### ISSUE TITLE
PLANFIKSPUNKTDK.KOTE

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#101]
Hvordan findes denne værdi?

Pt anvendes z.koordinaten; men det giver store afvigelser if.h.t. det som pt ligger i UM.
Eks: de 2 første kolonner er kote-værdier, sidste er id_lokalid
91.362	55.408	28
108.366	72.338	35
38.275	2.358	48
106.073	69.908	70
88.918	52.978	24
96.281	59.929	5801
40.483	2.535	29164

**Comment by kbevers** [comment]
Koten må skulle findes i nyeste koordinat med SRID EPSG:5799 (DVR90). Altså z-værdien. Hvis ikke der findes en DVR90-koordinat må koten skulle sættes til Null (hvis tilladt).

**Comment by Helle-Git** [comment]
Nu forsøges med:
Hvis der findes en aktuelt gældende  DVR90-koordinat til punktet, benyttes denne - ellers NULL

**Comment by busstoptaktik** [comment]
@Helle-Git jeg antager at denne kan lukkes
