### ISSUE TITLE
HOEJDEFIKSPUNKTDNN generelt

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#102]
Hvad er udtræksbetingelserne for disse?
F.eks. hvilke(n) SRIDID-værdier er kendetegnende for disse?

Konklusion:
Der udtrækkes for de punkter der har
* koordinater med sridid 11 eller 12    OG
* har punktinfo om regionskode enten 'REGION:DK eller 'REGION:SJ'
* har tilknyttede geometriobjekter

SRIDID 11 og 12:
11 | DK:GI44 | Kotesystem: Dansk Normal Nul, Sjælland
12 | DK:GM91 | Kotesystem: Dansk Normal Nul, Jylland

**Comment by kbevers** [comment]
Det er jo så højdefikspunkter med DNN koter. Det er SRID=EPSG:5733. Derudover vil jeg mene at udtræksbetingelserne er tilsvarende dem for HOEJDEFIKSPUNKTDK.

**Comment by Helle-Git** [comment]
Jeg kan pt. ikke finde punkter med koordinater med denne SRID (=10).
Kommer de en senere migrering, eller hvad gør jeg forkert?

**Comment by kbevers** [comment]
Nej, det gør du ikke. Det var mig der var for hurtig. DNN-koterne findes under DK:GI44 og DK:GM91. Det er SRIDID 11 og 12. 

Der er masser koordinater at arbejde med:

```
SELECT sridid, count(*) FROM koordinat WHERE sridid in (11,12) GROUP BY sridid;
```

```
SRIDID  COUNT(*)
11	    45193
12	    118469
```

**Comment by Helle-Git** [comment]
Tak, nogle punkter har tilknyttet begge typer af koordinater , f.eks. lokalid 3367 og 3368.
Hvilket koordinatsæt skal så benyttes?

**Comment by Helle-Git** [comment]
Der er - med dette udtrækskriterie - ca 115000 punkter i FIRE, mod ca 98000 i Fikspunktsreg.

Jeg har udtrukket 100 punkter - og får fejl på ca 20 om at der mangler geometri-oplysninger.
F.eks. lokalid 3854 og 3864.

**Comment by kbevers** [comment]
> Der er - med dette udtrækskriterie - ca 115000 punkter i FIRE, mod ca 98000 i Fikspunktsreg.
>
> Jeg har udtrukket 100 punkter - og får fejl på ca 20 om at der mangler geometri-oplysninger.
F.eks. lokalid 3854 og 3864.

Hvis man ser bort fra punkter uden geometri, er antallet af punkter så mere korrekt? Sådan slag på tasken er 80% af 115000 i omegnen af 98000.

**Comment by Helle-Git** [comment]
Hvis der ses bort fra punkter uden geometri, er det 97141.

**Comment by kbevers** [comment]
>  nogle punkter har tilknyttet begge typer af koordinater , f.eks. lokalid 3367 og 3368.
Hvilket koordinatsæt skal så benyttes?

Jeg fik ikke svaret på denne. Hvis begge er til stede så benyttes koordinaten med SRIDID=11 da de bør være nyest og dermed bedst.

> Hvis der ses bort fra punkter uden geometri, er det 97141.

Godt, så må udvælgelseskriterierne altså være: Punkter med SRIDID = 11 eller 12, som har en geometri tilknyttet.

**Comment by Helle-Git** [comment]
Et problem med koordinater, er at der kan være flere samtidige med samme SRID, måske de ikke er blevet af-registreret?
Eks

select registreringfra, registreringtil, sridid, sz, z, t, transformeret, punktid from fire_adm.koordinat
where punktid in ( '94E0B955-BD73-6CBC-E053-1A041EAC2E5E',
'94E0B955-BE29-6CBC-E053-1A041EAC2E5E')
and registreringtil is NULL
and sridid in (11, 12);

23/03/1990 13:27:01.000000 +02:00		11	5	15.8007	23/03/1990 13:27:00.000000 +02:00	false	94E0B955-BD73-6CBC-E053-1A041EAC2E5E
05/10/2005 15:17:04.000000 +02:00		11	1	2.43	05/10/2005 15:15:00.000000 +02:00	false	94E0B955-BE29-6CBC-E053-1A041EAC2E5E
23/03/1990 13:27:01.000000 +02:00		12	10	15.802	01/07/1900 00:00:00.000000 +02:00	false	94E0B955-BD73-6CBC-E053-1A041EAC2E5E
06/03/1991 07:36:01.000000 +02:00		12	5	2.441	11/03/1987 14:06:00.000000 +02:00	false	94E0B955-BE29-6CBC-E053-1A041EAC2E5E

**Comment by kbevers** [comment]
> Et problem med koordinater, er at der kan være flere samtidige med samme SRID, måske de ikke er blevet af-registreret?

Jeg vil ikke afvise at det forekommer, men dit eksempel herover viser det ikke. Begge de to punkter du spørger på har både en koordinat med sridid=11 og sridid=12 og altså ikke to koordinater med samme sridid. Hvis vi istedet tager dem en ad gangen er det nemmere at holde overblikket:

```
select registreringfra, registreringtil, sridid, sz, z, t, transformeret, punktid from fire_adm.koordinat
where punktid in ( '94E0B955-BD73-6CBC-E053-1A041EAC2E5E')
and registreringtil is NULL
and sridid in (11, 12);

1990-03-23 13:27:01	(null)	11	5	15.800700000000001	1990-03-23 13:27:00	false	94E0B955-BD73-6CBC-E053-1A041EAC2E5E
1990-03-23 13:27:01	(null)	12	10	15.802	            1900-07-01 00:00:00	false	94E0B955-BD73-6CBC-E053-1A041EAC2E5E

-------------------

select registreringfra, registreringtil, sridid, sz, z, t, transformeret, punktid from fire_adm.koordinat
where punktid in ( '94E0B955-BE29-6CBC-E053-1A041EAC2E5E')
and registreringtil is NULL
and sridid in (11, 12);

2005-10-05 15:17:04	(null)	11	1	2.43	            2005-10-05 15:15:00	false	94E0B955-BE29-6CBC-E053-1A041EAC2E5E
1991-03-06 07:36:01	(null)	12	5	2.4409999999999998	1987-03-11 14:06:00	false	94E0B955-BE29-6CBC-E053-1A041EAC2E5E
```

**Comment by Helle-Git** [comment]
Jeg har nu lavet udtræk af 'alle' DNN-højdefikspunkter; MEN

Der er **2830 punkter som udtrækkes, der ikke har en tilsvarende i UM**.
De fordeler sig således på SRID:
SRID 11: 526 punkter, SRID12: 2304 punkter.  
Eksempler på lokalid, punktid:

75252 | 95582745-5422-3280-E053-1A041EAC5624
-- | --
65016 | 95582745-2C28-3280-E053-1A041EAC5624
74219 | 95582745-5019-3280-E053-1A041EAC5624
74238 | 95582745-502C-3280-E053-1A041EAC5624
75301 | 95582745-5453-3280-E053-1A041EAC5624
75326 | 95582745-546C-3280-E053-1A041EAC5624
75330 | 95582745-5470-3280-E053-1A041EAC5624
5147 | 95582744-427B-3280-E053-1A041EAC5624
5799 | 95582744-4507-3280-E053-1A041EAC5624
72470 | 95582745-4945-3280-E053-1A041EAC5624
72662 | 95582745-4A05-3280-E053-1A041EAC5624

Der er 5132 punkter i UM, som IKKE er udtrukket:
Der har vist bl.a. srid 7 og 13 ??
Eksempler på lokalid og fikspunktsnummer:

1807 | K-01-06948
-- | --
3244 | K-01-09115
17276 | K-25-09068
1164 | K-01-06295
64405 | 1-00-06194
852732 | 14-14-09029
778219 | K-01-00155
64457 | 1-00-06249
728571 | 138-01-09076
2516 | K-01-07684
232172 | 46-06-09008

**Comment by kbevers** [comment]
> Der har vist bl.a. srid 7 og 13 ??

Ja, det ser sådan ud. Prøv at medtage EPSG:5714 og DK:KN44 og se om ikke antallet af punkter kommer til at passe bedre så.

**Comment by Helle-Git** [comment]
Ni tages alle 4 SRID-værdier med.
Jeg udtrækker pt ikke alle (det tager så laaang tid), så jeg laver mindre udtræk - pt med 10000 punkter.
Af disse er 293 ikke i UM i forvejen, det er relativt mange.
Så der er nok et kriterium mere, der skal bruges til at identificere dem (hvis de ikke skal medtages)

**Comment by busstoptaktik** [comment]
Artskode for DNN sættes til "punkter i net af lavere eller ukendt kvalitet". Evt. transformerede DNN koter skal ikke længere udstilles.

**Comment by busstoptaktik** [comment]
> Så der er nok et kriterium mere, der skal bruges til at identificere dem (hvis de ikke skal medtages)

EPSG:5714 bør nok alligevel udelades. Jeg skal lige have kigget nærmere på KN44.

Det er ikke nogen katastrofe at der kommer færre punkter med over i det nye setup, men vi skal helst ikke lukke hidtil ikke-publicerede ud i det fri.

**Comment by Helle-Git** [comment]
Der udtrækkes pt. en del punkter, som IKKE kan tildeles et fikspunktsnummer.
Nogle af dem har et ekstern-nummer (IDENT:ekstern)  a la '4078/24700H3'.
Andre har transformerede GI44-koordinater.
MEN om dette er udelukkelses-kriterier er UVIST !!!!!
De få stikprøver jeg har foretaget er IKKE kendte i UM. 
(lokalid: 757788, 850399, 850401, 850408, 72191, 72192, 72195)

**Comment by Helle-Git** [comment]
Jeg udtrækker nu med de nye kriterier.
Jeg ved ikke om punkter, der 'kun' har IDENT-attribut IDENT:diverse (evt. IDENT:ekstern er ignoreret) skal tages med.
Efter at have analyseret ca 65000 (ca ½delen), er der 3 punkter, der ikke kan bestemmes herreds-oplysninger for. Det ene af disse findes i UM's DNN-tabel, de 2 andre gør ikke (men det ene findes som dansk højdefikspunkt). 
De har disse fikspunktsnumre, IDENT-type og lokalid:
 199-01-99028.1 IDENT:diverse 862965
 199-01-92371.1 IDENT:diverse 862851
 24-01-00032.1  IDENT:diverse 783607   * findes i UMs DNN-tabel

**Comment by kbevers** [comment]
Jeg synes du også skal udelade IDENT:diverse. Men det var godt du ikke gjorde det i første omgang, for de tre identer du har fundet frem skulle være klassificeret som landsnumre. Jeg opdaterer min kode så de placeres korrekt i næste kørsel af migrationen.

**Comment by busstoptaktik** [comment]
> Jeg opdaterer min kode så de placeres korrekt i næste kørsel af migrationen.

@kbevers, hvis denne er i orden, så bare luk dette issue, og fortsæt diskussionen ovre på #134

**Comment by kbevers** [comment]
Disse burde være på plads nu.

**Comment by Helle-Git** [comment]
Det overordnede udvalgskriterium er nu udvidet, så der KUN medtages punkter, som har tilknyttet mindst eet gældende  IDENT:-attribut (som ikke er landsnr eller diverse). Dvs mindst en af disse:
 IDENT:landsnr, IDENT:GNSS, IDENT:GI  eller IDENT:jessen
