### ISSUE TITLE
FIKSPUNKTSYS34: Identificer ca. 30000 punkter der mangler i FIRE

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#104]
Hvordan hentes data til denne?
REGION:DK eller REGION:SJ, samt 
SRID:  DK:S34S eller DK:S34J

Dette giver 496198 (aktuelle) punkter i FIRE, der er 497601 aktuelle i FIKSPUNKT/GeoBank

Nogle punkter har koordinater med begge SRID, hvilken skal så vælges?

**Comment by kbevers** [comment]
Husk også DK:S45B (SRIDID 23). Så vidt jeg kan se gør det ikke den store forskel at udvælge ud fra region - der er ikke System34/45 koordinater andre steder end i Danmark.

Så vidt jeg kan se er der kun ganske få punkter der har både S34S og S34J koordinater (under 200). Jeg har kigget på cirka ti af de punkter og det ser ud til at den koordinatsystemet der er brugt i udstillingsmodellen er det som punktet først er blevet registreret i. Så fx er 94-01-00103 registreret som S34S i udstillingsmodellen, da den aktive S34S koordinat er ældre end den aktive S34J koordinat. Der findes ikke punkter hvor S45B findes samtidigt med S34S/S34J.

**Comment by Helle-Git** [comment]
Der er punkter med begge sridid-koordinater.
Jeg er i tvivl om hvilken dato jeg skal bruge - registreringfra, eller T - men i begge situationer er der 'dubletter'.
Så 2 spørgsmål:
* Hvilken dato skal benyttes?
* Hvilket yderligere kriterium skal benyttes, når datoerne er ens?

Eksempler med dato 'T':
punktid:9502C9D6-90A8-2EE8-E053-1A041EACA231  lokalid:138970  
punktid:9502C9D6-C6E3-2EE8-E053-1A041EACA231  lokalid:152878

**Comment by Helle-Git** [comment]
Der er punkter, som ikke har punktinformation, til at bestemme fikspunktsnummer udfra.
F.eks.:
punktid 9502C9D7-162E-2EE8-E053-1A041EACA231  lokalid:173199
punktid 9502C9D7-162F-2EE8-E053-1A041EACA231  lokalid:173200 
punktid 9502C9D7-168D-2EE8-E053-1A041EACA231  lokalid:173294  
punktid 9502C9D7-168E-2EE8-E053-1A041EACA231  lokalid:173295

Jeg har ikke fundet disse  lokalid i UM, så måske skal de slet ikke over til FIRE?

**Comment by kbevers** [comment]
> Hvilken dato skal benyttes?

T

> Hvilket yderligere kriterium skal benyttes, når datoerne er ens?

Det er hip som hap. Tag koordinaten med det laveste objectid. 

> Jeg har ikke fundet disse lokalid i UM, så måske skal de slet ikke over til FIRE?

Jo, det skal de, men de burde nok have en registreringtil-dato så det er klart at det er aflyste punkter. I REFGEO har de MV_STATUS=-1 hvilket betyder at punktet ikke er i brug. Desværre findes der ikke information om hvornår MV_STATUS=-1 er sat, så det er lidt en udfordring at afregistrere punktet i FIRE. Der kan dog altid faldes tilbage på en opdigtet registreringtil dato. Jeg tror ikke selv jeg kan løse problemet men jeg tager lige et kig i Nikolajs SQL og forsøger at spore mig ind på hvor ændringen skal laves.

For nu må du nøjes med at se bort fra de punkter.

**Comment by Helle-Git** [comment]
Det blev aftalt at se bort fra  transformerede koordinaterne ; dvs punkter, hvor aktuelt gældende koordinat-sæt er transformerede tages ikke med.

Der udtrækkes nu 483219 punkter fra FIRE, hvoraf de 15 (og evt. yderligere 10) ignoreres.
Af findes de 344 punkter KUN i FIRE (ikke i UM-tabellen);
Mens der er 32449 i UM-tabellen, som 'mangler'
Der er 497601 aktuelt gældende punkter/rækker i UM-tabellen.

**Comment by busstoptaktik** [comment]
Det er sgu lidt mystisk det her. Jeg kan heller ikke få tallene til at gå op. Er s45b kommet med i opgørelsen over punkter i FIRE?

Omdøber issue til at dække dette ubehagelige element

**Comment by kbevers** [comment]
Det vil være en fordel om vi kan få en håndfuld eksempler på punkter der findes i REFGEO-UM som ikke overføres til FIRE-UM. Forhåbentligt er der noget systematik at spore.

**Comment by busstoptaktik** [comment]
@Helle-Git jeg assigner denne til dig, jvf. @kbevers kommentar ovenfor

**Comment by Helle-Git** [comment]
Denne må nok vente på at der igen er data i koordinat-tabellen med de relevante sridid'er.

**Comment by Helle-Git** [comment]
Jeg har dd sendt regneark med dagens test-resultater, heri er en del håndfulde lokalid'er.

En mindre håndfuld med lidt oplysninger:


ID_LOKALID | FIKSPUNKTSNUMMER | X | Y | MIDDELFEJL | AFMAERKNINGSBESKRIVELSE
-- | -- | -- | -- | -- | --
107180 | 8-02-00042 | 103699,62 | 161226,6 | 999 |  
109573 | 8-09-00033 | 103316,41 | 161325,76 | 999 |  
112288 | 9-02-75114 | 89756,304 | 152097,948 | 30 |  
119727 | 11-05-00809 | 90412,99001 | 182771,76 | 40 | Jernrør i støbning. 0.05 m over terræn.
119728 | 11-05-00810 | 90787,8 | 183211,32 | 40 | Tabtgået
127 | K-01-00878 | 74295,57 | 143305,65 | 40 | Tabtgået
130624 | 13-04-00288 | 77126,96 | 168592,09 | 999 | Tabtgået
130625 | 13-04-00289 | 77240,16 | 168624,98 | 999 | Tabtgået

**Comment by kbevers** [comment]
Så vidt jeg lige kan se, så er ingen af punkterne nævnt i tabellen ovenfor at finde i REFGEO-UM's FIKSPUNKTSYS34 tabel. Jeg antager at de så fejlagtigt overføres til FIRE-UM, er det korrekt?

**Comment by Helle-Git** [comment]
Testen gav 

KUN i FIRE | 1798
-- | --
KUN i UM | 16180

Dem i tabellen, er eksempler på punkter 'KUN i FIRE' - dvs de vil blive udstillet.. (men er det ikke i dag).  Om de er fejlagtigt - det må I afgøre.

**Comment by Helle-Git** [comment]
Eksempler på punkter, som IKKE bliver udtrukket - men findes i UM:


ID_LOKALID | FIKSPUNKTSNUMMER | X | Y | SYSTEM34VERSION | MAALEMETODE | GMLID
-- | -- | -- | -- | -- | -- | --
100073 | 5-06-00234 | 97978,43 | 117895,35 | System34Sjælland | ukendt målemetode | fiks.100073.19950109115000
100077 | 5-06-00238 | 98542,55 | 117778,85 | System34Sjælland | ukendt målemetode | fiks.100077.19950109115000
100085 | 5-06-00246 | 97240,06 | 118254,12 | System34Sjælland | fotogrammetrisk opmålt | fiks.100085.19950109115001
100218 | 5-06-00380 | 95110,01 | 118459,97 | System34Sjælland | fotogrammetrisk opmålt | fiks.100218.19950109115001
100219 | 5-06-00381 | 94946,07 | 118806,84 | System34Sjælland | fotogrammetrisk opmålt | fiks.100219.19950109115001
100220 | 5-06-00382 | 101217,01 | 116924,05 | System34Sjælland | fotogrammetrisk opmålt | fiks.100220.19950109115001
100221 | 5-06-00383 | 100740,24 | 116763,41 | System34Sjælland | fotogrammetrisk opmålt | fiks.100221.19950109115001

**Comment by kbevers** [comment]
> Dem i tabellen, er eksempler på punkter 'KUN i FIRE' - dvs de vil blive udstillet.. (men er det ikke i dag). Om de er fejlagtigt - det må I afgøre.

Jeg forstår. Jeg må være kommet til at kigge i en forkert tabel da jeg tjekkede punkterne i UM.

Jeg forstår til gengæld ikke hvorfor de punkter fra din tabel ovenfor *ikke* kommer med over til FIRE-UM. Så vidt jeg kan se er der ikke noget der skulle diskvalificere dem fra at blive trukket ud. Hvilke kriterier bruger du til at udvælge System34/45 koordinater med? I beskrivelse af dette issue antydes at en kombination af REGION:DK/REGION:SJ samt DK:S34S, DK:S34J og DK:S45 benyttes, men jeg kan ikke helt gennemskue hvad der aktuelt står i dit script. Mit bedste gæt lige nu er at det er der problemet skal findes.

**Comment by Helle-Git** [comment]
Opsummering:
Nu udtrækkes aktuelt gældende punkter som opfylder:
- har koordinat med SRIDID 21,22 eller 23 som IKKE er transformeret
- der findes (gældende) punktinformation med mindst en af (
ident_landsnr,   ident_gi, ident_gnss, ident_jessen, ident_diverse) 
- der er tilknyttet mindst et gældende geometriobjekt

**Comment by kbevers** [comment]
Tak Helle. Jeg har kigget nærmere på punkterne ovenfor. De har allesammen transformerede koordinater, så det er der kattten er begravet.

@busstoptaktik Er du stadig af den overbevisning at vi skal udelade transformerede koordinater?

**Comment by busstoptaktik** [comment]
> Er du stadig af den overbevisning at vi skal udelade transformerede koordinater?

Det ser ud som om vi er nødt til at tage dem med:

-  I S34-UM fordi de formodentlig er i brug
- I PFP-UM fordi det i en eller anden grad giver mening at vi, når der skiftes system, er nødt til, i en overgangsperiode, som p.t. har varet 20-30 år, at udstille transformerede koordinater, fordi punkterne endnu ikke har været genindmålt, og på en eller anden måde er man jo nødt til at gøre systemet tilgængeligt...

Så vi slipper med andre ord ikke... og med den konklusion kan denne vel lukkes.

**Comment by Helle-Git** [comment]
Nu medtages de transformerede koordinater
