### ISSUE TITLE
FIKSPUNKTSYS34.X  og Y

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#107]
Hvordan bestemmes disse felters værdier?

**Comment by busstoptaktik** [comment]
@Helle-Git - kan denne lukkes?

**Comment by busstoptaktik** [comment]
@Helle-Git - eller rettere: Jeg lukker den nu, men genåbn hvis @kbevers svar ikke er udtømmende

**Comment by Helle-Git** [comment]
Hvis der er flere (gældende) koordinatsæt for punktet, hvilket skal så benyttes?

**Comment by kbevers** [comment]
> Hvis der er flere (gældende) koordinatsæt for punktet, hvilket skal så benyttes?

Er det ikke samme fremgangsmåde som beskrevet i https://github.com/Kortforsyningen/FIRE-DDL/issues/104 ?

**Comment by busstoptaktik** [comment]
@Helle-Git jeg antager at du implicit er enig i @kbevers spørgende svar:

> Er det ikke samme fremgangsmåde som beskrevet i #104 ?

og lukker

**Comment by Helle-Git** [comment]
Som for MIDDELFEJL (der også kommer fra koordinat):

Der kigges på koordinater med sridid 21, 22 eller 23.

21	DK:S34J	Projicerede koordinater 2D: System 34 Jylland
22	DK:S34S	Projicerede koordinater 2D: System 34 Sjælland
23	DK:S45B	Projicerede koordinater 2D: System 45 Bornholm

Hvis der for et punkt er flere aktuelt gældende koordinatsæt, 
benyttes det, med den tidligste værdi af 'T' .

**Comment by busstoptaktik** [comment]
@Helle-Git der er en del tilfælde af meget store (flere dekameter) afvigelser mellem S34-koordinater i UM og FIRE. Fx punktet med `refgeo_id=10229`, hvor `x(FIRE)=162661`, mens `x(UM)=162644`.

Det ser simpelthen ud til at skyldes at det er S34J-værdien der vælges det ene sted, mens det er S34S-værdien det andet, jvf. dette udtræk fra fire info punkt 10229:

    * 1989-09-13 13:05   EPSG:4258      11.1214975, 55.3403901 (35.0, 35.0)
    * 1989-09-18 11:28   EPSG:23032     634628.158, 6134926.16 (20.0, 20.0)
    * 1987-08-31 11:15   DK:SB          509901.124, 6135333.53 (20.0, 20.0)
    * 1989-09-13 13:05   DK:S34S        162643.708, 101206.489 (20.0, 20.0)
    * 1985-08-30 12:31   DK:S34J        162660.93, 101198.909 (20.0, 20.0) 

De to systemer er sammenfaldende ved Agri Bavnehøj, der i begge systemer har koordinaterne (200000 m, 200000m) - derfor er afvigelserne i et punkt med koordinater i begge systemer tilstrækkeligt tæt på hinanden til at drive landinspektører til vanvid.

Så lukker denne igen-igen

**Comment by Helle-Git** [comment]
Udtræk fra de to (UM og FIRE), viser der vælges forskellige koordinatsystemer:

 -- |  --  |  --  |  --  |  --
fikspunktsnummer | middelfejl | x | y | system34version
K-11-00001 | 20 | 162643.708 | 101206.489 | System34Sjælland
K-11-00001  | 20 | 162660.93 |  101198.909   | System34Jylland

**Comment by busstoptaktik** [comment]
30 grove afvigelser passer også sammen med

SYSTEM34VERSION-grupperinger | 30 | System34Jylland | System34Sjælland
-- | -- | -- | --
