### ISSUE TITLE
HOEJDEFIKSPUNKTFO  Generel

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#109]
Hvordan identificeres punkter til denne?

Forslag: 
sridid=**EPSG:5317**  samt punktinfo= **REGION:FO**

**Comment by kbevers** [comment]
Du kan godt nøjes med bare at vælge på baggrnud af EPSG:5317. Der er ikke punkter udenfor Færøerne der har den SRID.

**Comment by busstoptaktik** [comment]
Lukker denne. Fortsæt generel diskussion om færøske højdefikspunkter ovre på #135
