### ISSUE TITLE
HOEJDEFIKSPUNKTGL  Generel

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#110]
Hvordan identificeres punkterne til denne?

Forslag:

srid= **EPSG:4747** samt punktinfo =**REGION:GL**

**Comment by kbevers** [comment]
EPSG:4747 dækker over længe- og breddegrader ikke koter. I Grønland er koter registeret som lokal middelvandstand, hvilet er EPSG:5714. Regionen skal rigtigt nok tages i betragtning her da der også findes danske middelvandstandskoter.

**Comment by Helle-Git** [comment]
Med dette kriterium (SRID=7 og REGION:GL) 
finder jeg ca. 30000 aktuelle punkter - i UM er der ca. 8000.

Så der skal nok en begrænsning mere på - men hvilken??

**Comment by Helle-Git** [comment]
Jeg har tilføjet begr.  at punktet også skal have punktinfo 'ATTR:Højdefikspunkt'.

SÅ er der 8622 punkter (mod  8165 i UM).

MEN af disse er der 409 uden tilknyttet geometri.
Er denne manglende geometri udtryk for fejl i FIRE - eller skal jeg kun udtrække punkter med geometriobjekter?

**Comment by kbevers** [comment]
Umiddelbart tror jeg ikke det er en fejl at der ikke findes geometri. Udtræk kun dem der har en geometri. Så ser det også ud til at antallet passer ret godt.

**Comment by busstoptaktik** [comment]
> I Grønland er koter registeret som lokal middelvandstand, hvilet er EPSG:5714

... så GVR2016 bliver en sag for næste udgave af udstillingsmodellen :-)

**Comment by busstoptaktik** [comment]
Ovenstående ser ud til at være løst. Videre diskussion om emnet fortsætter under #136 - lukker denne
