### ISSUE TITLE
HOEJDEFIKSPUNKTGL.EASTING og NORTHING

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#111]
Hvordan bestemmes disse?

Den 'almene' algoritme fra HOEJDEFIKSPUNKTDK siger 
SDO_CS.TRANSFORM(g.geometri, 25832).sdo_point.y

Men for disse grønlandske punkter giver det ret store forskelle ifht UM; f.eks.

ATTRIB | NUM_I_FIRE | NUM_I_FIKS | LOKALID_FIRE
-- | -- | -- | --
northing | 8465325 | 7193439 | 785506
northing | 8513922 | 7178850 | 785505
northing | 8513859 | 7178806 | 785504

**Comment by kbevers** [comment]
Samme algoritme skal bruges, dog skal `25832` skal erstattes med den relevante kode i Grønland.  Jeg vil tro at det er `32622`. Hvis heller ikke det passer så prøv med `32624`. Det er henholdsvis WGS84 UTM Zone 22 og Zone 24, det burde være en af de to.

**Comment by busstoptaktik** [comment]
@Helle-Git og @kbevers jeg antager at denne kan lukkes

**Comment by Helle-Git** [comment]
Jeg benytter nu 32624 (32622 giver MEGET store afvigelser i forhold til UM).

Hvor store afvigelser er acceptable?  (mellem FIRE og UM)
Der er 259 med en hypot-difference > 10.
Der er 456, hvor northing afviger på heltals-delen (rundet af til 0 decimaler)
Der er 1980, hvor easting afviger på heltals-delen (runde af til 0 decimaler)

456
--




456
--

**Comment by kbevers** [comment]
Jvf. min mail fra d. 7. november skal easting og northing ikke afledes af geometrien, men fra koordinaten. Det gælder for alle planfikspunkter.

Så for koordinaten `k` kan easting og northing beregnes med: 
```
SDO_CS.TRANSFORM(SDO_GEOMETRY(2001, 4747, SDO_POINT_TYPE(k.x, k.y, NULL), NULL, NULL), 32624).SDO_POINT.x easting,
          SDO_CS.TRANSFORM(SDO_GEOMETRY(2001, 4747, SDO_POINT_TYPE(k.x, k.y, NULL), NULL, NULL), 32624).SDO_POINT.y northing,
```

I virkeligheden burde man kunne nøjes med et kald til SDO_CS.TRANSFORM, men det kan jeg ikke lige finde ud af at gøre, så her får du bare en dum teknik der gør det to gange.

Jeg ved ikke om ovenstående løser problemet, men det er i øjeblikket mit bedste bud. Selvom mit udredning fra d.7. overbeviste mig om at det nok ikke var det der er problemet...

**Comment by busstoptaktik** [comment]
Det ser ud som om der er røget et argument og/eller en slutparentes - eller er det bare mig der ikke kan tælle/læse indenad?

**Comment by kbevers** [comment]
Det er dig der ikke kan tælle

**Comment by busstoptaktik** [comment]
OK - har den nu - efter copy+paste ind i flad tekst og tælleigenigenogengangtil (med tunen lige i månen) :-)

**Comment by Helle-Git** [comment]
> Det gælder for alle planfikspunkter.

Øhh, dette omhandler danske HØJDE-fikspunkter ..

**Comment by kbevers** [comment]
> Øhh, dette omhandler danske HØJDE-fikspunkter ..

Ups, min fejl. Se bort fra ovenstående. Men det må vel da i øvrigt være Grønlandske højdefikspunkter vi snakker om her?

**Comment by busstoptaktik** [comment]
Afvigelser på heltallet er ikke noget problem for placeringskoordinaten, men:

> Der er 259 med en hypot-difference > 10.

Kan du lave en liste over hvilke punkter det drejer sig om og hvor stor afvigelsen er (punkt-id, længde, bredde, afvigelse)?

Jeg kan frygte at Oracle måske alligevel ikke er så skarpe på UTM-transformation som @kbevers test i forgårs antydede:

@kbevers - jeg tror at de nuværende geo_gr96-placeringkoordinater i FIRE er baseret på utm24_gr96-koordinater fra REFGEO, omregnet under migreringen med SDO-funktioner. Er det korrekt?

I så fald er det vi ser (idet @Helle-Git  jo regner tilbage igen for at få det til at passe med udstillingsmodellen), jo sandsynligvis at Oracles UTM-implementering ikke roundtripper specielt godt langt fra centermeridianen, hvilket også er hvad vi ville forvente hvis den var baseret på John Snyders
gamle rækkeudvikling.

I så fald må vi regne med at ca. halvdelen af fejlen ligger i overgangen REFGEO->FIRE, og halvdelen den anden vej.

Jeg synes det lyder som om der er behov for endnu en REFGEO-hjælpetabel med PROJ-beregnede geo_wgs84-koordinater for grønlandske punkter: Dermed kan vi i hvert fald eliminere den ene halvdel af fejlen. Resten kommer på plads når vi ad åre retter udstillingsmodellen til.

@Helle-Git - hvis ingen af de 259 afvigelser går over 50 m kan du godt lukke dette issue igen. Der skal gøres noget ved det, men det er ikke et problem i mappingsammenhæng.

**Comment by kbevers** [comment]
> @kbevers - jeg tror at de nuværende geo_gr96-placeringkoordinater i FIRE er baseret på utm24_gr96-koordinater fra REFGEO, omregnet under migreringen med SDO-funktioner. Er det korrekt?

Det tror jeg ikke, nej. Det sker i hvert fald ikke i https://github.com/Kortforsyningen/FIRE-DDL/blob/master/Migration /MakeGeometriObjekt.sql og så ved jeg ikke hvor det ellers skulle ske.

**Comment by Helle-Git** [comment]
I det regneark med tjek-resultater, som jeg sendte i går, er der faneblad med HFPGL-detaljer.
Heri står hypot-værdi og lokal-id, for de 25 punkter med størst hypot-værdi.

De største hypot-værdier er 34,80124402, 34,839679 og 34,84267055.

**Comment by busstoptaktik** [comment]
> I det regneark med tjek-resultater, som jeg sendte i går, er der faneblad med HFPGL-detaljer

Undskyld, Helle - jeg sad og kiggede på fanebladet med titel "HFPGL v.2 udv detaljer" og kunne ikke finde noget der lignede hypot-værdier. Jeg ser dem nu, og trækker lige koordinaterne ud og tager et overblik, når jeg kan nå frem til det (er i skrivende stund på vej til Kortdage)

**Comment by Helle-Git** [comment]
Der er 2 punkter med hypot-værdi over 50,
Hypot-værdi | lokalid
-- | --
57.0582798970878	| 767856
50.9618044327289	| 767853

Jeg har udtrukket nogle informationer om disse 2 punkter, fra hhv FIRE og UM:


FIKSPUNKTSNUMMER | SRID | GEOM_X | GEOM_Y | EASTING | NORTHING | ID_LOKALID | PUNKTID
-- | -- | -- | -- | -- | -- | -- | --
2028 | 32624 | -265878,1173 | 8939109,208 | -265878,1173 | 8939109,208 | 767853 | 97886973-05FA-5A7A-E053-1A041EACC99C
2028 | 32624 | -265878,1173 | 8939109,208 | -265927,81 | 8939120,51 | 767853 | - Udstillede data -
2031 | 32624 | -281289,3738 | 8935342,853 | -281344,99 | 8935355,6 | 767856 | - Udstillede data -
2031 | 32624 | -281289,3738 | 8935342,853 | -281289,3738 | 8935342,853 | 767856 | 97886973-05FD-5A7A-E053-1A041EACC99C

De 2 rækker hvor punktid er '- Udstillede data -'  indeholder data fra UM.
SRID, GEOM_X, og GEOM_Y er hentet fra geometri-feltet.

Det hele er hentet med denne SQL:

select fikspunktsnummer, 
 SDO_CS.TRANSFORM(g.geometri, 32624).sdo_srid srid,
 to_char(SDO_CS.TRANSFORM(g.geometri, 32624).sdo_point.x,'9999999D999999999') geom_x,  
 to_char(SDO_CS.TRANSFORM(g.geometri, 32624).sdo_point.y,'9999999D999999999')  geom_y, -- SDO_CS.TRANSFORM(g.geometri, 32624).sdo_point.z z,
to_char(easting,'9999999D999999999') easting, to_char(northing,'9999999D99999999') northing, id_lokalid, punktid 
from hfpgl g
where id_lokalid in (767856, 767853) 

union
select fikspunktsnummer, 
 SDO_CS.TRANSFORM(g.geometri, 32624).sdo_srid,
 to_char(SDO_CS.TRANSFORM(g.geometri, 32624).sdo_point.x,'9999999D999999999')x,   
 to_char(SDO_CS.TRANSFORM(g.geometri, 32624).sdo_point.y, '9999999D999999999') ,  --SDO_CS.TRANSFORM(g.geometri, 32624).sdo_point.z,
to_char(easting,'9999999D999999999') easting, to_char(northing,'9999999D99999999'),  id_lokalid, '- Udstillede data -' punktid 
from hoejdefikspunktgl@fikspunkt_l1 g
where id_lokalid in (767856, 767853)
and registreringtil is NULL
;

**Comment by kbevers** [comment]
Det ser ud til at være forskelle i transformationsmaskineriet i Oracle og den Frandske kode. Jeg tror ikke vi kan gøre noget ved det med det setup vi  har nu. Skal det gøres bedre må vi inddrage kordinattransformation fra ekstern programmel og det er vist langt uden for scope af denne mapning.

**Comment by kbevers** [comment]
Lukket med https://github.com/Kortforsyningen/FIRE-DDL/commit/5b5151cf74852a6e7927a7cdb50725757c6ab5ea og efterfølgende forbedringer.
