### ISSUE TITLE
GEOMETRIOBJEKT kun-eet-pr-punkt-adgangen-constraint 

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#112]
Jeg savner constraint på GEOMETRIBOBJEKT som sikrer at der kun er een samtidig forekomst pr punkt(id).
Det kan tjekkes ifm overførsel til Gepbanken; men det bør vel være en constraint i FIRE?
Pt. er det opfyldt.

**Comment by kbevers** [comment]
Det lyder som en god ide. Det skal vel være max et "aktivt" geometriobjekt pr punkt? Jeg kan sagtens se at det bliver nødvendigt at ændre et punkts geometri fremtiden (der findes i dag mange der er meget forkerte).

Har du mod på selv at lave sådan en constraint? Den skal tilføjes i https://github.com/Kortforsyningen/FIRE-DDL/blob/master/DDL.sql

**Comment by Helle-Git** [comment]
Jeg vil foreslå et unikt index, som dette.
Jeg har lagt det på nu; men det forsvinder jo ved næste indlæsning:

create unique index geomobj_datopid on geometriobjekt(punktid, registreringfra);

**Comment by kbevers** [comment]
> Jeg har lagt det på nu; men det forsvinder jo ved næste indlæsning

Hvis du tilføjer det til https://github.com/Kortforsyningen/FIRE-DDL/blob/master/DDL.sql så kommer det med ved næste indlæsning.

**Comment by Helle-Git** [comment]
Mit manglende kendskab til Github/GitLab gør at jeg pt ikke vil lægge noget kode ind

**Comment by kbevers** [comment]
Okay, så gør jeg det...

**Comment by kbevers** [comment]
Der findes tilsvarende constraints for nogle af de andre tabeller, fx

```
CREATE UNIQUE INDEX OBSERVATIONSTYPE_IDX_001 ON OBSERVATIONTYPE
(OBSERVATIONSTYPEID);
 
ALTER TABLE OBSERVATIONTYPE ADD
CONSTRAINT OBSERVATIONTYPE_U01
UNIQUE (OBSERVATIONSTYPEID)
USING INDEX OBSERVATIONSTYPE_IDX_001
ENABLE VALIDATE;
```

Skal jeg også tilføje `ALTER TABLE ...` for denne constraint?

**Comment by kbevers** [comment]
Tilføjet med cb70f13 og sidenhen https://github.com/Kortforsyningen/FIRE/pull/227
