### ISSUE TITLE
FIKSPUNKTSYS34.MAALEMETODE og ARTSKODE

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#113]
Hvordan bestemmes disse?

Med de kendte algoritmer fås mange forskelle; for 25000 fikspunkter er der denne fordeling:
Kolonnerne er Tjek, antal, Værdi hentet fra FIRE, Værdi i UM

Målemetode-grupperinger | 732 | terrestrisk måling | fotogrammetrisk opmålt
-- | -- | -- | --
Målemetode-grupperinger | 133 | terrestrisk måling | GPS opmålt
Målemetode-grupperinger | 168 | terrestrisk måling | ukendt målemetode
Målemetode-grupperinger | 15796 | terrestrisk måling | blanding af terrestrisk måling med GPS eller fotogrammetrisk måling
  |   |   |  
Artskode-grupperinger | 2 | overordnet højdefikspunktsnet | overordnet planfikspunktsnet
Artskode-grupperinger | 1762 | Punkt i net af lavere eller ukendt kvalitet | overordnet planfikspunktsnet
Artskode-grupperinger | 1 | overordnet højdefikspunktsnet | punkt i net af høj kvalitet
Artskode-grupperinger | 953 | Punkt i net af lavere eller ukendt kvalitet | punkt i net af lav kvalitet bestemt ved få eller ingen overbestemmelse
Artskode-grupperinger | 433 | Punkt i net af lavere eller ukendt kvalitet | punkter i net af lavere eller ukendt kvalitet
Artskode-grupperinger | 20941 | Punkt i net af lavere eller ukendt kvalitet | punkt i net af høj kvalitet
Artskode-grupperinger | 4 | Punkt i net af lavere eller ukendt kvalitet | fundamental punkt

**Comment by busstoptaktik** [comment]
Jeg starter lige gættelegen her:

**Målemetode**

"Ægte" S34-koordinater bør under alle omstændigheder være opstået ved terrestrisk måling.

Transformerede S34-koordinater arver muligvis p.t. deres ophavskoordinats målemetode. De bør nok alle omklassificeres til "ukendt målemetode", for det er oftest transformationen og ikke målemetoden, der bestemmer nøjagtigheden.

Hvordan ser det ud hvis du frasorterer transformerede værdier?

**Artskode**

Den store gruppe hvor vi har "lavere eller ukendt" i FIRE og "høj kvalitet" i UM kan godt bekymre mig, for det kunne tyde på en fejl i migreringen REFGEO->FIRE. I det hele taget ser det jo lidt mystisk ud, og vi skal nok lige have @mrlarshole til at kaste et britisk klik på den del...

**Comment by Helle-Git** [comment]
**Målemetode**
Pt. er algoritmen at den ALTID sættes til 'terrestrisk måling' for SYS34.

**Comment by mrlarshole** [comment]
Thomas antagelse om at transformerede S34-koordinater har arvet bl.a. deres ophavskoordinats målemetode er, mig bekendt og i min tid, rigtig. De blev indsat med artskode 6 så man kunne se at de var transformeret. man kunne så ved at kigge i ophavstabellen og journalen finde oplysninger om oprindelsen og forklaring/formål til transformationen. Det er efter "nu om dages" omstændigheder lidt noget rod og i virkeligheden skulle man nok ikke, i det hele taget, udstille transformerede koordinater, men kun de oprindelige og lade det være op til bruger selv at transformere. Der har historisk set været et behov og er muligvis stadig. Man bør undersøge disse i fald det besluttes ikke at udstille trans. Det ville være lækkert.

**Comment by mrlarshole** [comment]
Herunder udtræk af hhv. UM og REFGEO sammenlignet med Helles 25000. Procentsatserne er nogenlunde ens taget i betragtning at der fra REFGEO kun er kigget på s34j. Det vides ikke hvilke 25000 punkter Helle har kigget på men mit gæt er at de ikke repræsenterer et bredt udvalg(ingen terrestriske), ellers er der måske noget galt i migreringen?
Maalemetode | UM | REFGEO | Helles 25000
terrestrisk måling | 41 | 55 | 0
blanding af terrestrisk måling med GPS eller fotogrammetrisk måling | 53 | 37 | 94
GPS opmålt | 1 | 1 | 1
fotogrammetrisk opmålt | 5 | 6 | 4
barometrisk opmålt | 0 | 0 | 0
ukendt målemetode | 1 | 1 | 1

**Comment by busstoptaktik** [comment]
> Pt. er algoritmen at den ALTID sættes til 'terrestrisk måling' for SYS34.

Det er helt som det skal være

**Comment by busstoptaktik** [comment]
> Da der ikke er en fornuftig algoritme pt, sættes ARTSKODE altid til ''Aner det ikke ??!!''

Det er fint for nu. Jeg skal lige have snakket med Søren om vi kan slippe afsted med at kalde alle s34-koordinater for "net af lavere eller ukendt nøjagtighed". Det ville geodætisk give god mening, men kan vise sig at være et problem for den matrikulære side

**Comment by mrlarshole** [comment]
Fordelingen af artskode i REFGEO(s34j) svarer til fordelingen i UM(s34 generelt).   
Helles 25000 punkter i FIRE, afviger markant.

**Comment by Helle-Git** [comment]
ARTSKODE kan - midlertidigt - sættes til '**'Aner det ikke ??!!'**' ; 
MEN det er IKKE en af de tilladt værdier - så der skal findes en bedre løsning, inden det er færdigt.
(Jeg skal se hvordan en fornuftig værdi kan findes i FIRE, så den kan videregives til 'ny-UM')

**Comment by kbevers** [comment]
> MEN det er IKKE en af de tilladt værdier - så der skal findes en bedre løsning, inden det er færdigt.

Det er vi klar over, Helle. Som Thomas skrev ovenfor vil vi gerne have alle punkterne angivet som "net af lavere eller ukendt nøjagtighed" (måske med et par meget specifikke undtagelser), men det da potentielt skaber problemer for omverdenen kræver det nærmere undersøgelser. Du hører nærmere når vi har et klart svar.

**Comment by busstoptaktik** [comment]
Jeg har snakket med Søren, og vi blev enige om, i betragtning af at S34-koordinater alle er mindst 15 år gamle, at omdøbe alle til "punkter i net af lavere eller ukendt kvalitet".

Så både målemetode og artskode ligger nu fast for S34.

Derudover mener vi at transformerede koordinater og koter (indtil det modsatte er bevist) ikke længere skal udstilles.

**Comment by busstoptaktik** [comment]
> Derudover mener vi at transformerede koordinater og koter (indtil det modsatte er bevist) ikke længere skal udstilles.

Og det modsatte blev så bevist, jf. diskussion andetsteds

**Comment by busstoptaktik** [comment]
Lukker med konklusionen at S34 altid har målemetode terrestrisk, og artskode "net af lavere eller ukendt kvalitet"

**Comment by Helle-Git** [comment]
Transformerede koordinater er nu med igen.

For målemetode og artskode er fordelingen pt:

jf   issue#113 |   |   |  
-- | -- | -- | --
Maalemetode-grupperinger | 316493 | terrestrisk måling | blanding af terrestrisk måling med GPS eller fotogrammetrisk måling
Maalemetode-grupperinger | 2 | terrestrisk måling | barometrisk opmålt
Maalemetode-grupperinger | 3418 | terrestrisk måling | ukendt målemetode
Maalemetode-grupperinger | 4068 | terrestrisk måling | GPS opmålt
Maalemetode-grupperinger | 14221 | terrestrisk måling | fotogrammetrisk opmålt
Artskode-grupperinger | 16180 | punkter i net af lavere eller ukendt   kvalitet | punkter transformeret til gældende system
-- | -- | -- | --
Artskode-grupperinger | 67 | punkter i net af lavere eller ukendt kvalitet | fundamental punkt
Artskode-grupperinger | 418294 | punkter i net af lavere eller ukendt kvalitet | punkt i net af høj kvalitet
Artskode-grupperinger | 34273 | punkter i net af lavere eller ukendt kvalitet | overordnet planfikspunktsnet
Artskode-grupperinger | 19634 | punkter i net af lavere eller ukendt kvalitet | punkt i net af lav kvalitet bestemt ved få eller ingen overbestemmelse

**Comment by kbevers** [comment]
Så vidt jeg kan se var artskoden den store knast i dette issue. Den har vi taget hånd om på anden vis nu. Lukkes.
