### ISSUE TITLE
HOEJDEFIKSPUNKTFO.fikspunktsnummer

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#114]
Denne forsøges identificeres på samme måde som de øvrige.

Jeg får så fikspunktsnumre f.eks. a la 'FO  K-87-09035';  jeg forventer ikke at få 'FO ' med.

Er det noget jeg skal sortere fra - eller er det en uhensigtsmæssighed i udtræk til FIRE, som ændres?

**Comment by kbevers** [comment]
Ja, du må sortere FO fra. Grunden til at de er der, er at der ellers opstår kollisioner mellem numrene i Danmark, Grønland og Færøerne.

**Comment by Helle-Git** [comment]
Jeg mangler pt. data til at finde fikspunktsnummer for 179 punkter.

Muligvis fordi de har fået det 'nye' IDENT:stationsnr', skal det så bruges til/som fikspunktsnummer?

**Comment by kbevers** [comment]
Det ser ud til at stationsnumrene prioriteres højere end GNSS-identerne i Grønland og Færøerne, men ikke i Danmark. Så for de færøske og grønlandske punkter må det blive:

1. Landsnummer
2. Stationsnummer
3. GNSS
