### ISSUE TITLE
HOEJDEFIKSPUNKTFO.Artskode

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#115]
Hvordan skal denne findes?

**Comment by Helle-Git** [comment]
Med den algoritme der anvendes ifm danske højdefikspunkter, fås
alle (714) 'Punkt i net af høj kvalitet'

MENS de i UM fordeler sig med
713 'overordnet højdefikspunktsnet'
1 'fundamental punkt'

**Comment by kbevers** [comment]
Det er fint nok. Det betyder umiddelbart ikke det store.

**Comment by kbevers** [comment]
Hvis vi vil ramme helt rigtigt skal "FO  K-87-09037" sættes som fundamentalpunkt
