### ISSUE TITLE
HOEJDEFIKSPUNKTDNN.Artskode

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#117]
Hvordan findes artskode for disse?

(algoritmen for danske højdefikspunkter er vist ikke generelt gyldig)

**Comment by kbevers** [comment]
Samme tanke har strejfet mig - Jeg synes som udgangspunkt at det er fint

**Comment by Helle-Git** [comment]
Det er  hårdtkodet, så den altid sættes til 'punkter i net af lavere eller ukendt kvalitet'. (i denne tabel)
