### ISSUE TITLE
HOEJDEFIKSPUNKTGL.fikspunktsnummer

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#118]
Data hentes fra punktinfo -der søges i rækkefølge (blandt IDENT:*-identtyper):
Landsnr, station, GI, GNSS, jessen, ekstern, diverse.

Hvis det fundne fikspuntsnummer starter med 'GL  ' (2 blanke), skrælles disse 4 tegn væk.
(som tilsvarende for færøske, hvor der dog kun er eet blanktegn)

**Comment by kbevers** [comment]
Det lyder fornuftigt.

> (som tilsvarende for færøske, hvor der dog kun er eet blanktegn

Er du sikker på at det er rigtigt? Det skulle gerne være to blanke i alle tilfælde hvor en regionskode er foranstillet identen. Hvis ikke modtager jeg gerne et par eksempler.

**Comment by Helle-Git** [comment]
Beklager, der er også 2 blanke ifm de færøske.
Jeg skræller nu også de 4 tegn af for dem..
