### ISSUE TITLE
HOEJDEFIKSPUNKTFO.kote

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#119]
Hvordan findes værdien til denne?
Der findes ingen, hvis algoritmen for danske højde- og plan-fikspunkter benyttes; 
dvs: hvis der findes en DVR90-koordinat for punktet, benyttes z-koordinaten - ellers NULL.

**Comment by kbevers** [comment]
Mon ikke det isteder er FVR09 der skal bruges? Det er EPSG:5317.

**Comment by busstoptaktik** [comment]
Vi bør i hvert fald nok ikke udstille andre højdesystemer end FVR09.
