### ISSUE TITLE
HOEJDEFIKSPUNKTFO.maaleaar

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#121]
Denne bliver helt anderledes end i UM - hvordan skal den findes?

Nu fordeler de sig således:

ATTRIB | TEKST_I_FIRE | TEKST_I_FIKS | ANTAL
-- | -- | -- | --
Maaleaar | 2013 | 1800 | 513
Maaleaar | 2010 | 2009 | 178
Maaleaar | 2011 | 1800 | 12
Maaleaar | 2010 | 1800 | 3
Maaleaar | 2010 | 1968 | 2
Maaleaar | 2010 | 1990 | 2
Maaleaar | 2011 | 2009 | 1
Maaleaar | 2010 | 1989 | 1
Maaleaar | 2010 | 1967 | 1
Maaleaar | 2011 | 2008 | 1

**Comment by Helle-Git** [comment]
Der benyttes (pt) samme algoritme for alle fikspunkter, højde-/plan-/sys34 , danske/nordatlantiske.
MEN det er endnu ikke implementeret at der ses på ikke-transformerede koordinater hvis der ikke er en observation tilnyttet.
Det vil blive a la dette
select max(t.year) from koordinat where transformeret = false and sridid in (7, 8, 10,11,12,13)

**Comment by kbevers** [comment]
Okay, jeg mene at du kun skal medtage de SRID'er bruges til at udpegene punkterne i første omgang. Så på færøske højdefikspunkter er det EPSG:5317 (og evt også EPSG:5714 - kan ikke huske om den kom med eller ej).

**Comment by busstoptaktik** [comment]
Men det må være noget galt i fire: FVR09 kampagnen kørte i enten 2008 eller 2009. Så gik der selvfølgelig noget tid med processering, og derfor passer det fint med koordinater fra 2010-11, men det er jo ikke det samme som måleår. Men måske beregningsår alligevel i praksis er mere nyttigt...

**Comment by busstoptaktik** [comment]
OK - jeg vover et øje her og postulerer at FIRE ser mest ædruelig ud. Går derudover ud fra at en del af de øvrige diskrepanser forsvinder når der kun betragtes koteobservationer og FVR2009-koordinater
