### ISSUE TITLE
PLANFIKSPUNKTDK.ARTSKODE

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#122]
Hvordan findes denne?

Den bruges til at fastlægge værdien af KLASSE (og denne fejler p.gr.a. fejlagtige værdier for ARTSKODE (og/eller MVSTATUS))
Det er kombinationen: MVSTATUS:3, ARTSKODE:4, der forekommer
(ARTSKODE 4 = 'punkter i net af lavere eller ukendt kvalitet')

**Comment by busstoptaktik** [comment]
Betyder

> Det er kombinationen: MVSTATUS:3, ARTSKODE:4, der forekommer

at det er den eneste kombination, der forekommer. Eller betyder det at det er den kombination der giver problemer med fastlæggelsen af KLASSE?

**Comment by Helle-Git** [comment]
Denne kombination er ikke en gyldig til at finde værdi af KLASSE.
Det er ikke den eneste kombination der forekommer; men et eksempel på en der fejler.

**Comment by Helle-Git** [comment]
Da der ikke er en fornuftig algoritme pt, sættes ARTSKODE altid til ''Aner det ikke ??!!'' 
( som får værdi -1)

**Comment by kbevers** [comment]
Et bud på bestemmelse af artskode for danske planfikspunkter. Bemærk at ligesom ved de danske højdefikspunkter vil der være store forskelle mellem ny og gammel UM.

### Fundamental punkt

De definerende ETRS89 postamenter: BUDD, HVIG, MYGD, STAG, TYVH og VAEG. Skal findes som IDENT:GNSS.

```
SELECT * FROM punktinfo WHERE infotypeid=343 AND tekst IN ('BUDD', 'HVIG', 'MYGD', 'STAG', 'TYVH', 'VAEG');
```

### Overordnet planfikspunkt

Permanente GNSS-stationer, 5D-punkter, 10km-punkter og REFDK-punkter.

```
SELECT * FROM punktinfo WHERE infotypeid IN (350,352,353);
```

### Punkt i net af høj kvalitet

Tilsvarende fremgangsmåden for DVR90-koter. Plankoordinater hvorom der gælder, at de to følgende betingelser er opfyldt:

Nyeste observationer, der er indgået i beregningen af koordinaten, er højst 10 år gamle, samt
den estimerede spredning på koordinaten er højst 5 mm
Noget i stil med

```
SELECT *
FROM koordinat k
WHERE T > trunc(SYSDATE - interval '10' year,'YEAR') -- Ti år eller nyere
        AND sx <= 5; -- spredning højst 5 mm
```

**BEMÆRK**: Værdien på 5 mm er muligvis for lav, jf. 

```
SELECT count(sx), sx FROM koordinat k GROUP BY sx ORDER BY count(sx) DESC;

502159	35
400735	999
73529	20
27218	30
20749	40
19109	100
19047	10
17988	11
16857	15
16260	14
15926	9
15622	18
15053	13
14374	19
14324	17
13262	22
12957	16
12941	12
12433	23
12326	8
11734	21
11147	26
10949	25
10769	50
10664	33
10288	27
9994	7
9960	28
9445	31
8574	36
8461	24
8443	38
8198	6
8149	37
8024	34
7409	29
7146	5
6650	45
6431	39
6378	49
...
```


### punkter i net af lavere eller ukendt kvalitet

Øvrige plankoordinater, altså dem der endnu ikke er blevet fanget af de ovenstående kategorier OG som ikke har feltet ”Transformeret” krydset af.

### punkt i net af lav kvalitet bestemt ved få eller ingen overbestemmelse

Udgår.

### punkter transformeret til gældende system

Transformerede koordinater.

**Comment by busstoptaktik** [comment]
@kbevers kvad:

> BEMÆRK: Værdien på 5 mm er muligvis for lav, jf. ...

@Helle-Git hvor er vi i praksis endt? Da vi har 10km-nettet og dets venner liggende i niveauet over kan vi sikkert tillade os at trække spredningen til 10 mm om nødvendigt, men jeg kan ikke finde en oversigt over fordelingen af artskoder for PFPDK.
