### ISSUE TITLE
HOEJDEFIKSPUNKTGL.ARTSKODE

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#123]
Da der ikke er en fornuftig algoritme pt, sættes ARTSKODE altid til ''Aner det ikke ??!!''
( som får værdi -1).

Dette er IKKE en gyldig værdi i henhold til DDL; men bruges indtil en bedre er angivet.

**Comment by kbevers** [comment]
Sæt den til "... net af lav eller ukendt kvalitet".

**Comment by kbevers** [comment]
Jeg lukker denne, da mapningen beskrevet ovenfor er simpel og lige til. Alle punkter har i dag enten lav eller ukendt kvalitet. Vi kommer ikke til at registrere nye højdefikspunkter, så det er fint nok at hårdkode værdien.
