### ISSUE TITLE
PLANFIKSPUNKTDK.FIKSPUNKTSNUMMER

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#124]
Skal fikspunkter findes og behandles på samme måde som for højdefikspunkter?

Der er 1.november 3535 planfikspunkt-kandidater, hvor der er problemer med at finde herredsnr etc.
De fordeler sig med
 1 med IDENT:GNSS  (fikspunktsnr er KTSX)
501 har IDENT:ekstern
3033 har IDENT:diverse  

Eksempler: 
med IDENT:diverse, lokalid, fikspunktsnummer
605235	 8390.441 
605249	 8405.441 
605270	 8426.441 

med IDENT:ekstern
757793	 4078/999.0203 
766281  4500/670017
757792  4078/999.0202 
**853371	 8025/18-6028**
**853381	 8025/103-6010** 

 853371 og 853381 (og andre af de 500 andre eksterne) skal frasorteres, da det er produktionsnumre; men de øvrige??

**Comment by Helle-Git** [comment]
Det ene punkt med IDENT:GNSS, har lokalid 861306;, og punktid 95582750-6AA1-3280-E053-1A041EAC5624
punktinformationerne for dette er

KTSX		343	IDENT:GNSS	GNNS Stationsnummer
72-01-00159.1		349	IDENT:diverse	Identtyper der forekommer sporadisk

Mon ikke IDENT:diverse skulle have været IDENT:landsnr?

I UM har dette punkt fikspunktsnummer svarende til IDENT:diverse

**Comment by busstoptaktik** [comment]
> Mon ikke IDENT:diverse skulle have været IDENT:landsnr?

Det lyder plausibelt - og så har ".1" i "72-01-00159.1" måske sendt den fra landsnummer til diverse @kbevers? Lad os lige se om den rystes på plads ved næste migrering

**Comment by kbevers** [comment]
Ja, der har været lidt bøvl med at tolke identer der ender på .xxxx korrekt. Jeg tror de værste problemer er løst nu, men der skal nok dukke flere op. Jeg tager dem som de bliver opdaget.

**Comment by kbevers** [comment]
Jeg tillader mig at lukke denne da vi konvergerer mod orden i registreringen af identer. De få der er fejl i dukker op sporadisk og tages hånd om løbende.
