### ISSUE TITLE
Udvid SRIDTYPE tabel så den tilsvarer OBSERVATIONTYPE-tabellen

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#125]
OBSERVATIONTYPE-tabellen holder for hver type observation styr på hvilke værdier hver enkelt type indeholder. Denne information bruges blandt andet til at sætte constraints på observationstabellen, så det sikres at hver observation har udfyld de nødvendige felter.

Et tilsvarende koncept er nødvendigt for koordinater og koordinatsystemer. Hver koordinat *kan* have værdier i både `x`, `y` og `z` felterne i tabellen, samt de tilsvarende spredningsværdier 'sx', 'sy', 'sz'. Tabellen SRIDTYPE skal i DDL'en ændres sådan at det registreres hvilke koordinat-værdier der er påkrævede for det enkelte koordinatsystem. Fx EPSG:5733/DVR90-koter hvor det kun er `z` og `sz` der skal sættes eller System34 hvor kun de plane koordinater `x` og `y` er relevante.

Der skal tilføjes en constraint på koordinattabllen der checker at de korrekte værdier er sat ved indsættelse. Denne constraint tilsvarer den der er sat på observationstabellen: https://github.com/Kortforsyningen/FIRE-DDL/blob/740ded567750b16cd69ccc34d4a8f6a29b1de883/DDL.sql#L809-L912

**Comment by busstoptaktik** [comment]
@PeterWestNielsen du nævnte på et tidspunkt at du og Steen havde en håndfuld constraints som endnu ikke var committet. Kan det tænkes at der allerede er gang i noget i den retning som @kbevers efterlyser?

**Comment by kbevers** [comment]
Løst pr ed162218901a7f23c9f3c25b9323a06e1e563be0
