### ISSUE TITLE
HOEJDEFIKSPUNKTFO.GEOMETRI

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#126]
Hvilken overensstemmelse skal der være mellem GEOMETRI i FIRE og UM?

Når jeg sammenligner - er der forskelle på 690 ud af 714.
Sammenligner med:
 dbms_lob.compare(HF.geometri.get_wkt(), nf.geometri.get_wkt() )!= 0

Jeg har også set på forskellen mellem hypot(x , y fra geometrien) fra hhv. FIRE og UM  (uden at være sikker på at det er en fornuftig sammenligning..); men hvilken afvigelse er acceptabel? - eller hvordan kan de sammenlignes?

**Comment by busstoptaktik** [comment]
I FIRE er geometrien i grader - jeg ved ikke om den er i meter (UTM) i udstillingsmodellen. Men under antagelse af at begge er i grader (hvis de er i radianer: gang først med 180/pi):

For at få en cirkaforskel i meter:

Gang breddegradsforskellen med 111000
Gang længdegradsforskellen med 55000

tag hypot af de to tal.

Eksempel:

    // Længdegradsforskel
    dL = (12.0000001 - 12.0000002)*55000;

    // Breddegradsforskel
    dB = (55.0000008 - 55.0000009)*111000;

    // Grovafstand
    ds = hypot (dL, dB);

En forskel på to meter er helt OK, en forskel på fem meter er småkriminel, og en forskel på 100 m er i hegnet. Hvis alt holder sig under to meter er alt fint, og der er ingen grund til at undersøge videre.

**Comment by busstoptaktik** [comment]
NB: I det nordlige grønland er 55000 i overkanten (20000 er bedre), men der er som sagt tale om en grov overslagsberegning, så hvis nordgrønlandske punkter skejer lidt mere ud er der ingen grund til bekymring (fem meter er fint der oppe)

**Comment by Helle-Git** [comment]
I dit eksempel er hypot-værdien 0.0123878973195615, så det er helt fint (ca 1 cm) - bare for at være sikker. ?!

**Comment by busstoptaktik** [comment]
Ja - det er korrekt

**Comment by kbevers** [comment]
Jeg vover pelsen og påstår at denne er på plads
