### ISSUE TITLE
PLANFIKSPUNKTFO Overordnet

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#127]
Denne tabel har disse felter -
AFMAERKNINGSBESKRIVELSE
ARTSKODE
EASTING
ELLIPSOIDEHOEJDE
FIKSPUNKTSBESKRIVELSE
FIKSPUNKTSNUMMER
FO10KMNET
GEOMETRI
GPSEGNET
HERREDSOGN_HERREDSNUMMER
HERREDSOGN_KOEBSTADNUMMER
HERREDSOGN_SOGNENUMMER
KOTE
KOTEREFERENCEVERSION
LOEBENUMMER
MIDDELFEJL
MVSTATUS
MAALEMETODE
MAALSKITSE
NORTHING
TEKSTBESKRIVELSE

ID_LOKALID

FORRETNINGSHAENDELSE
FORRETNINGSOMRAADE
FORRETNINGSPROCES
GMLID
ID_NAMESPACE
REGISTRERINGFRA
REGISTRERINGSAKTOER
REGISTRERINGTIL
STATUS
OBJECTID
VIRKNINGFRA
VIRKNINGSAKTOER
VIRKNINGTIL

**Comment by Helle-Git** [comment]
Hvordan findes de punkter, de skal udtrækkes?

**Comment by busstoptaktik** [comment]
2	EPSG:4258	Geografiske koordinater 2D: ETRS89
    3	EPSG:4937	Geografiske koordinater 3D: ETRS89
    4	EPSG:4936	Geocentrisk kartesiske koordinater 3D: ETRS89

For breddegrad > 58. Eller region=FO.

@kbevers kan det tænkes at der også er FOTM-koordinater i spil?

**Comment by Helle-Git** [comment]
Fordelingen pt. af aktuelt gældende koordinater for punkter med 
- Region-Færøerne 
- geometriobjekt

er

ANTAL | SRIDID | TRANSFORMERET
-- | -- | --
229 | 2 | FALSK
533 | 3 | FALSK
464 | 7 | FALSK
714 | 25 | FALSK

Det er uvist om der er punkter med flere gyldige koordinatsæt (forskellige srid).

Der er 762 aktuelt gældende færøske planfikspunkter i UM.

**Comment by kbevers** [comment]
> @kbevers kan det tænkes at der også er FOTM-koordinater i spil?

Nej, sådan nogle mener jeg ikke vi har. Hverken i FIRE eller REFGEO.

**Comment by busstoptaktik** [comment]
SRIDID 7 og 25 er kotesystemer, så de skal ikke med i planfikspunkttabellen

**Comment by busstoptaktik** [comment]
Jeg indkaster lige lidt til artskodebestemmelse, fra den afsluttende rapport om ETRS89/FVR09 projektet:

"Fundamentalstationer"

Station | Number | X | Y | Z
-- | -- | -- | -- | --
ARGI | 37161 | 2 981 490.0722 m | -354 651.8089 m | 5 608 474.7852 m
KLAK | 84806 | 2 960 778.0871 m | -342 299.7933 m | 5 620 225.3598 m
SORV | 30012 | 2 971 445.1815 m | -379 959.4077 m | 5 612 155.7989 m
TORH | 55822 | 2 980 573.6424 m | -353 744.5006 m | 5 608 956.9021 m
TVOR | 17811 | 3 026 017.3727 m | -360 952.0512 m | 5 584 332.1751 m

GNSSmålt i 2008/09:

    KLAK, TORH, SORV, TVOR,
    VID1, EIDI, NOR1, SAN1, TOR1, ARG1
    AIPO, ARG3,
    ARGI (permanent):

Lidt snak om hvordan man bestemte nye koordinater til gamle punkter:

> The 5 basic GPS stations (chapter 3) have fixed 3D coordinates.
>
> Totally 761 stations had UTM zone 29 ETRS89 coordinates determined by adjustment of observations. 528 stations had the ellipsoidal height determined by adjustment of observations using GPS vectors and zenith distances with inclusion of deflections of the vertical determined from the preliminary geoid and the final fogeoid12.02. Some local polygon line networks observed by US are included to improve the accuracy at the border of the network.
>
>Only the result from the final adjustment is shown in the following.
>
> 4.4.1 Final adjustment results
> The determination of the UTM coordinates and the ellipsoidal height is done in a combined adjustment fixing the five basic stations and using the GPS vectors, rounds of direction observations, distance observations, zenith distances and few height observations.
>
> The scale of older distance observations may deviate from the scale defined in the International Terrestrial Reference System (ITRS). The adjustment system was improved to support the determination of a scale correction for one or more groups of distance or GPS-vector observations. When the scale correction was applied the a posteriori mean errors decreased: Distances about 50% and older GPS-vectors 25%.

**Appendix** A. GPS stations**

Station location | Name | Number | Status | Remarks
-- | -- | -- | -- | --
Tórshavn | ARGI | 37161 | EPN   station | Reference   station, levelling station
Klaksvík | KLAK | 84806 | EUREF   station | Reference   station, levelling station
Sørvágur | SORV | 30012 | EUREF   station | Reference   station, levelling station
Tórshavn | TORH | 55822 | EUREF   station | Reference   station, levelling station
Tvøroyri/Øravík | TVOR | 17811 | EUREF   station | Reference   station
Dalur | DALU | 24029 | 10 km station |  
Eiði | EID1 | 60908 | 10 km station | Levelling   station
Fuglafjørður | FGL1 | 66041 | 10 km station |  
Gásadalur | GASA | 32024 | 10 km station |  
Gjógv | GJOG | 61034 | 10 km station |  
Gamlarætt | GLR1 | 37088 | 10 km station |  
Hattarvík | HATT | 95019 | 10 km station |  
Hvalba | HVAL | 20815 | 10 km station |  
Hvítanes | HVIT | 54285 | 10 km station | Levelling   station
Kollafjørður | KOLL | 51807 | 10 km station | Levelling   station
Kunoy | KUNO | 80023 | 10 km station |  
Langasandur | LANG | 48803 | 10 km station |  
Leirvík | LEIR | 67813 | 10 km station | Levelling   station
Mymines | MYK1 | 33014 | 10 km station |  
Mykines | MYK2 | 33024 | 10 km station |  
Norðdepil | NORD | 88022 | 10 km station |  
Raktangi | RAKT | 56002 | 10 km station |  
Saksun | SAKS | 45040 | 10 km station |  
Sandur | SAND | 27816 | 10 km station |  
Sandavágur | SDVA | 28727 | 10 km station |  
Skopun | SKOP | 27185 | 10 km station |  
Skálavik | SKVK | 26347 | 10 km station |  
Stykkið | STYK | 43297 | 10 km station |  
Sumba | SUMB | 11499 | 10 km station |  
Svínoy | SVIN | 93076 | 10 km station |  
Vágur | VAGR | 12808 | 10 km station |  
Vestmanna/Válur | VEST | 43325 | 10 km station |  
Viðareiði | VID1 | 92815 | 10 km station |  
Airport | AIPO | 30803 | Additional   station |  
Eiði | EIÐI | 60122 | Additional   station | Close   to tide gauge
Fuglafjørður | FGL2 | 66908 | Additional   station | Close   to tide gauge
Gamlarætt | GLR2 | 37904 | Additional   station | Close   to tide gauge
Norðskáli | NOR1 | 58808 | Additional   station | Close   to tide gauge
Sandur | SAN1 | 27018 | Additional   station | Close   to tide gauge
Skipanes | SKIP | 71058 | Additional   station | Close   to tide gauge
Tórshavn | TOR1 | 55819 | Additional   station | Close   to tide gauge
Tórshavn | ARG1 | 37162 | Auxiliary   station | Close   to ARGI, Levelling station
Tórshavn | ARG3 | 37164 | Auxiliary   station | Close   to ARGI, Levelling station
Tórshavn | ARG4 | 37165 | Auxiliary   station | Close   to ARGI, Levelling station

Table 15: Stations observed with GPS in 2008, 2009 and 2010.

**Comment by busstoptaktik** [comment]
Lukker denne - fortsæt diskussion ovre i #137
