### ISSUE TITLE
PLANFIKSPUNKTGL overordnet

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#128]
Der er følgende attributter:

AFMAERKNINGSBESKRIVELSE
ARTSKODE
EASTING
ELLIPSOIDEHOEJDE
FIKSPUNKTSBESKRIVELSE
FIKSPUNKTSNUMMER
GEOMETRI
GPSEGNET
KOTE
KOTEREFERENCEVERSION
MIDDELFEJL
MVSTATUS
MAALEMETODE
MAALSKITSE
NORTHING
REFGR
TEKSTBESKRIVELSE

ID_LOKALID

FORRETNINGSHAENDELSE
FORRETNINGSOMRAADE
FORRETNINGSPROCES
GMLID
ID_NAMESPACE
REGISTRERINGFRA
REGISTRERINGSAKTOER
REGISTRERINGTIL
STATUS
OBJECTID
VIRKNINGFRA
VIRKNINGSAKTOER
VIRKNINGTIL

**Comment by Helle-Git** [comment]
Hvad karakteriserer de grønlandske planfikspunkter? 
Hvilke kriterier skal benyttes for at udtrække dem?

**Comment by busstoptaktik** [comment]
26	EPSG:4747	Geografiske koordinater 2D: GR96
    27	EPSG:4909	Geografiske koordinater 3D: GR96
    28	GL:NAD83G	Geografiske koordinater 2D: NAD83G (DEPRECATED)

**Comment by busstoptaktik** [comment]
... og måske

    1	EPSG:4326	Geografiske koordinater 2D: WGS84

for (breddegrad > 62) eller (breddegrad > 59 og længdegrad < -15)

**Comment by kbevers** [comment]
Det vil undre mig meget hvis der er er WGS84-koordinater i UM

**Comment by Helle-Git** [comment]
Der er 9680 forskellige aktuelle grønlandske planfikspunkter i UM.

Når jeg søger i FIRE, finder jeg væsentlig flere.
Jeg søger på aktuelle data for punkter med
- sridid 1, 26, 27, 28
- region Grønland
- der er (mindst) et geometriobjekt tilknyttet punktet

Fordelt på koordinat-oplysninger får jeg denne fordeling:

ANTAL | SRIDID | TRANSFORMERET
-- | -- | --
30859 | 26 | FALSK
147 | 26 | SAND
139 | 27 | FALSK
11 | 27 | SAND

**Comment by busstoptaktik** [comment]
> Det vil undre mig meget hvis der er er WGS84-koordinater i UM

Det er der så heller ikke, men tanken var at koordinater fra før 1996 kunne være registreret som (i mangel af bedre) WGS84 i REFGEO

**Comment by busstoptaktik** [comment]
> Der er 9680 forskellige aktuelle grønlandske planfikspunkter i UM

Hvis jeg skal begynde at gætte er der nok en del af de ca. 20000 overskydende der er  fotogrammetrisk registrerede naturlige fikspunkter, anvendt ifbm aerotriangulering og orthoopretning.

**Comment by Helle-Git** [comment]
Punkter registreret i region Grønland, fordeler sig på sridid 7, 26 og 27.

De fordeler sig på infotyper således (AFM:<nummer>  og AFM:Højde.. er frasorteret)


ANTAL | INFOTYPEID | INFOTYPE
-- | -- | --
6 | 1 | AFM:diverse
667 | 2 | AFM:horisontal
3221 | 3 | AFM:vertikal
233 | 4 | AFM:horisontalvertikal
3931 | 5 | AFM:naturlig
109 | 330 | ATTR:tabtgået
7 | 332 | ATTR:vandstandsmåler
354 | 333 | ATTR:gnss_egnet
9193 | 334 | ATTR:beskrivelse
9829 | 335 | ATTR:højdefikspunkt
261 | 343 | IDENT:GNSS
38123 | 344 | IDENT:refgeo_id
12403 | 347 | IDENT:station
25825 | 349 | IDENT:diverse
1 | 356 | NET:jessen
278 | 361 | NET:REFGR
38123 | 368 | REGION:GL
571 | 369 | SKITSE:sti
571 | 370 | SKITSE:md5

**Comment by kbevers** [comment]
Jeg har bladret godt og grundigt rundt i både FIRE og UM, og er kommet frem til den konklusion at søgekriterierne må være

1. REGION:GL
2. SRIDID=26 (EPSG:4747)
2. IDENT:station

Med nedenstående SQL får jeg 9071 hits. Det er det tætteste jeg kan komme det. Det skal dog bemærkes at jeg op til nu kun har tilladt IDENT:station på formen `xxxxxx` eller `xxxxx.yyyy`. Det har jeg i a7420f0 nu ændret til også at tillade færre tal efter punktummet, da det ser ud til at mange punkter med stationsnummer kun har et enkelt tal efter punktummet. Jeg satser på at vi kommer tættere på de ~9600 punkter efter næste migration.

```
SELECT count(*) FROM koordinat k
JOIN punktinfo pi ON k.punktid=pi.punktid
JOIN punktinfotype pit on pi.infotypeid=pit.infotypeid
WHERE 1=1
  AND k.sridid in (26)
  AND k.registreringtil IS NULL
  AND pit.infotype='IDENT:station';
```

**Comment by busstoptaktik** [comment]
Men 9600 punkter henne i Grønland undrer mig nu alllllllligevel lidt. @majbrittws er der noget her der lyder psært?

**Comment by busstoptaktik** [comment]
> Jeg satser på at vi kommer tættere på de ~9600 punkter efter næste migration.

@kbevers  lukker du dette issue hvis det er tilfældet? Vi kan fortsætte den overordnede diskussion ovre på #138

**Comment by kbevers** [comment]
> Jeg satser på at vi kommer tættere på de ~9600 punkter efter næste migration.

Jeg rammer nu 9610. Det må være godt nok.

**Comment by Helle-Git** [comment]
Der er 150 punkter i UM, som ikke udtrækkes fra FIRE.

De har (alle?) srid EPSG:4909 og udtrækkes derfor ikke..
For at<få dem med, udvides til at EPSG:4909 OGSÅ tages med

**Comment by busstoptaktik** [comment]
Vi lider så stadig under at udstillingsmodellen i bund og grund er todimensionel, og udstyret til at udstille max 2 plane dimensioner + evt. en kote (ikke en højde), så vi må bruge en "a la Færø" model, hvor koten hentes hvor man nu kan få den:

Hvis der er en GVR2016/EPSG:8267 så benyt Z fra den, ellers, hvis der er en MSL/EPSG:5714 benyt Z for den. Ellers har punktet bare ikke nogen kote.

**Comment by busstoptaktik** [comment]
... og ser nu ovre på #170 at der naturligvis også er ellipsoidehøjder i spil, så de skal bruges når de er der - de skal bare ikke registreres som koter.

**Comment by Helle-Git** [comment]
> Hvis der er en GVR2016/EPSG:8267 så benyt Z fra den, ellers, hvis der er en MSL/EPSG:5714 benyt Z for den. Ellers har punktet bare ikke nogen kote.
> 
Jeg kan godt implementere dette; men det vil ikke have nogen effekt pr; da der ikke er koordinater i FIRE med GVR2016/EPSG:8267.

**Comment by busstoptaktik** [comment]
Ja - jeg ved godt at der ikke p.t. er nogen, men det kommer der jo (formodentlig) på et tidspunkt, så det er mest skrevet som en reminder ifbm. historikunderstøttelsen.
