### ISSUE TITLE
HOEJDEFIKSPUNKTDK.GEOMETRI

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#129]
Der er 10 punkter hvor afvigelserne er ret store (hypot-værdi større end 2).

Afvigelser fundet som beskrevet i issue #126 

Det er disse 10 punkter, med disse værdier (hyp er hypot-værdien, som jo er temmelig meget større end 2..)

Der er udtrukket ca. 70000 punkter - der er ca. 50% flere i UM; så der kan 'gemme' sig flere med dette problem.

HYP | GEOMETRI.SDO_SRID | GEOMETRI.SDO_GTYPE | ID_LOKALID | FIKSPUNKTSNUMMER
-- | -- | -- | -- | --
300,831284 | 4326 | 2001 | 847358 | 102-03-09185
80,36694866 | 4326 | 2001 | 847336 | 95-08-09083
69,17818119 | 4326 | 2001 | 46410 | K-63-09225
28,86369541 | 4326 | 2001 | 46404 | K-63-09219
22,76190558 | 4326 | 2001 | 46224 | K-63-09029
21,84830697 | 4326 | 2001 | 46564 | K-63-09392
21,02629025 | 4326 | 2001 | 405972 | 102-09-09026
18,36210474 | 4326 | 2001 | 401195 | 101-02-09026
14,606584 | 4326 | 2001 | 46505 | K-63-09331
4,269307197 | 4326 | 2001 | 402370 | 101-07-09041

**Comment by kbevers** [comment]
Der er simpelthen kommet nyt data i REFGEO, og dermed geobank/UM, siden vi sidst har lavet en overførsel fra REFGEO til FIRE. Alle punkterne du har fundet har registreringfra sat til 31/10-2019. Vi skal lave en ny migration for at komme problemet til livs. Jeg vil foreslå at det sker i weekenden.

Der skulle i øvrigt på nuværende tidspunkt være blevet lavet ændringer på 13 punkter, så flot at du har fanget størstedelen af dem :-)

**Comment by busstoptaktik** [comment]
Men hvorfor filan giver det ændringer på placeringskoordinaterne at man opdaterer koterne?

**Comment by kbevers** [comment]
> Men hvorfor filan giver det ændringer på placeringskoordinaterne at man opdaterer koterne?

Det gør det heller ikke. De har lavet punktrevision i Åårhus, og har derfor flyttet placeringskoordinaten for punkter hvor den ikke var retvisende.
