### ISSUE TITLE
DATA SQL rækkefølge

### ISSUE THREAD

**Issue by AsgerPetersen** [Kortforsyningen/FIRE-DDL#13]
Af hensyn til automatisk indlæsning (og sådan set også manuel indlæsning) ville det være nyttigt med en rækkefølge på SQL scripts. Det kunne være et præfix med `01_xxx`, `02_xxx` etc

**Comment by kbevers** [comment]
Det er vel også fint nok hvis bare rækkefølgen er kendt og dokumenteret i en README?

Umiddelbart vil jeg gætte på at rækkefølgen er som følger:

0. Sags-tabeller (tilføjes på nuværende tidspunkt via DDL, så skal ikke indlæses separat)
1. `FIRE_ADM.PUNKTINFOTYPENAMESPACE.sql`
2. `FIRE_ADM.OBSERVATIONTYPENAMESPACE.sql`
3. `FIRE_ADM.SRIDNAMESPACE.sql`
4. `FIRE_ADM.PUNKTINFOTYPE.sql`
5. `FIRE_ADM.OBSERVATIONTYPE.sql` (tilføjes vist også via DDL, så nok ikke nødvendig)
6. `FIRE_ADM.PUNKT.sql`
7. `FIRE_ADM.PUNKTINFO.sql`
8. `FIRE_ADM.KOORDINAT.sql`
9. `FIRE_ADM.GEOMETRIOBJEKT.sql`
10. `FIRE_ADM.OBSERVATION.sql` (når den ellers bliver tilføjet)

Er det helt i skoven @nikolajkamstrup ?

**Comment by AsgerPetersen** [comment]
Hvis de sorterede i den rette rækkefølge, kunne vi bare afvikle dem sådan. Ellers skal vi jo hardkode filnavnene.

**Comment by kbevers** [comment]
Sandt, men omvendt så synes jeg også det er noget bøvl hvis filnavnene skal skifte fordi der indføres en ny tabel eller lign. Fx hvis vi nummerede filerne som ovenfor ville det sandsynligvis blive nødvendigt at ændre på dem alle sammen så snart der bliver fyldt rigtigt data i sags-tabellerne. Det ville være relativt let at fikse i en hardkodet liste over filer til indlæsning.

**Comment by nikolajkamstrup** [comment]
Rækkefølgen er helt korrekt, Kristian. Jeg indsætter en korrekt sorteret liste i readme.
