### ISSUE TITLE
Status på mapping til PLANFIKSPUNKTDK

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#132]
# PLANFIKSPUNKTDK

Generelt - bl.a. om hvordan punkterne identificeres (#96)
## Felter der ikke findes i HOEJDEFIKSPUNKTDK

- [x] DK10KMNET (#85)
- [x] ELLIPSOIDEHOEJDE (#86)
- [x] GPSEGNET (#87)
- [x] KLASSE (#88)
- [x] REFDK (#89)

## Sidetabeller

- [x] PLANFIKSPUNKTDK_FOTO
- [x] PLANFIKSPUNKTDK_PLANDESC
- [x] PLANFIKSPUNKTDK_PUNKTDESC
- [x] PLANFIKSPUNKTDK_SPECIALNR

### Faglige felter

- [x] REGISTRERINGFRA (#61)
- [x] REGISTRERINGTIL (#62)
- [x] STATUS
- [x] FIKSPUNKTSNUMMER (#124 )
- [x] KOTE (#101)
- [x] KOTEREFERENCEVERSION (#64)
- [x] MAALEMETODE (#65)
- [x] FIKSPUNKTSBESKRIVELSE (#67)
- [x] ARTSKODE (#122)
- [x] MVSTATUS (#69)
- [x] MIDDELFEJL (#100 0)
- [x] AFMAERKNINGSBESKRIVELSE (#71)
- [x] TEKSTBESKRIVELSE (#72)
- [ ] MAALSKITSE (#73)
- [x] HERREDSOGN_HERREDSNUMMER (#74)
- [x] HERREDSOGN_KOEBSTADNUMMER (#75)
- [x] HERREDSOGN_SOGNENUMMER (#76)
- [x] LOEBENUMMER (#77)
- [x] NORTHING (#146 )
- [x] EASTING (#146 )

### Administrative felter

- [x] DATO_OPRETTET (#83)
- [x] DATO_NEDLAGT
- [x] GMLID (#82)
- [x] ID_NAMESPACE
- [x] ID_LOKALID
- [x] FORRETNINGSPROCES
- [x] FORRETNINGSHAENDELSE
- [x] REGISTRERINGSAKTOER
- [x] FORRETNINGSOMRAADE
- [x] KOMMUNEKODE (#81)
- [x] OBJECTID
- [x] VIRKNINGFRA (#59)
- [x] VIRKNINGTIL (#60)
- [x] VIRKNINGSAKTOER

**Comment by busstoptaktik** [comment]
Kotereferenceversion er ikke relevant her

**Comment by busstoptaktik** [comment]
@Helle-Git kan du checke fordelingen af "kotereferenceversion" og "koteklasse" i planfikspunktdk-tabellen? ingen af dem burde være relevante, så det vil være interessant at se hvad man har forsøgt at kommunikere ad den vej.

**Comment by kbevers** [comment]
```
SELECT count(kotereferenceversion), kotereferenceversion FROM fikspunkt_l1.planfikspunktdk GROUP BY kotereferenceversion ORDER BY count(kotereferenceversion) DESC;
-------------
493397	ingen
16395	DVR90
```

"koteklasse" er ikke en kolonne i planfikspunktdk-tabellen. "klasse" findes, med følgende fordeling:

```
SELECT count(klasse), klasse FROM fikspunkt_l1.planfikspunktdk GROUP BY klasse ORDER BY count(klasse) DESC;
------
373742	2
126089	3
2214	0
1852	1
0	(null)
```
men den type klasse omhandler vist godt nok planfikspunkterne og ikke koter.

**Comment by busstoptaktik** [comment]
Så kotereferenceversion er DVR90 når der er en kote

**Comment by kbevers** [comment]
> Så kotereferenceversion er DVR90 når der er en kote og NULL når kote enten er NULL eller er en ETRS89-højde?

kotereferenceversion er DVR90 når kote ikke er NULL. Ellipsoidehøjder placeres ikke i kote-feltet (den har sin egen kolonne).

**Comment by busstoptaktik** [comment]
> Ellipsoidehøjder placeres ikke i kote-feltet (den har sin egen kolonne).

Jep - der skulle have stået "transformerede ETRS89-højder" (det var mere for at finde ud af om der rent faktisk var kigget på om der stod noget i tilfælde hvor vi ikke har en DVR90-kote i FIRE)

**Comment by busstoptaktik** [comment]
> "klasse" findes, med følgende fordeling (...)

Og klasse er vores gennemgående smertensbarn: Vi mangler mapping i alle tabeller. Nogen idéer, @Helle-Git og @kbevers?

**Comment by kbevers** [comment]
Jeg er i tvivl om hvad klasse dækker over. Hvad dokumentationen af UM om feltet?

**Comment by busstoptaktik** [comment]
... og jeg er vist bare fejlklassificeret :-) ... distræt er alt for vagt et ord når jeg kan glemme at jeg for tre dage siden sammenfattede definitionen ovre i #88. Men da @mrlarshole, på min anmodning for tredje gang fremsendte koden til udregning af klasse-klassen kom jeg i tanke om det.

Jeg markerer "klasse" som afsluttet i alle planfikspunkttabeller.

Hvad koteklasse, i kotetabellerne, angår er Lars' vurdering at den i bedste fald er ubrugelig, så den skal måske hverken migreres eller mappes
