### ISSUE TITLE
Status på mapping til SYSTEM34FIKSPUNKT

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#133]
Hovedtabel
-------------

- [x] AFMAERKNINGSBESKRIVELSE
- [x] ARTSKODE
- [x] FIKSPUNKTSBESKRIVELSE
- [x] FIKSPUNKTSNUMMER
- [x] FORRETNINGSHAENDELSE
- [x] FORRETNINGSOMRAADE
- [x] FORRETNINGSPROCES
- [x] GEOMETRI
- [x] GMLID
- [x] HERREDSOGN_HERREDSNUMMER
- [x] HERREDSOGN_KOEBSTADNUMMER
- [x] HERREDSOGN_SOGNENUMMER
- [x] ID_LOKALID
- [x] ID_NAMESPACE
- [x] KOMMUNEKODE
- [x] LOEBENUMMER
- [x] MAALEMETODE
- [ ] MAALSKITSE
- [x] MIDDELFEJL
- [x] MVSTATUS
- [x] OBJECTID
- [x] REGISTRERINGFRA
- [x] REGISTRERINGSAKTOER
- [x] REGISTRERINGTIL
- [x] STATUS
- [x] SYSTEM34VERSION
- [x] TEKSTBESKRIVELSE
- [x] VIRKNINGFRA
- [x] VIRKNINGSAKTOER
- [x] VIRKNINGTIL
- [x] X
- [x] Y

Sidetabeller
-------------

* FIKSPUNKSYS34_PLANDESC
    - [x] FIKSPUNKSYS34OBJECTID
    - [x] PLANDESC (#162)
* SYSTEM34FIKSPUNKTFO_PUNKTDESC
    - [x] FIKSPUNKSYS34OBJECTID
    - [x] PUNKTDESC
* SYSTEM34IKSPUNKTFO_SPECIALNUMMEROBJECTID
    - [x] FIKSPUNKSYS34OBJECTID
    - [x] SPECIALNUMMEROBJECTID

**Comment by busstoptaktik** [comment]
@Helle-Git er der, i udstillingsmodellen p.t., nogen variation i "SYSTEM34VERSION"? Hvis ikke er dette element også afklaret.

**Comment by kbevers** [comment]
Der er tre udfald:

```
SELECT unique(system34version) FROM fikspunkt_l1.fikspunktsys34;
-------
System34Sjælland
System45Bornholm
System34Jylland
```

Burde være trivielt at holde styr på, da der er et 1-1 forhold med SRID'en i FIRE.KOORDINAT

**Comment by busstoptaktik** [comment]
@Helle-Git - jvf. @kbevers opgørelse ovenfor hakker jeg "SYSTEM34VERSION" af ovenfor, og anfører en mental note om at "SYSTEM34ZONE" er et mere oplagt navn når vi en gang skal til at revidere udstillingsmodellen :-)

SYSTEM34VERSION

    System34Jylland  = sridid 21 DK:S34J	
    System34Sjælland = sridid 22 DK:S34S
    System45Bornholm = sridid 23 DK:S45B

**Comment by busstoptaktik** [comment]
@Helle-Git, @kbevers med lukning af #104 ser det ud som om at transformerede punkter skal med i S34-UM.

**Comment by busstoptaktik** [comment]
Med seneste opdateringer i bl.a. #106, #107 og #108 er denne vist på plads, bortset fra målskitseproblemet (som formodentlig løses ved at kopiere ægs-antal tusind filer til et bibliotek på F:\GDB)

**Comment by Helle-Git** [comment]
Hvad med sidetabellerne ??, er det også OK at der er ca 1700 flere punkter med fremover?

**Comment by busstoptaktik** [comment]
> er det også OK at der er ca 1700 flere punkter med fremover?

De ser jo ikke ud til at være restrictede og vi kan ikke se nogen god grund til at de ikke skulle med, så de må jo bare komme med så.

Er det forkert at sidetabellerne er hakket af som afsluttet? Jeg spørger dumt fordi jeg ikke kan holde overblikket oppe her sidst på ugen...
