### ISSUE TITLE
Status på mapping til HOEJDEFIKSPUNKTFO

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#135]
Hovedtabel
-------------

- [x] AFMAERKNINGSBESKRIVELSE
- [ ] ARTSKODE  (jf #115)
- [x] EASTING  (jf #116)
- [x] FIKSPUNKTSBESKRIVELSE
- [x] FIKSPUNKTSNUMMER jf (#114)
- [x] FORRETNINGSHAENDELSE
- [x] FORRETNINGSOMRAADE
- [x] FORRETNINGSPROCES
- [x] GEOMETRI  (jf #126)
- [x] GMLID
- [x] HERREDSOGN_HERREDSNUMMER
- [x] HERREDSOGN_KOEBSTADNUMMER
- [x] HERREDSOGN_SOGNENUMMER
- [x] ID_LOKALID
- [x] ID_NAMESPACE
- [x] KOTE  (jf #119)
- [x] KOTEREFERENCEVERSION
- [x] LOEBENUMMER
- [x] MAALEAAR  (jf #121)
- [x] MAALEMETODE
- [ ] MAALSKITSE
- [x] MIDDELFEJL
- [x] MVSTATUS
- [x] NORTHING  (jf #116)
- [x] OBJECTID
- [x] REGISTRERINGFRA
- [x] REGISTRERINGSAKTOER
- [x] REGISTRERINGTIL
- [x] STATUS
- [x] TEKSTBESKRIVELSE
- [x] VIRKNINGFRA
- [x] VIRKNINGSAKTOER
- [x] VIRKNINGTIL

Sidetabeller
-------------

* HOEJDEFIKSPUNKTFO_FOTO
    - [x] HOEJDEFIKSPUNKTFOOBJECTID
    - [x] FOTO
* HOEJDEFIKSPUNKTFO_KOTEDESC
    - [x] HOEJDEFIKSPUNKTFOOBJECTID
    - [x] KOTEDESC
* HOEJDEFIKSPUNKTFO_PUNKTDESC
    - [x] HOEJDEFIKSPUNKTFOOBJECTID
    - [x] PUNKTDESC
* HOEJDEFIKSPUNKTFO_SPECIALNUMMEROBJECTID
    - [x] HOEJDEFIKSPUNKTFOOBJECTID
    - [x] SPECIALNUMMEROBJECTID

**Comment by busstoptaktik** [comment]
Jeg antager at der kun findes en kotereferenceversion: FVR2009 alias sridid 25 EPSG:5317, og hakker denne af @Helle-Git af-hak den igen, hvis du mener det er en fejl

**Comment by busstoptaktik** [comment]
EPSG:5317, alias sridid 25

**Comment by Helle-Git** [comment]
Der er kotereferenceversion FVR09 på alle.
