### ISSUE TITLE
Status på mapping til HOEJDEFIKSPUNKTGL

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#136]
Hovedtabel
-------------

- [x] AFMAERKNINGSBESKRIVELSE
- [ ] ARTSKODE #123
- [x] EASTING jf #111
- [x] FIKSPUNKTSBESKRIVELSE
- [x] FIKSPUNKTSNUMMER jf #118 
- [x] FORRETNINGSHAENDELSE
- [x] FORRETNINGSOMRAADE
- [x] FORRETNINGSPROCES
- [x] GEOMETRI
- [x] GMLID
- [x] HERREDSOGN_HERREDSNUMMER
- [x] HERREDSOGN_KOEBSTADNUMMER
- [x] HERREDSOGN_SOGNENUMMER
- [x] ID_LOKALID
- [x] ID_NAMESPACE
- [x] KOTE
- [x] KOTEREFERENCEVERSION
- [x] LOEBENUMMER
- [x] MAALEAAR
- [x] MAALEMETODE  jf #143 
- [ ] MAALSKITSE
- [x] MIDDELFEJL
- [x] MVSTATUS
- [x] NORTHING  jf #111 
- [x] OBJECTID
- [x] REGISTRERINGFRA
- [x] REGISTRERINGSAKTOER
- [x] REGISTRERINGTIL
- [x] STATUS
- [x] TEKSTBESKRIVELSE
- [x] VIRKNINGFRA
- [x] VIRKNINGSAKTOER
- [x] VIRKNINGTIL

Sidetabeller
-------------

* HOEJDEFIKSPUNKTGL_FOTO
    - [x] HOEJDEFIKSPUNKTGLOBJECTID
    - [x] FOTO
* HOEJDEFIKSPUNKTGL_KOTEDESC
    - [x] HOEJDEFIKSPUNKTGLOBJECTID
    - [x] KOTEDESC
* HOEJDEFIKSPUNKTGL_PUNKTDESC
    - [x] HOEJDEFIKSPUNKTGLOBJECTID
    - [x] PUNKTDESC
* HOEJDEFIKSPUNKTGL_SPECIALNUMMEROBJECTID
    - [x] HOEJDEFIKSPUNKTGLOBJECTID
    - [x] SPECIALNUMMEROBJECTID

**Comment by Helle-Git** [comment]
Hvor behandles de enkelte attributter?
F.eks. er der forskelle for MAALEMETODE, der er denne fordeling
(Antal, værdi i FIRE, værdi i UM)


2 |   |   |   |   | blanding af terrestrisk måling med GPS   eller fotogrammetrisk måling | fotogrammetrisk opmålt
-- | -- | -- | -- | -- | -- | --
2353 |   |   |   |   | blanding af terrestrisk måling med GPS eller fotogrammetrisk måling | terrestrisk måling

**Comment by kbevers** [comment]
> Hvor behandles de enkelte attributter?

I seperate issues. Hvis der mangler et, så opret det og beskriv situationen der skal afklares.

**Comment by busstoptaktik** [comment]
Målemetode sættes til terrestrisk (se #143)
