### ISSUE TITLE
Status på mapping til PLANFIKSPUNKTFO

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#137]
Hovedtabel
-------------

- [x] AFMAERKNINGSBESKRIVELSE
- [ ] ARTSKODE issue #169 
- [x] EASTING
- [x] ELLIPSOIDEHOEJDE
- [x] FIKSPUNKTSBESKRIVELSE
- [x] FIKSPUNKTSNUMMER
- [ ] FO10KMNET
- [x] FORRETNINGSHAENDELSE
- [x] FORRETNINGSOMRAADE
- [x] FORRETNINGSPROCES
- [x] GEOMETRI
- [x] GPSEGNET
- [x] GMLID
- [x] HERREDSOGN_HERREDSNUMMER
- [x] HERREDSOGN_KOEBSTADNUMMER
- [x] HERREDSOGN_SOGNENUMMER
- [x] ID_LOKALID
- [x] ID_NAMESPACE
- [x] KOTE
- [x] KOTEREFERENCEVERSION
- [x] LOEBENUMMER
- [x] MAALEAAR
- [x] MAALEMETODE
- [ ] MAALSKITSE
- [x] MIDDELFEJL
- [x] MVSTATUS
- [x] NORTHING
- [x] OBJECTID
- [x] REGISTRERINGFRA
- [x] REGISTRERINGSAKTOER
- [x] REGISTRERINGTIL
- [x] STATUS
- [x] TEKSTBESKRIVELSE
- [x] VIRKNINGFRA
- [x] VIRKNINGSAKTOER
- [x] VIRKNINGTIL

Sidetabeller
-------------

* PLANFIKSPUNKTFO_FOTO
    - [x] PLANFIKSPUNKTFOOBJECTID
    - [x] FOTO
* PLANFIKSPUNKTFO_KOTEDESC issue #156  
    - [x] PLANFIKSPUNKTFOOBJECTID
    - [x] KOTEDESC
* PLANFIKSPUNKTFO_PUNKTDESC   issue #157 
    - [x] PLANFIKSPUNKTFOOBJECTID
    - [x] PUNKTDESC
* PLANFIKSPUNKTFO_SPECIALNUMMEROBJECTID
    - [x] PLANFIKSPUNKTFOOBJECTID
    - [x] SPECIALNUMMEROBJECTID

**Comment by busstoptaktik** [comment]
Jeg har hakket "GPSEGNET" af, med henvisning til listen over GNSS-målte punkter ovre i #127.

**Comment by kbevers** [comment]
> Jeg har hakket "GPSEGNET" af, med henvisning til listen over GNSS-målte punkter ovre i #127.

Der manglede en beskrivelse af hvordan de skal mappes: https://github.com/Kortforsyningen/FIRE-DDL/issues/142

**Comment by Helle-Git** [comment]
For planfikspunkter på Grønland, gælder at der skal være en 'IDENT:station' tilknyttet punktet.
Er det også tilfældet for de færøske?

**Comment by kbevers** [comment]
> Er det også tilfældet for de færøske?

Nej. Hvis der findes et landsnr skal det bruges. Hvis ikke der er et landsnr så skal stationsnr bruges. Så vidt jeg lige kan se burde det dække alle punkterne, men hvis det ikke gør så må GNSS- og diverse-numre derefter tages i betragtning, så vi er sikker på at der bliver tilknyttet et fikspunktsnummer.

**Comment by Helle-Git** [comment]
Det er ikke et spørgsmål om hvilke identer, der skal anvendes hvornår; 
MEN for de grønlandske gælder, at der SKAL være et stationsnummer tilknyttet punktet; der kan også være andre; f.eks. landsnr, GNSS- og diverse; men punktet tages kun i betragtning, hvis der findes et stationsnummer.  (Jeg fjerner betingelsen for de disse, og ser hvad der sker)
