### ISSUE TITLE
Status på mapping til PLANFIKSPUNKTGL

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#138]
Hovedtabel
-------------

- [x] AFMAERKNINGSBESKRIVELSE
- [x] ARTSKODE  jf #147 
- [x] EASTING
- [x] ELLIPSOIDEHOEJDE
- [x] FIKSPUNKTSBESKRIVELSE
- [x] FIKSPUNKTSNUMMER
- [x] FORRETNINGSHAENDELSE
- [x] FORRETNINGSOMRAADE
- [x] FORRETNINGSPROCES
- [x] GEOMETRI
- [x] GPSEGNET  jf #138 
- [x] GMLID
- [x] HERREDSOGN_HERREDSNUMMER
- [x] HERREDSOGN_KOEBSTADNUMMER
- [x] HERREDSOGN_SOGNENUMMER
- [x] ID_LOKALID
- [x] ID_NAMESPACE
- [x] KOTE
- [x] KOTEREFERENCEVERSION  (jf #144)
- [x] LOEBENUMMER
- [x] MAALEAAR
- [x] MAALEMETODE
- [ ] MAALSKITSE
- [x] MIDDELFEJL
- [x] MVSTATUS
- [x] NORTHING
- [x] OBJECTID
- [x] REFGR
- [x] REGISTRERINGFRA
- [x] REGISTRERINGSAKTOER
- [x] REGISTRERINGTIL
- [x] STATUS
- [x] TEKSTBESKRIVELSE
- [x] VIRKNINGFRA
- [x] VIRKNINGSAKTOER
- [x] VIRKNINGTIL

Sidetabeller
-------------

* PLANFIKSPUNKTGL_FOTO
    - [x] PLANFIKSPUNKTGLOBJECTID
    - [x] FOTO
* PLANFIKSPUNKTGL_KOTEDESC
    - [x] PLANFIKSPUNKTGLOBJECTID
    - [x] KOTEDESC
* PLANFIKSPUNKTGL_PUNKTDESC
    - [x] PLANFIKSPUNKTGLOBJECTID
    - [x] PUNKTDESC
* PLANFIKSPUNKTGL_SPECIALNUMMEROBJECTID
    - [x] PLANFIKSPUNKTGLOBJECTID
    - [x] SPECIALNUMMEROBJECTID

**Comment by busstoptaktik** [comment]
@Helle-Git var der mere end en værdi for KOTEREFERENCEVERSION i PLANFIKSPUNKTGL?

**Comment by busstoptaktik** [comment]
REFGR: findes via attribut NET:REFGR

STATUS: altid "gældende"

**Comment by busstoptaktik** [comment]
GPSEGNET: alle REFGR-punkter er GPSegnede

**Comment by Helle-Git** [comment]
Se #144 for værdifordeling af KOTEREFERENCEVERSION (der er 2)

**Comment by Helle-Git** [comment]
GPSEGNET:  Hvis det IKKE er et REFGR-markeret punkt, sættes værdien til 'ikke vurderet'
