### ISSUE TITLE
Trigger AID#KOORDINAT is invalid

### ISSUE THREAD

**Issue by bjornharrtell** [Kortforsyningen/FIRE-DDL#14]
The trigger "AID#KOORDINAT" at:

https://github.com/Kortforsyningen/FIRE-DDL/blob/70c8df6a72e869ed4d1a766ca1bbd2c491b27567/DDL.sql#L725-L740

Seem to cause "ORA-04098: trigger 'FIRE.AID#KOORDINAT' is invalid and failed re-validation".

**Comment by kbevers** [comment]
When does this error appear? When loading the DDL or when inserting data?

**Comment by bjornharrtell** [comment]
When inserting data.

**Comment by nikolajkamstrup** [comment]
It fails when loading DDL (ORA-00942). Seems like the code is probably copied from the test environment as it says schema name FIRE_TEST, see line 728

**Comment by nikolajkamstrup** [comment]
Fix is to remove the "FIRE_TEST." prefix

**Comment by bjornharrtell** [comment]
Hmm last time I looked / copy pasted there was no FIRE_TEST prefix... but git history doesn't explain. mysterious. @kbevers I hope you are not force pushing? :)

**Comment by kbevers** [comment]
> @kbevers I hope you are not force pushing? :)

Yes, I am. Or was. I have notified Asger and Nikolaj in an email. For some reason I haven't got your mail address so you weren't included in that thread - sorry! This was the only way I could fix a bad diff between versions of the DDL. It's never cool to force push, but it wasn't very cool to have a diff consisting of 700 discarded lines and 700 new lines. So, sorry for the confusion it may have caused but hopefully thing make sense now!

**Comment by bjornharrtell** [comment]
Not cool! :)

**Comment by kbevers** [comment]
> But it still fails when inserting data although with another error.
ORA-04091: table FIRE_ADM.KOORDINAT is mutating, trigger/function may not see it
ORA-06512: at "FIRE_ADM.AID#KOORDINAT", line 5
ORA-04088: error during execution of trigger 'FIRE_ADM.AID#KOORDINAT'

Is this caused by a poorly defined constrain/trigger or inconsistent data?

**Comment by B027987** [comment]
Deleted trigger, has to find another way to check validity

**Comment by PeterWestNielsen** [comment]
Trigger replaced with index:
CREATE UNIQUE INDEX KOOR_UNIQ_001 ON KOORDINAT
(SRID, PUNKTID, REGISTRERINGTIL);
