### ISSUE TITLE
Udelad punkter uden fikspunktsnummer i migrering fra REFGEO

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#140]
Citater fra #63:

> Der er stadig problemer med at finde fikspunktsnummer for disse 4 REFGEO ID: 533768, 534080, 72205 og 72206.

og

> Okay, det er uheldigt. Jeg forstår ikke hvorfor de bliver overført i første omgang. Er det muligt at se bort fra dem? Jeg er klar over at det ikke er en særlig skøn løsning, men da årsagen til deres eksistens ikke er kendt kan vi ikke gøre ret meget andet.

@kbevers - enden på diskussionen blev vist at det skal ordnes under migrering (de 4 punkter skal ikke med over i FIRE), men hvordan?

**Comment by busstoptaktik** [comment]
Se også #105

**Comment by kbevers** [comment]
Burde bliver taget hånd om i forbindelse med https://github.com/Kortforsyningen/FIRE-DDL/issues/105. Jeg arbejder på en løsning.
