### ISSUE TITLE
Målskitse (alle tabeller)

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#141]
Jeg tror at "MAALSKITSE" bare handler om at finde det rette filnavn frem, men den er uafklaret i alle 8 UM-tabeller, så det fylder en del i mangelstatistikken.

Er der nogen blokerende udeståender på den?

**Comment by busstoptaktik** [comment]
OK  -  ser nu at vi allerede har #73 vedr. højdefikspunkter, med beskrivelsen 

> punktinfo (id=367 ~ SKITSE:sti)

@Helle-Git er dette tilstrækkeligt til at afklare sagen?

**Comment by kbevers** [comment]
Stier i målskitse er på formen `/img/maalskitser/DK/K-01-00127.png`. Den tilsvarende skitse i FIRE er registreret som `skitser\K-01-00127_2.png`. I øjeblikket ligger filer under `F:\GRF\Data\FIRE\skitser`. Jeg vil tro at der skal gøres et eller andet ved den situation på den ene eller anden måde. Enten skal filerne flyttes til en anden server eller også skal vi have smidt dem et sted på F:\ hvor der er læseadgang for andre en GRF-medarbejdere, fx F:\GDB\.

**Comment by busstoptaktik** [comment]
> eller også skal vi have smidt dem et sted på F:\ hvor der er læseadgang for andre en GRF-medarbejdere, fx F:\GDB

@Helle-Git og/eller (kan ikke lige finde Steens github-tag): Er dette løsningen?
