### ISSUE TITLE
HEOJDEFIKSPUNKTGL.MAALEMETODE

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#143]
Der pr disse forskelle på værdierne (fordeling):

antal | FIRE-værdi | UM-værdi
-- | -- | --
2 | blanding af terrestrisk måling med GPS eller fotogrammetrisk måling | fotogrammetrisk opmålt
2353 | blanding af terrestrisk måling med GPS eller fotogrammetrisk måling | terrestrisk måling

**Comment by busstoptaktik** [comment]
Jeg tvivler på de to fotogrammetrisk målte i UM. Sæt det hele til terrestrisk. Muligvis er FIRE-værdien forkert, men det kan vi rette op på i FIRE. For koter er der ikke så meget andet end terrestrisk der giver mening (alt andet bør kunne genkendes ved enorme - flere meter eller dekameter - spredninger).
