### ISSUE TITLE
PLANFIKSPUNKTGL.KOTEREFERENCEVERSION

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#144]
Der er denne fordeling af disse i UM:

6032	MSL
3648	ingen

**Comment by busstoptaktik** [comment]
Sættes til:

- MSL for punkter med EPSG:5714.
- GVR2000 for punkter med EPSG:8266
- GVR2016 for punkter med EPSG:8267

Vi ved ikke om de 3648 uden angivelse reelt er GVR2000 eller GVR2016, men det er ikke decideret forker at kalde dem MSL (det er bare knapt så god en beskrivelse)

**Comment by kbevers** [comment]
Bemærk at GVR2000 og GVR2016 i øjeblikket er at finde i FIRE, men vil komme på et senere tidspunkt.

**Comment by busstoptaktik** [comment]
> Vi ved ikke om de 3648 uden angivelse reelt er GVR2000 eller GVR2016

Eller, givet at vi befinder os i en planfikspunkttabel, at de bare ikke har nogen kote.

**Comment by Helle-Git** [comment]
Der er følgende 'tilladte' værdier for KOTEREFERENCEVERSION

**Comment by kbevers** [comment]
Jeg har i https://github.com/Kortforsyningen/FIRE-DDL/commit/7aa761eb31f5fcfcc42395e61ba4bc05189c236b tilføjet SRIDTYPEr for GVR2000 og GVR2016 men da der ikke findes nogle koordinater for disse to SRID'er så skal de ikke tages i betragtning i mapningen.


> Eller, givet at vi befinder os i en planfikspunkttabel, at de bare ikke har nogen kote.

Det er tilfældet. kotereferenceversion "ingen" betyder at der ikke er en kote tilknyttet.

**Comment by busstoptaktik** [comment]
> så skal de ikke tages i betragtning i mapningen

... men kan jo blive aktuelt i tilfælde af inkrementelle opdateringer

**Comment by kbevers** [comment]
> ... men kan jo blive aktuelt i tilfælde af inkrementelle opdateringer

og i så fald må de få klistet "MSL"-betegnelsen på sig. I hvert fald indtil udstillingsmodellen ændres til også at tillade "GVR20yy" (og det tror jeg aldrig vi får gjort).

**Comment by busstoptaktik** [comment]
> og det tror jeg aldrig vi får gjort

Nej, ikke for denne udstillingsmodel. Det bliver næste version, med et nyt API und einem neues Valdemar webapppppppp ovenpå

**Comment by kbevers** [comment]
Det er uklart for mig om denne er mappet allerede eller ej, men da issuet er åbent antager jeg at der stadig er tvivl om hvordan det gøres.

Der skal tjekkes om der findes en koordinat på punkt med sridtype EPSG:5714. Hvis der gør det sættes kotereferenceversion til "MSL", ellers "ingen".

**Comment by Helle-Git** [comment]
Da de nordatlantiske planfikspunkter venter til der er helt styr på de øvrige - er denne ikke lavet endnu.
