### ISSUE TITLE
PLANFIKSPUNKTDK.EASTING og NORTHING

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#146]
Hvordan bestemmes disse for danske planfikspunkter?
(Der er beskrevet hvordan de findes for højdefikspunkter , og dette giver MEGET store afvigelser, når det benyttes for disse!.)
Transformationsparameteren sættes til 25832; for Grønland : 32624 og for Færøerne:  25829  

Eksempel: 
EASTING-værdier (FIRE UM): 3268812	559289
NORTHING-værdier (FIRE UM): 7447635	6346460

**Comment by kbevers** [comment]
Da det denne gang faktisk handler om planfikspunkterne vil jeg tillade mig endnu engang at henvise til min mail d. 7./11. For nemhedens skyld indsætter jeg her den relevante SQL fra mailen: 

```
SELECT count(*) FROM ( 
        SELECT 
          k.x, k.y,
          SDO_CS.TRANSFORM(SDO_GEOMETRY(2001, 4258, SDO_POINT_TYPE(k.x, k.y, NULL), NULL, NULL), 25832).SDO_POINT.x geodesy_easting, -- BRUG DENNE
          SDO_CS.TRANSFORM(SDO_GEOMETRY(2001, 4258, SDO_POINT_TYPE(k.x, k.y, NULL), NULL, NULL), 25832).SDO_POINT.y geodesy_northing,-- BRUG DENNE
          SDO_CS.TRANSFORM(g.geometri, 25832).SDO_POINT.x geometry_easting,
          SDO_CS.TRANSFORM(g.geometri, 25832).SDO_POINT.y geometry_northing
        
        FROM koordinat k 
        JOIN geometriobjekt g ON g.punktid=k.punktid
        WHERE 1=1
          AND k.registreringtil IS NULL 
          AND k.sridid IN (2,3)
 )  WHERE sqrt(power(geodesy_easting-geometry_easting,2)+power(geodesy_northing-geometry_northing,2)) > 1.0;
```

Pointen er, at vi skal have oversat de geografiske koordinatværdier (grader) fra koordinattabellen til UTM-koordinater frem for at oversætte koordinaterne fra geometriobjekttabellen.
