### ISSUE TITLE
PLANFIKSPUNKTGL.ARTSKODE

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#147]
Hvordan skal denne sættes?

**Comment by kbevers** [comment]
# Fundamental punkt

Punkter hvor ATTR:fundamentalpunkt == EPSG:4747. Der skal gerne være fire alt i alt.

# Overordnet planfikspunktsnet

NET:REFGR (dog med undtagelse af punkter med ATTR:fundamentalpunkt)

# Punkt i net af høj kvalitet

GR96 koordinater hvorom der gælder, at de to følgende betingelser er opfyldt: 

1) Nyeste observationer, der er indgået i beregningen af koten, er højst 10 år gamle, samt 
2) den estimerede spredning på koten er højst 50 mm 

Noget i stil med

```
SELECT *
FROM koordinat k
WHERE T > trunc(SYSDATE - interval '10' year,'YEAR') -- Ti år eller nyere
        AND sx <= 50; -- spredning højst 50 mm
```

# punkter i net af lavere eller ukendt kvalitet

Øvrige GR96 koordinater, altså dem der endnu ikke er blevet fanget af de ovenstående kategorier OG som ikke har feltet ”Transformeret” krydset af.

# punkt i net af lav kvalitet bestemt ved få eller ingen overbestemmelse

Udelades. Der er ikke noget nævneværdig forskel mellem denne og "punkter i net af lavere eller ukendt kvalitet"

# Punkter transformeret til gældende system

Transformerede GR96 koordinater.

**Comment by busstoptaktik** [comment]
Ged barberet ovenfor af @kbevers - lukker denne
