### ISSUE TITLE
PLANFIKSPUNKTDK_PLANDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#148]
Beskrivelse af udfaldsrum (fx fra DDL) indsættes her mhp. videre analyse af hvilke `ATTR:xxx` der skal mappes hertil

**Comment by Helle-Git** [comment]
I følge DDL, kan der antages disse værdier:


Værdinavn | Dokumentation
-- | --
fundamentalstation | Station som er et hovedpunkt i det overordnede referencenet.
godkendt til matrikulære arbejder | Punkt som har tilstrækkelig nøjagtighed til brug for matrikulært arbejde.
hjælpepunkt | Hjælpepunkt i opmålingen af højdefikspunktnettet.
vedligeholdes af fikspunktsmyndigheden | Punkt der oprindeligt hørte til det overordnede planfikspunktnet eller højdefikspunktnettet.

De findes med denne fordeling i UM (aktuelle data):

COUNT(*) | PLANDESC
-- | --
340823 | godkendt til matrikulære arbejder
124222 | hjælpepunkt
773 | fundamentalstation
114 | vedligeholdes af fikspunktsmyndigheden

**Comment by Helle-Git** [comment]
Bestemme værdierne i plandesc-tabellerne på samme måde som i KOTEDESC-tabellerne (f.eks. issue #150) ?

**Comment by kbevers** [comment]
De skal mappes således:

PLANDESC | punktinfotype
---- |-----
godkendt til matrikulære arbejder | ATTR:MV_punkt
hjælpepunkt | ATTR:hjælpepunkt
fundamentalstation | NET:10KM
vedligeholdes af fikspunktsmyndigheden | ATTR:GI_punkt
