### ISSUE TITLE
NULL constraint should be in schema not as trigger?

### ISSUE THREAD

**Issue by bjornharrtell** [Kortforsyningen/FIRE-DDL#15]
https://github.com/Kortforsyningen/FIRE-DDL/blob/eaa66de58d4e7a342e1e6677ab5e2eb17f33a172/DDL.sql#L802-L846

**Comment by B027987** [comment]
Its not a simple NULL check.

IF the data in OBSERVATIONTYPE for this COLUMN is NOT NULL THEN
this column (in OBSERVATION) may not be NULL

just like the TRIGGER SAYS 👍 

  select value1,
         value2,
         value3,
         value4,
         value5,
         value6,
         value7,
         value8,
         value9,
         value10,
         value11,
         value12,
         value13,
         value14,
         value15 into
         val1,
         val2,
         val3,
         val4,
         val5,
         val6,
         val7,
         val8,
         val9,
         val10,
         val11,
         val12,
         val13,
         val14,
         val15
  from observationtype a
  where A.OBSERVATIONSTYPE = :new.observationstype;
         

  if :new.value1 is null and val1 is not null THEN
    RAISE_APPLICATION_ERROR(20000,'Value1 må ikke være NULL'); 

...

**Comment by bjornharrtell** [comment]
Ok I see, partially. :)

But this raises another question. The values in observationstype are VARCHAR2(4000) but are attempted to be coerced into number, this does not make sense to me. Test data indicated that the values in observationstype can indeed be a textual description like for example `Covarians dy, dz [m^2]`.

**Comment by B027987** [comment]
Peter is sick today, hes in charge of the datatypes, im sure he will fix it when back.

**Comment by B027987** [comment]
You are correct, I looked in the wrong place for the type, corrected and will be applied in next DDL
(changed to VARCHAR2)

**Comment by PeterWestNielsen** [comment]
Updated trigger add to new DDL 20181129.v0.4.FikspunktForvaltning
