### ISSUE TITLE
HOEJDEFIKSPUNKTDK_KOTEDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#150]
Beskrivelse af udfaldsrum (fx fra DDL) indsættes her mhp. videre analyse af hvilke `ATTR:xxx` der skal mappes hertil

**Comment by Helle-Git** [comment]
I følge DDL, kan der antages disse værdier:

Værdinavn | Dokumentation
-- | --
fundamentalstation | Station som er et hovedpunkt i det overordnede referencenet.
godkendt til matrikulære arbejder | Punkt som har tilstrækkelig nøjagtighed til brug for matrikulært arbejde.
hjælpepunkt | Hjælpepunkt i opmålingen af højdefikspunktnettet.
vedligeholdes af fikspunktsmyndigheden | Punkt der oprindeligt hørte til det overordnede planfikspunktnet eller højdefikspunktnettet.



De findes med denne fordeling i UM (aktuelle data):


COUNT(*) | KOTEDESC
-- | --
923 | godkendt til matrikulære arbejder
6440 | fundamentalstation
7395 | hjælpepunkt
3451 | vedligeholdes af fikspunktsmyndigheden

**Comment by Helle-Git** [comment]
Jeg har især svært ved at finde en måde at identificere
* 'fundamentalstation' og
* 'vedligeholdes af fikspunktsmyndigheden'

'Godkendt til matrikulære arbejder': følger ATTR:MV_punkt
'hjælpepunkt' følger ATTR:hjælpepunkt

**Comment by kbevers** [comment]
De skal mappes således:

PLANDESC | punktinfotype
---- |-----
godkendt til matrikulære arbejder | ATTR:MV_punkt
hjælpepunkt | ATTR:hjælpepunkt
fundamentalstation | NET:DVR90
vedligeholdes af fikspunktsmyndigheden | ATTR:GI_punkt

Mapningen af "fundamentalstation" kommer ikke til at stemme overens med hvad der ligger i REFGEO-UM. Jeg kan ikke gennemskue hvad der er fælles for de 6440 punkter der er markeret som fundamentalstation. Det giver dog mening at bruge dem fra NET:DVR90. Det giver så vidt jeg husker i omegnen af 1500 punkter.
