### ISSUE TITLE
HOEJDEFIKSPUNKTDK_PUNKTDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#151]
Beskrivelse af udfaldsrum (fx fra DDL) indsættes her mhp. videre analyse af hvilke `ATTR:xxx` der skal mappes hertil

**Comment by Helle-Git** [comment]
I følge DDL, kan der antages disse værdier:


Værdinavn | Dokumentation
-- | --
afmærkning tabtgået | Det fysiske fikspunkt findes ikke længere.
eksternt etableret | Fikspunkt etableret af en ekstern anvender, andre end referensenetsmyndigheden.
naturligt fikspunkt | En naturlig forefindende signifikant objekt. f.eks kirketårn, skorsten.
postament | En granitblok sat til brug for første til tredie ordens opmåling af det overordnet referencenet.
begrænset adgang | Fikspunkt hvor der er begrænsning i adgang og anvendelse af punktet.

De findes med denne fordeling i UM (aktuelle data):

COUNT(*) | PUNKTDESC | TAB
-- | -- | --
24499 | afmærkning tabtgået | hoejdefikspunktdk_punktdesc
7128 | begrænset adgang | hoejdefikspunktdk_punktdesc
269 | postament | hoejdefikspunktdk_punktdesc
11 | naturligt fikspunkt | hoejdefikspunktdk_punktdesc
15 | eksternt etableret | hoejdefikspunktdk_punktdesc

**Comment by Helle-Git** [comment]
Jeg gætter på at de - for alle - fikspunktstyper, skal findes udfra punktinfo:
MEN hvordan findes 'postament'??, og er de andre rigtige??

  | INFOTYPE
-- | --
afmærkning tabtgået | ATTR:tabtgået
begrænset adgang | ATTR:restricted
Postament | ???? --
naturligt fikspunkt | AFM:naturlig
eksternt etableret | ATTR:ekstern

**Comment by kbevers** [comment]
> MEN hvordan findes 'postament'??

Noget i den her stil:

```
SELECT * FROM punktinfo pi
JOIN punkt p ON pi.punktid=p.id
WHERE infotypeid in (SELECT infotypeid FROM punktinfotype WHERE LOWER(beskrivelse) LIKE '%postament%');
```

> og er de andre rigtige??

Ja, det set fornuftigt ud.

**Comment by Helle-Git** [comment]
Der mangler en håndfuld, som alle findes med 'postament' i UM

postament | K-01-00863 | 112
-- | -- | --
postament | K-76-00002 | 60117
postament | 1-13-00821 | 74435
postament | 10-02-00001 | 114146
postament | 25-12-00002 | 162598
postament | 27-12-00001 | 169716
postament | 30-07-00001 | 176348
postament | 32-07-00001 | 182181
postament | 46-06-00003 | 231827
postament | 65-16-00001 | 312543
postament | 70-08-09025 | 325202
postament | 73-14-09032 | 332390
postament | 96-01-00001 | 390574
postament | 110-09-00001 | 431502
postament | 117-02-00001 | 449195
postament | 118-08-00001 | 453087
postament | 147-08-00821 | 537682


Ved at slå dem op i FIRE, akn jeg se at de IKKE har en 'postament-like'-punktinfo tilknyttet;
men de har alle en 'AFM-diverse' (infotypeid=1) med en fritekst, hvori der ofte indgår ordet postament.
F.eks.

-- | -- | --
1 |   | Hul i midte af skifferplade   på     muret postament, ca. 0.96 m højt.
1 |   | Muret astronomisk pille   90x70x150     cm.
1 |   | Muret pille på betonstøbning        85x85x100 cm med jernplade.      Hul i midte af jernpladen.

**Comment by kbevers** [comment]
> de har alle en 'AFM-diverse' (infotypeid=1) med en fritekst, hvori der ofte indgår ordet postament.

Ja, det var derfor jeg lavede ovenstående udtræk, men det er tilsyneladende ikke retvisende. Det ser ud til at alle punkter af typen postament kan findes i REFGEO vha 

```
SELECT refnr FROM quickstninform WHERE p_mark=1;
```

Jeg laver en tilføjelse til migrationsscripts sådan at AFM:postament oprettes i fremtiden.

**Comment by kbevers** [comment]
> Jeg laver en tilføjelse til migrationsscripts sådan at AFM:postament oprettes i fremtiden.

Tilføjet pr 417201a. Virker næste gang der køres en migration. I weekenden?

**Comment by Helle-Git** [comment]
Der udtrækkes 232  'for meget' (dvs de findes ikke tilsvarende i UM).
Nogle er med ¨postament' - de venter til ovenstående ændring er indført.
De øvrige er jævnt fordelt på 'afmærkning tabtgået' og 'begrænset adgang'  
(Begge findes også i den del, der er fælles for FIRE og UM).
Måske der kommer lidt for mange af disse markeringer med? 
(Eller de har manglet i UM -  lidt pinligt hvis der er restrictede, der er blevet synlige..)
eksempler:

tekst | punktid | lokalid
-- | -- | --
afmærkning tabtgået | 9788696D-9AF7-5A7A-E053-1A041EACC99C | 406080
afmærkning tabtgået | 9788696D-9B08-5A7A-E053-1A041EACC99C | 406097
begrænset adgang | 9788696E-0382-5A7A-E053-1A041EACC99C | 432856
begrænset adgang | 9788696E-0F03-5A7A-E053-1A041EACC99C | 435801
postament | 9788696E-3561-5A7A-E053-1A041EACC99C | 445627
postament | 9788696E-3562-5A7A-E053-1A041EACC99C | 445628
postament | 9788696E-3565-5A7A-E053-1A041EACC99C | 445631
begrænset adgang | 9788696E-A81D-5A7A-E053-1A041EACC99C | 475000
begrænset adgang | 9788696E-B571-5A7A-E053-1A041EACC99C | 478414
begrænset adgang | 9788696E-B6E2-5A7A-E053-1A041EACC99C | 478783
begrænset adgang | 9788696E-B6E3-5A7A-E053-1A041EACC99C | 478784

**Comment by kbevers** [comment]
> Måske der kommer lidt for mange af disse markeringer med?

Det har jeg svært ved at svare på. 

Hvad er punkterne i tabellen eksempler på? Punkter du trækker ud fra FIRE men som ikke er at finde i UM?

**Comment by Helle-Git** [comment]
Ja, det er punktdesc der er trukket ud fra FIRE; men som ikke findes i UM .

**Comment by kbevers** [comment]
Jeg tror allerede den her er på plads, men for god ordens skyld og konsistens med tilsvarende issues, så kører vi altså med følgende mapping:

 PUNKTDESC | INFOTYPE
-- | --
afmærkning tabtgået | ATTR:tabtgået
begrænset adgang | ATTR:restricted
Postament | AFM:postmanent
naturligt fikspunkt | AFM:naturlig
eksternt etableret | ATTR:ekstern
