### ISSUE TITLE
PLANFIKSPUNKTGL_PLANDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#152]
Beskrivelse af udfaldsrum (fx fra DDL) indsættes her mhp. videre analyse af hvilke `ATTR:xxx` der skal mappes hertil

**Comment by Helle-Git** [comment]
I følge DDL, kan der antages disse værdier:


Værdinavn | Dokumentation
-- | --
fundamentalstation | Station som er et hovedpunkt i det overordnede referencenet.
godkendt til matrikulære arbejder | Punkt som har tilstrækkelig nøjagtighed til brug for matrikulært arbejde.
hjælpepunkt | Hjælpepunkt i opmålingen af højdefikspunktnettet.
vedligeholdes af fikspunktsmyndigheden | Punkt der oprindeligt hørte til det overordnede planfikspunktnet eller højdefikspunktnettet.

De findes med denne fordeling i UM (aktuelle data):

COUNT(*) | PLANDESC
-- | --
118 | fundamentalstation

**Comment by kbevers** [comment]
De skal mappes således:

PLANDESC | punktinfotype
---- |-----
godkendt til matrikulære arbejder | ATTR:MV_punkt
hjælpepunkt | ATTR:hjælpepunkt
**fundamentalstation** | **NET:REFGR**
vedligeholdes af fikspunktsmyndigheden | ATTR:GI_punkt
