### ISSUE TITLE
PLANFIKSPUNKTGL_PUNKTDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#153]
Beskrivelse af udfaldsrum (fx fra DDL) indsættes her mhp. videre analyse af hvilke `ATTR:xxx` der skal mappes hertil

**Comment by Helle-Git** [comment]
I følge DDL, kan der antages disse værdier:

ærdinavn | Dokumentation
-- | --
afmærkning tabtgået | Det fysiske fikspunkt findes ikke længere.
eksternt etableret | Fikspunkt etableret af en ekstern anvender, andre end referensenetsmyndigheden.
naturligt fikspunkt | En naturlig forefindende signifikant objekt. f.eks kirketårn, skorsten.
postament | En granitblok sat til brug for første til tredie ordens opmåling af det overordnet referencenet.
begrænset adgang | Fikspunkt hvor der er begrænsning i adgang og anvendelse af punktet.


De findes med denne fordeling i UM (aktuelle data):

COUNT(*) | PUNKTDESC
-- | --
53 | afmærkning tabtgået
1897 | naturligt fikspunkt
8 | postament

**Comment by kbevers** [comment]
Skal mappes efter følgende principper:

Værdinavn | punktinfotype
-- | --
afmærkning tabtgået | ATTR:tabtgået
eksternt etableret | ATTR:ekstern
naturligt fikspunkt | AFM:naturlig
postament | AFM:postament
begrænset adgang |ATTR:restricted
