### ISSUE TITLE
HOEJDEFIKSPUNKTGL_KOTEDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#154]
Beskrivelse af udfaldsrum (fx fra DDL) indsættes her mhp. videre analyse af hvilke `ATTR:xxx` der skal mappes hertil

**Comment by Helle-Git** [comment]
I følge DDL, kan der antages disse værdier:

Værdinavn | Dokumentation
-- | --
fundamentalstation | Station som er et hovedpunkt i det overordnede referencenet.
godkendt til matrikulære arbejder | Punkt som har tilstrækkelig nøjagtighed til brug for matrikulært arbejde.
hjælpepunkt | Hjælpepunkt i opmålingen af højdefikspunktnettet.
vedligeholdes af fikspunktsmyndigheden | Punkt der oprindeligt hørte til det overordnede planfikspunktnet eller højdefikspunktnettet.


De findes med denne fordeling i UM (aktuelle data):

COUNT(*) | KOTEDESC
-- | --
173 | fundamentalstation

**Comment by kbevers** [comment]
Jeg kan ikke gennemskue hvad der gør et grønlandsk højdefikspunkt til en fundamentalstation. Mit forslag er at udelade dem i FIRE-UM, hvilket effektivt gør tabellen tom. Vi har ikke vedligeholdt højdefikspunkter i Grønland i evigheder så de er formentligt ikke meget værd i dag alligevel.

@busstoptaktik Er du enig i at udelade dem fra tabellen?
