### ISSUE TITLE
HOEJDEFIKSPUNKTGL_PUNKTDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#155]
Beskrivelse af udfaldsrum (fx fra DDL) indsættes her mhp. videre analyse af hvilke `ATTR:xxx` der skal mappes hertil

**Comment by Helle-Git** [comment]
I følge DDL, kan der antages disse værdier:


Værdinavn | Dokumentation
-- | --
afmærkning tabtgået | Det fysiske fikspunkt findes ikke længere.
eksternt etableret | Fikspunkt etableret af en ekstern anvender, andre end referensenetsmyndigheden.
naturligt fikspunkt | En naturlig forefindende signifikant objekt. f.eks kirketårn, skorsten.
postament | En granitblok sat til brug for første til tredie ordens opmåling af det overordnet referencenet.
begrænset adgang | Fikspunkt hvor der er begrænsning i adgang og anvendelse af punktet.

De findes med denne fordeling i UM (aktuelle data):

COUNT(*) | PUNKTDESC | TAB
-- | -- | --
80 | afmærkning tabtgået | hoejdefikspunktgl_punktdesc
2970 | naturligt fikspunkt | hoejdefikspunktgl_punktdesc
7 | postament | hoejdefikspunktgl_punktdesc

**Comment by kbevers** [comment]
Mappes på følgende vis:

 PUNKTDESC | INFOTYPE
-- | --
afmærkning tabtgået | ATTR:tabtgået
begrænset adgang | ATTR:restricted
Postament | AFM:postmanent
naturligt fikspunkt | AFM:naturlig
eksternt etableret | ATTR:ekstern
