### ISSUE TITLE
HOEJDEFIKSPUNKTFO_KOTEDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#158]
Beskrivelse af udfaldsrum (fx fra DDL) indsættes her mhp. videre analyse af hvilke `ATTR:xxx` der skal mappes hertil

**Comment by Helle-Git** [comment]
I følge DDL, kan der antages disse værdier:

Værdinavn | Dokumentation
-- | --
fundamentalstation | Station som er et hovedpunkt i det overordnede referencenet.
godkendt til matrikulære arbejder | Punkt som har tilstrækkelig nøjagtighed til brug for matrikulært arbejde.
hjælpepunkt | Hjælpepunkt i opmålingen af højdefikspunktnettet.
vedligeholdes af fikspunktsmyndigheden | Punkt der oprindeligt hørte til det overordnede planfikspunktnet eller højdefikspunktnettet.


COUNT(*) | KOTEDESC
-- | --
1 | fundamentalstation



De findes med denne fordeling i UM (aktuelle data):

**Comment by kbevers** [comment]
Brug ATTR:fundamentalpunkt som mapning af fundamentalstation. Grundet en fejl (se https://github.com/Kortforsyningen/FIRE-DDL/commit/a15d99730c2bb24f889a255359113812f884eef5) er det ene punkt, K-87-09037, ikke blevet påklistret denne attribut men det bliver den ved næste migration.
