### ISSUE TITLE
HOEJDEFIKSPUNKTDNN.PUNKTDESC

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#161]
I følge DDL, kan der antages disse værdier:

Værdinavn | Dokumentation
-- | --
afmærkning tabtgået | Det fysiske fikspunkt findes ikke længere.
eksternt etableret | Fikspunkt etableret af en ekstern anvender, andre end referensenetsmyndigheden.
naturligt fikspunkt | En naturlig forefindende signifikant objekt. f.eks kirketårn, skorsten.
postament | En granitblok sat til brug for første til tredie ordens opmåling af det overordnet referencenet.
begrænset adgang | Fikspunkt hvor der er begrænsning i adgang og anvendelse af punktet.

De findes med denne fordeling i UM (aktuelle data):

COUNT(*) | PUNKTDESC | TAB
-- | -- | --
26288 | afmærkning tabtgået | hoejdefikspunktdnn_punktdesc
2811 | begrænset adgang | hoejdefikspunktdnn_punktdesc
267 | postament | hoejdefikspunktdnn_punktdesc
10 | naturligt fikspunkt | hoejdefikspunktdnn_punktdesc
17 | eksternt etableret | hoejdefikspunktdnn_punktdesc

**Comment by kbevers** [comment]
Skal mappes efter følgende principper:

Værdinavn | punktinfotype
-- | --
afmærkning tabtgået | ATTR:tabtgået
eksternt etableret | ATTR:ekstern
naturligt fikspunkt | AFM:naturlig
postament | AFM:postament
begrænset adgang |ATTR:restricted

**Comment by busstoptaktik** [comment]
Kristian har angivet 1:1 mapping ovenfor. Lukker denne.
