### ISSUE TITLE
HOEJDEFIKSPUNKTDNN.KOTEDESC 

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#163]
I følge DDL, kan der antages disse værdier:

Værdinavn | Dokumentation
-- | --
fundamentalstation | Station som er et hovedpunkt i det overordnede referencenet.
godkendt til matrikulære arbejder | Punkt som har tilstrækkelig nøjagtighed til brug for matrikulært arbejde.
hjælpepunkt | Hjælpepunkt i opmålingen af højdefikspunktnettet.
vedligeholdes af fikspunktsmyndigheden | Punkt der oprindeligt hørte til det overordnede planfikspunktnet eller højdefikspunktnettet.

De findes med denne fordeling i UM (aktuelle data):

COUNT(*) | KOTEDESC
-- | --
5989 | godkendt til matrikulære arbejder
5957 | vedligeholdes af fikspunktsmyndigheden
1538 | fundamentalstation
1890 | hjælpepunkt

**Comment by kbevers** [comment]
PLANDESC | punktinfotype
---- |-----
godkendt til matrikulære arbejder | ATTR:MV_punkt
hjælpepunkt | ATTR:hjælpepunkt
fundamentalstation | ATTR:fundamentalpunkt
vedligeholdes af fikspunktsmyndigheden | ATTR:GI_punkt

Bemærk at der med ovenstående mapning vil komme en forskel i antallet af fundamentalpunkter. Der kommer eet punkt (G.M.902) ud med ovenstående. Bemærk at der er flere ATTR:fundamentalpunkt-attributter tilknyttet punktet, da det er fundamentalpunkt i flere koordinatsystemer - det skal naturligvis kun optræde en gang i tabellen.

I REFGEO-UM betyder fundamentalstation i denne sammenhæng punkter der har indgået i 3. præcisionsnivellement. Den information har vi ikke registreret i FIRE, derfor denne anderledes mapning.

**Comment by busstoptaktik** [comment]
> I REFGEO-UM betyder fundamentalstation i denne sammenhæng punkter der har indgået i 3. præcisionsnivellement. Den information har vi ikke registreret i FIRE,

Men NET:DVR90 udgør vel en stor delmængde deraf.
