### ISSUE TITLE
Gør namespace-constraints dynamiske

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#164]
I øjeblikket er namespaces til punktinfotype, observationtype og sridtype hårdkodede:

https://github.com/Kortforsyningen/FIRE-DDL/blob/417201a742f1804a582cae81abbc75ed47f443f9/DDL.sql#L959-L976

Det bør ændres til at læse namespaces fra de tilhørende tabeller punktinfotypenamespace, observationtypenamespace og sridtypenamespace.

Jeg antager at det kan gøres i stil med

```
ALTER TABLE PUNKTINFOTYPE ADD 
CONSTRAINT PUNKTINFOTYPE_CON_0001
CHECK (substr(infotype,1,instr(infotype,':')-1) in (SELECT namespace FROM punktinfotypenamespace))
ENABLE
VALIDATE;
```

**Comment by stsu** [comment]
det kan man ikke med constraints:
Error at line 1
ORA-02251: underforespørgsel er ikke tilladt her

**Comment by kbevers** [comment]
Hvad kan man så gøre? Andre steder bruger vores constraints/triggers data fra tabellerne til at afgøre om en indsættelse er tilladt eller ej.

**Comment by stsu** [comment]
HVIS PUNKTINFO.infotype kolonnen var splittet op i 2 kolonner(!) SÅ kunne første delen (AFM, ATTR,,,) være en fremmednøgle ind i PUNKTINFOTYPENAMESPACE.NAMESPACE

**Comment by stsu** [comment]
Det er altså ikke muligt:

  IF substr(:new.infotype,1,instr(:new.infotype,':')-1) not in (select namespace from punktinfonamespace) then

    RAISE_APPLICATION_ERROR(-20000,'Noinfotype in punktinfonamespace (!) ');

  END IF;



giver


![image](https://user-images.githubusercontent.com/6232716/70224765-1c6cc600-174e-11ea-9b9f-e38dc616ddf4.png)

**Comment by kbevers** [comment]
Jeg er stadigvæk ikke overbevist. Jeg har forsøgt mig med følgende trigger, som efter et par simple tests umiddelbart ser ud til at fungere efter hensigten:

```
CREATE OR REPLACE TRIGGER AIU#SRIDTYPE
AFTER INSERT OR UPDATE ON sridtype
FOR EACH ROW
DECLARE
   val varchar2(4000):= '';
BEGIN

  SELECT namespace INTO val
  FROM sridnamespace a
  WHERE a.namespace = substr(:new.srid,1,instr(:new.srid,':')-1);

  IF val IS NULL THEN
    RAISE_APPLICATION_ERROR(-20000,'Ugyldigt namespace');
  END IF;

END;
```

Jeg vil nødig påstå at jeg er ekspert på området, så gør mig gerne klogere på hvorfor det ikke lader sig gøre.

Jeg har prøvet den af på FIRE_TEST.

**Comment by kbevers** [comment]
NAMESPACE tabellerne er fjernet med seneste udgave af DDL'en, så dette er ikke aktuelt længere.
