### ISSUE TITLE
Sekscifrede løbenumre i landsnummer

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#168]
Relateret til #77: Der forekommer landsnumre med sekscifrede løbenumre, fx K-01-240090. Disse bliver registreret under IDENT:diverse, men burde vel være landsnr (lige som dem med ".yyyy" blev det i #77)

Eksempler fra Sys34-tabellen (de viste numre er refgeo_id, og nogle af dem relaterer til SJ-numre, ikke landsnumre, hvor der er et tilsvarende problem med manglende landsnummer - her er der dog vist ikke noget at gøre ved det):

853016
853023
853018
853024
669501 SJ
659192 SJ
659779 SJ
853022
853019
853015
853017
674146 SJ
703855 SJ
673787 SJ
659144 SJ
3437
853020
853025
853014
659798 SJ
853021
853050
853052

**Comment by kbevers** [comment]
Skulle gerne være taget hånd om i https://github.com/Kortforsyningen/FIRE-DDL/commit/4df24f8befaa4502f19ca59c740c68c9b948e14d

Der skal bare laves en ny migration før det træder i kraft.

**Comment by busstoptaktik** [comment]
Pørfækt - og derudover er konklusionen at vi ikke udstiller punkter der ikkkkkke har et landsnummer (tilsyneladende bortset fra GL)

**Comment by busstoptaktik** [comment]
@Helle-Git se ovenfor: Ved næste migrering/migration burde disse disser være dissede :-)

Så jeg lukker denne - stadig med den overordnede konklusion at punkter uden landsnummer ikke udstilles (før vi har en ny IDENT-agnostisk udstillingsmodel)

**Comment by busstoptaktik** [comment]
> overordnede konklusion at punkter uden landsnummer ikke udstilles

Denne konklusion holdt jo så ikke.

Dogmet om at ”ethvert punkt har et landsnummer” er åbenlyst netop blot et dogme – og vi kan ikke opfinde landsnumre til punkter der ikke har det. Frands har tilsyneladende tildelt værdien ”Manglende løbenummer” til løbenummerfelter for punkter der kun har stationsnummer. Det gælder formodentlig, systemets symmetri taget i betragtning, universelt.

Så, som Kristian har sagt det i et år, og som det nu i hvert fald er tindrende tydeligt: Vi må bare ignorere dogmet om at alt har et landsnummer, og designs som UM, der går ud fra at dogmet er korrekt kommer til at leve med det i form af mindre kønne ”Manglende løbenummer”-betegnelser.

Vi kunne overveje at bruge løbenummer 99999.9999, for at få noget der kan matches som tal, men som åbenlyst ikke er et löbenummer. Men på den anden side kan der være anvendelser der er afhængige af at matche teksten "Manglende løbenummer". Så det bliver det bare, indtil vi introducerer en ny UM.
