### ISSUE TITLE
PLANFIKSPUNKTFO.ARTSKODE

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#169]
Hvordan skal denne mappes?

**Comment by kbevers** [comment]
# Fundamental punkt

Punkter hvor ATTR:fundamentalpunkt == EPSG:4258 *og* REGION:FO. Der skal gerne være fem alt i alt.

Det drejer sig om punkter med IDENT:GNSS lig med:
`FO  ARGI`, `FO  KLAK`, `FO  SORV`, `FO  TORH`, `FO  TVOR`

# Overordnet planfikspunktsnet

NET:FO10KM (dog med undtagelse af punkter med ATTR:fundamentalpunkt)

# Punkt i net af høj kvalitet

ETRS89 (EPSG:4258, EPSG:4937) koordinater hvorom der gælder, at de to følgende betingelser er opfyldt:

1) Nyeste observationer, der er indgået i beregningen af koordinates, er højst 10 år gamle, samt 
2) den estimerede spredning på X-koordinaten er højst 50 mm 

Noget i stil med

```
SELECT *
FROM koordinat k
WHERE T > trunc(SYSDATE - interval '10' year,'YEAR') -- Ti år eller nyere
        AND sx <= 50; -- spredning højst 50 mm
```

# punkter i net af lavere eller ukendt kvalitet

Øvrige ETRS89 koordinater, altså dem der endnu ikke er blevet fanget af de ovenstående kategorier OG som ikke har feltet ”Transformeret” krydset af.

# punkt i net af lav kvalitet bestemt ved få eller ingen overbestemmelse

Udelades. Der er ikke noget nævneværdig forskel mellem denne og "punkter i net af lavere eller ukendt kvalitet"

# Punkter transformeret til gældende system

Transformerede ETRS89 koordinater.
