### ISSUE TITLE
PLANFIKSPUNKTGL.ellipsoidehoejde

### ISSUE THREAD

**Issue by Helle-Git** [Kortforsyningen/FIRE-DDL#170]
For PlanfikspunktDK er en beskrivelse ellipsoidehøjde; men den gælder vist ikke for de grønlandske

Den nuværende mapning er:
 Ellipsoidehoejde, er z-koordinaten for de få udvalgte med SRID EPSG:4937; ellers NULL

**Comment by Helle-Git** [comment]
Har forsøgt med :
Ellipsoidehoejde, er z-koordinaten for de få udvalgte med SRID EPSG:4909; ellers NULL

Det bevirkede at der kom ellipsoidehøjde på de 150 punkter med denne srid.
MEN der er stadig 3598 som mangler en en ellipsoidehøjde.

**Comment by Helle-Git** [comment]
Eksempler på punkter, hvor der mangler værdi:

ellipsoidehoejde | id_lokalid
-- | --
407 | 791566
293 | 791567
36 | 791568
13 | 791573
530 | 791587

**Comment by kbevers** [comment]
Jeg kan genfinde alle højderne i databasen men de står som en del af 3D-koordinater under EPSG:4909. Grunden til at de ikke dukker op er at disse koordinater har en registreringtil-dato.

Det er samme problem som vi har set tidligere. Det grunder i måden koordinater i REFGEO er delt på to tabeller (plan + højde). Jeg er ikke sikker på at der er så meget vi kan gøre ved det - det er en fundamental forskel i de to datamodeller der er svær at rette op på.

**Comment by busstoptaktik** [comment]
Men at så mange punkter mister deres ellipsoidehøjde tyder jo også på en bommert et eller andet sted i logikken bag enten REFGEO eller migreringskoden. Vi er nok nødt til at leve med konsekvenserne af fortidens synder.

Kan et alternativ være en småkompliceret logik, der fjerner registreringtil fra seneste 4909-koordinat for alle punkter der også har en 4747? Det skulle i så fald være ud fra en formodning om at det er bedre end alternativet (og vil i hvert fald være det i de tilfælde hvor plankoordinaterne stemmer overens).

Det har haft konsekvenser at man valgte ikke at opdatere databasen til 4D da geodæsien blev 4-dimensionel. Det er vel den triste konklusion...
