### ISSUE TITLE
Relevant bemærkning fra REFGEO mangler i FIRE 

### ISSUE THREAD

**Issue by majbrittws** [Kortforsyningen/FIRE-DDL#178]
Der overføres ikke BEM fra tabellen BSK i REFGEO, men kun BEM fra HVD_BEM-tabellen. Her fremgår dog oplysninger om hvornår punktet er oprettet i databasen og af hvem, men ikke om punktet har været besøgt undervejs og er blevet revideret. Der mistes altså historik, og info om hvordan punktet har været beskrevet tidligere, som kan være relevant ved fejlsøgning, dataudtræk og kommende revisioner af punktet. 

Nedenfor er koden til udtræk af bemærkninger.
[https://github.com/Kortforsyningen/FIRE-DDL/blob/d7358d3f1fb01f0b3cf3fa55ac236d0fbc108380/Migration/MakePunktInfoATTR.sql#L201-L215]

Eller kan man et andet sted finde de historiske beskrivelser og dertilhørende oplysninger om af hvem og hvornår et punkt er ændret?

**Comment by busstoptaktik** [comment]
Hmm - det ser ud som om ATTR:beskrivelse overføres med fuld historik, mens ATTR:bemærkning fra samme tabel kun overføres som første version. Så løsningen må være at behandle ATTR:bemærkning på samme måde som ATTR:beskrivelse. Det er formodentlig en meget lille ændring, når man først har gravet sig frem til hvor den skal indsættes

**Comment by kbevers** [comment]
> Så løsningen må være at behandle ATTR:bemærkning på samme måde som ATTR:beskrivelse.

Ja, altså de bliver jo håndteret temmelig ens de to, så det ved jeg sgu ikke om hjælper en helt masse...

https://github.com/Kortforsyningen/FIRE-DDL/blob/e07716a1512223aa53786303e5439c0fe1a13d1e/Migration/MakePunktInfoATTR.sql#L78-L92

https://github.com/Kortforsyningen/FIRE-DDL/blob/e07716a1512223aa53786303e5439c0fe1a13d1e/Migration/MakePunktInfoATTR.sql#L201-L215

Problemet er stadig at informationerne er spredt over flere tabeller på en ikke særligt praktisk måde.

**Comment by busstoptaktik** [comment]
I det ene eksempel @majbrittws og jeg kiggede på i eftermiddags ser det ud til at bemærkningen i HVD_BEM er identisk med første bemærkning i BSK, så det er ikke utænkeligt at vi får hele striben med ved at ændre  `HVD_BEM` til `BSK` i  linjerne:

https://github.com/Kortforsyningen/FIRE-DDL/blob/e07716a1512223aa53786303e5439c0fe1a13d1e/Migration/MakePunktInfoATTR.sql#L212-L213

... men som sagt: Kun et skud, baseret på tabelinspektion af et enkelt tilfælde.

**Comment by kbevers** [comment]
> ... men som sagt: Kun et skud, baseret på tabelinspektion af et enkelt tilfælde.

Det ser ud til at være et pletskud. Herunder udtræk for det samme punkt med henholdsvis `HVD_BEM` og `BSK`:

```
06-09-22			344	[2006-09-22 07:39] U.K.				15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaba833-99ab-4b13-bca7-7ae4c17a456d
```

```
80-01-01	08-11-06	344	[1980-01-01 00:00] 				15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
08-11-06	14-11-23	344	[2008-11-06 11:14] Rev. uge 17 2008. U.K.	15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
14-11-23			344	[2014-11-23 13:00] Rev. uge 45 2014 BD/JW.	15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
```

Så det tror jeg da bare vi skal køre videre med. Godt set!

**Comment by busstoptaktik** [comment]
> Så det tror jeg da bare vi skal køre videre med. Godt set!

Hm - men det ser da ud til at  HVD_BEM-teksten mangler i BSK i dette tilfælde. Det var ikke tilfældet for det punkt vi kiggede på i går. TIlsyneladende et tilfælde af REFGEOinkonsistens. Alternativ løsning kunne være at operere med både `ATTR:hovedbemærkning` og `ATTR:bemærkning` (eller `ATTR:bemærkningshistorik`), for at være sikker på at få det hele med. Så er alt materiale med og vi kan foretage en besværlig merge med datoopdateringer når FIRE bliver til FEM om SEKS år, eller deromkring.

**Comment by kbevers** [comment]
Nu kom jeg lige til at nærstudere indholdet af de to udtræk ovenfor. Det var dårlige eksempler da jeg fik valgt data fra to forskellige punkter. Udtrækkene herunder hører til samme punkt. Det tyder på at første bemærkning er lagt i `HVD_BEM` og de efterfølgende i `BSK`, hvilket betyder at den løsning jeg netop har committet misser første bemærkning. Det er vist ikke helt godt nok...

```
97-03-20			344	[1997-03-20 16:12] Uffe   Sagsnr.: ?  Ini.: ?	15101d43-ac91-4c7c-9e58-c7a0b5367910	ac36cd5c-b589-4e4a-afbd-4704c73052fa
```

```
98-07-02	03-12-01	344	[1998-07-02 13:32] Nyetab. uge 13 1997. U.K.	15101d43-ac91-4c7c-9e58-c7a0b5367910	ac36cd5c-b589-4e4a-afbd-4704c73052fa
03-12-01	08-10-22	344	[2003-12-01 16:11] rev. uge 17 2003. U.K.	15101d43-ac91-4c7c-9e58-c7a0b5367910	ac36cd5c-b589-4e4a-afbd-4704c73052fa
08-10-22	16-04-19	344	[2008-10-22 16:29] Rev. uge 17 2008. J.G./J.P.	15101d43-ac91-4c7c-9e58-c7a0b5367910	ac36cd5c-b589-4e4a-afbd-4704c73052fa
16-04-19			344	[2016-04-19 19:35] Rev. uge 15 2016. RA.	15101d43-ac91-4c7c-9e58-c7a0b5367910	ac36cd5c-b589-4e4a-afbd-4704c73052fa
```

**Comment by kbevers** [comment]
> TIlsyneladende et tilfælde af REFGEOinkonsistens

Ja, det ser sådan ud. Der findes punkter der ikke har noget i `HVD_BEM` men flere indgange i `BSK` og omvendt. En mulig løsning er at lave en union på de to taller. Jeg prøver mig lidt frem og ser om det giver mere mening. Dog lidt svært at teste da det er ren stikprøvekontrol...

**Comment by kbevers** [comment]
Jeg *tror* den her udgave virker efter hensigten:

```sql
SELECT
    bf.IN_DATE AS REGISTRERINGFRA,
    bt.IN_DATE AS REGISTRERINGTIL,
    (SELECT INFOTYPEID FROM PUNKTINFOTYPE WHERE INFOTYPE = 'ATTR:bemærkning' AND ROWNUM <= 1) AS INFOTYPEID,
     '[' || TO_CHAR(bf.IN_DATE, 'YYYY-MM-DD HH24:MI') || '] ' || bf.BEM AS TEKST,
    '15101d43-ac91-4c7c-9e58-c7a0b5367910' AS SAGSEVENTFRAID,
    conv.ID AS PUNKTID
FROM PUNKT p
INNER JOIN CONV_PUNKT conv ON p.ID = conv.ID
INNER JOIN (SELECT refnr, 0 as versnr, bem, in_date FROM hvd_bem@refgeo UNION SELECT refnr, versnr, nvl(trim(bem), 'Punkt oprettet'), in_date FROM bsk@refgeo) bf ON bf.REFNR = conv.REFNR
LEFT JOIN  (SELECT refnr, 0 as versnr, bem, in_date FROM hvd_bem@refgeo UNION SELECT refnr, versnr, nvl(trim(bem), 'Punkt oprettet'), in_date FROM bsk@refgeo) bt ON bf.REFNR = bt.REFNR AND (bf.VERSNR+1) = bt.VERSNR
WHERE bf.IN_DATE < bt.IN_DATE OR bt.IN_DATE IS NULL
```

Bemærk `nvl(trim(bem), 'Punkt oprettet')`-delen i udtræk fra `BSK`-tabellen. Indført for at undgå tomme bemærkninger, da der i en del tilfælde ikke står noget i `bem` i første version. Uden det lille hack får vi udtræk i stil med:

```
80-01-01	08-11-06	344	[1980-01-01 00:00] 				15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
08-11-06	14-11-23	344	[2008-11-06 11:14] Rev. uge 17 2008. U.K.	15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
14-11-23	14-11-23	344	[2014-11-23 11:35] Rev. uge 17 2008. U.K.	15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
14-11-23			344	[2014-11-23 13:00] Rev. uge 45 2014 BD/JW.	15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
```

Som så bliver mere fuldstændigt med det lille hack indført:

```
80-01-01	08-11-06	344	[1980-01-01 00:00] Punkt oprettet		15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
08-11-06	14-11-23	344	[2008-11-06 11:14] Rev. uge 17 2008. U.K.	15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
14-11-23	14-11-23	344	[2014-11-23 11:35] Rev. uge 17 2008. U.K.	15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
14-11-23			344	[2014-11-23 13:00] Rev. uge 45 2014 BD/JW.	15101d43-ac91-4c7c-9e58-c7a0b5367910	aaaac825-92fb-46e3-bfb4-cbb00b157025
```

**Comment by kbevers** [comment]
Et yderligere spørgsmål: Har vi overhovedet brug for `[2014-11-23 13:00]` delen af bemærkningerne? Tidspunktet er logget i registreringfra og kan lige så godt hives der fra.

**Comment by busstoptaktik** [comment]
> Har vi overhovedet brug for [2014-11-23 13:00] delen af bemærkningerne? Tidspunktet er logget i registreringfra og kan lige så godt hives der fra.

@majbrittws - det er vist dig, der kan svare på dette?

**Comment by busstoptaktik** [comment]
... men i øvrigt ser det blæret ud :-)

**Comment by kbevers** [comment]
> det er vist dig, der kan svare på dette?

Det kan nu også være dig @busstoptaktik. Eller mig selv for den sags skyld. Langt hen ad vejen handler det jo om hvordan vi præsenterer den her information i `fire info punkt`. Lige nu kommer de ud sådan her:

```
ATTR:bemærkning             [2019-01-08 08:38] Permanent GNSS station i Skejby, nho 2019
```

men hvis der fremadrettet skal fremgå flere  `ATTR:bemærkninger`'er under samme punkt, så skal de måske istedet skrives ud lidt i stil med en tidsserie, eksempelvis:

```
[2019-01-08 08:38] ATTR:bemærkning              Permanent GNSS station i Skejby, nho 2019
[2020-01-08 08:38] ATTR:bemærkning              Permanent GNSS station i Skejby, nho 2020
[2021-01-08 08:38] ATTR:bemærkning              Permanent GNSS station i Skejby, nho 2021
```

Det kan sikkert også gøres på anden vis, men der er måske en principiel overvejelse at gøre sig her? Skal andre punktinfo der er blevet opdateret også vises frem?

**Comment by busstoptaktik** [comment]
> Det kan nu også være dig @busstoptaktik. Eller mig selv for den sags skyld

Jo - mit bud ville være at fjerne tidsstemplet og, som du viser ovenfor, tilføje registreringfra til attributlinjer med historik. Men @majbrittws har en real-life use-case (som det jo hedder på nynorsk), så jeg tænkte at hun måske havde en mere velfunderet holdning.

Min holdning er at tidsstemplet i registreringen skal væk. Det er en overflødig pleonastisk dobbeltkonfekt, som Kristian K ynder at trykke det ud.

**Comment by majbrittws** [comment]
Enig med jer to; Tidsstemplet er ikke relevant.
