### ISSUE TITLE
Clarify OBSERVATIONTYPE.SIGTEPUNKTID

### ISSUE THREAD

**Issue by bjornharrtell** [Kortforsyningen/FIRE-DDL#18]
Naming and type defined as VARCHAR2(32) looks like a GUID key but it appears it should be 'true' or 'false' according to comment, test data and constraint. I think it should not use the naming convention for keys and should use VARCHAR2(5) as other booleans.

Definition:
https://github.com/Kortforsyningen/FIRE-DDL/blob/eaa66de58d4e7a342e1e6677ab5e2eb17f33a172/DDL.sql#L92

**Comment by kbevers** [comment]
You are correct. Functionally I guess it doesn't matter if it is VARCHAR(36) or VARCHAR(5) but I agree that it will be clearer what is meant if a VARCHAR(5) is used.

**Comment by bjornharrtell** [comment]
I think the name is even more important to fix, having an ID suffix on something that is not an ID is no good.

**Comment by kbevers** [comment]
Agreed. It should be renamed to simply `SIGTEPUNKT`.
