### ISSUE TITLE
Migrering til udstillingsmodel fejler når der er samtidigt gældende GL EPSG:4747 og EPSG:4909 koordinater 

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#183]
`EPSG:4747` (SRIDID 26) er GR96 geografisk, `EPSG:4909` (SRIDID 27) er GR96 geografisk + ellipsoidehøjde.

Vi kan have gældende koordinater i begge systemer, men mappingen til udstillingsmodellen fejler hvis dette er tilfældet. Mappingen søger efter gældende koordinater fra både 4747 og 4909, og forventer at finde højst 1.

Dette bør rettes til at søge efter gældende koordinater fra både 4747 og 4909, og vælge den med yngste `registreringfra` (og i tilfælde af samtidige: vælg 4909).

*Hvorfor ikke yngste tidskoordinat?* Fordi vi stadig efterfølgende kan få reprocesserede data, som giver os mere troværdige, men ældre, 4949 koordinater, til erstatning for gældende 4747'er.

SÅ i kort form:

- Søg efter gældende koordinater fra både 4747 og 4909
- Hvis kun en findes: Vælg den
- Hvis begge findes: Vælg den med yngst `registreringfra`
- Hvis begge findes og `registreringfra` er ens: Vælg 4909

@kbevers - har du yderligere til dette?

**Comment by kbevers** [comment]
> @kbevers - har du yderligere til dette?

Lyder fornuftigt

**Comment by busstoptaktik** [comment]
Ordnet af @Helle-Git
