### ISSUE TITLE
The combination of DDL.sql and test data FIRE_ADM.PUNKT.sql cause constraint violation

### ISSUE THREAD

**Issue by bjornharrtell** [Kortforsyningen/FIRE-DDL#24]
It appears that it has duplicate IDs (guids), specifically `7C1AA93A-CB66-4643-E053-1A041EAC5880`.

Update: ^^ is not correct but for some reason I get the constraint violation anyway

**Comment by nikolajkamstrup** [comment]
Can you explain in more details. To me it seems like the punkt.sql only contains one ID with the value you have mentioned.

**Comment by bjornharrtell** [comment]
You are right, I didn't look at it right and I see you have "incremental" guids.  But I do get the constraint violation as follows:

```
Insert into PUNKT
*
ERROR at line 1:
ORA-00001: unique constraint (FIRE.PUNKT_R01) violated
```

Trying to establish why...

**Comment by nikolajkamstrup** [comment]
Kan det skyldes at du forsøger at loade nye data uden at have slettet de gamle?

**Comment by bjornharrtell** [comment]
Should not be possible, this is from a CI env where I create the db from scratch on each run.

**Comment by nikolajkamstrup** [comment]
I see. How do you come around the issue with Oracle not allowing you to insert the objectid?

**Comment by busstoptaktik** [comment]
@nikolajkamstrup see #23 - The objectids are removed with a small AWK script

**Comment by bjornharrtell** [comment]
I've verified by other means that ID is unique in the FIRE_ADM.PUNKT.sql so I'm at a loss why I get the constraint violation.

**Comment by bjornharrtell** [comment]
Found it... the current DDL.sql inserts a point with the same GUID as in the test data:

https://github.com/Kortforsyningen/FIRE-DDL/blob/3f5e6f1d788036848f98cd4d9720d7da29066e81/DDL.sql#L974-L975

**Comment by kbevers** [comment]
Where is this best fixed? In the DDL og the datadump?

**Comment by bjornharrtell** [comment]
I think the DDL should not insert anything else but enumerations (also the migration SAG, it seems more appropriate that the migration scripts do that).

**Comment by kbevers** [comment]
@PeterWestNielsen Can we move the inserts of the null-observation and everything related to SAG/SAGSEVENT to a separate file to make this run more smoothly? So basically this part of the DDL:

https://github.com/Kortforsyningen/FIRE-DDL/blob/3f5e6f1d788036848f98cd4d9720d7da29066e81/DDL.sql#L960-L1031

**Comment by kbevers** [comment]
The DDL is updated in https://github.com/Kortforsyningen/FIRE-DDL/commit/a6b9803176d09c79c8ce622e16e1b70004e9c669

This includes a new file where data inserts are handled. I assume this enough to close this issue?

**Comment by bjornharrtell** [comment]
Looks good to me. :+1:
