### ISSUE TITLE
Test data missing GEOMETRI for GEOMETRIOBJEKT

### ISSUE THREAD

**Issue by bjornharrtell** [Kortforsyningen/FIRE-DDL#27]
Current schema is:
https://github.com/Kortforsyningen/FIRE-DDL/blob/3f5e6f1d788036848f98cd4d9720d7da29066e81/DDL.sql#L30-L38

Test data does not have values for not null column GEOMETRI. This table should probably be populated via some other means based on existing KOORDINAT data?

**Comment by nikolajkamstrup** [comment]
You're right. The geometry is in the table so perhaps the export function does not support geometries. I'll look into it.

**Comment by nikolajkamstrup** [comment]
Pushed a new GEOMETRIOBJEKT.sql

**Comment by busstoptaktik** [comment]
> Pushed a new GEOMETRIOBJEKT.sql

For whatever reason, the new file seems to have a double byte order mark. Don't know if this is a problem for sqlplus, but wanted to jot it down here just in case
