### ISSUE TITLE
Testpunktudtræk til QC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#28]
Vi skal bruge et mindre antal testpunkter der rammer bredt og kan bruges til delvis validering af migreringsarbejdet.

Vi skal ramme lidt af hvert:

* 5D-punkter
* DVR90 definerende punkter
* CORS
* En Jessenpunktgruppe
* Noget GL
* Noget FO
* Et par alm detailpunkter
* En vandstandsmåler

### Detailregistreringer for et mindre antal punkter

- [ ] @busstoptaktik   piller nogle FO & GL punkter ud (evt. i samråd med MEWEB)
- [ ] ASMEI klarer DK - primært på basis af Vestkystnivellementet (hvad hedder Aslak på GitHub?).
- [ ] ASMEI koster rundt med studenter hvis vi tror det kan gøre det lettere at foretage udtrækkene fra REFGEO

### Statistik

- [ ] Lars Hole klarer udtrækkene fra FIRE
- [x] @nikolajkamstrup leverer SQLlerter til FIREudtrækkene + regnearket med den överördnede statistik.

**Comment by nikolajkamstrup** [comment]
SQL for QC, see  #32
