### ISSUE TITLE
Huskeseddel

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#30]
### Pints
Her lægges pinde der er for små til eget issue (herunder typiske PL-opgaver)

### Næste workshop (2018-12-10)

Dagsordenen er primært opfølgning på de prioriterede opgaver fra sidste uge.

Dernæst koordinering mht. Septimas arbejde.

### Sidste workshop (2018-12-04)

Prioriterne var, let opdateret og parafraseret:

- Opretning af koordinatversioner, så migrering kan glide i smør
- QC: Sample SQL til QC-udtræk
- Beregningstabel: Clustering af koordinater og oprettelse af et sagsevent pr datocluster. Metadata til events hentes i JSNR_BER)

- “Drift” - Datadump til videre brug af bl.a. Septima

- Observationer klumpes på samme måde som koordinater (dog baseret på IN_DATE) - med eller uden metadata fra JSNE_OBS

- Observationer: SDFE fjerner totalvarians fra alle observationstyper
KREVE klarer skitser asap.

**Comment by kbevers** [comment]
Så vidt jeg kan se er alt på denne liste udført eller irellevant.
