### ISSUE TITLE
Koordinatversionsrevision

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#31]
De ubehagelige tildatototalnedbrud forekommer når der er huller i versionsnummereringen for en koordinat.

@nikolajkamstrup udtænker og implementerer en renummerering (er der nogen der kan huske RENUM-kommandoen fra ældre tiders BASIC- og COMAL-fortolkere?), så det hele kan glide i smør og banan.

**Comment by nikolajkamstrup** [comment]
Implemented - see #41
