### ISSUE TITLE
SQL to populate ObservationType is not in sync with current DDL

### ISSUE THREAD

**Issue by nikolajkamstrup** [Kortforsyningen/FIRE-DDL#34]
I think you need to update the sql that populates the ObservationType table. It seems like it is 3 weeks old and no longer aligned with current DDL.

**Comment by nikolajkamstrup** [comment]
Hmm the file is not in sync but the population of the table is now a part of the DDL. I thought we had removed the population of tables from the DDL

**Comment by kbevers** [comment]
Information that is static, such as ObservationType and EventType, is inserted with the DDL. Information relating to Sag and SagsEvent is inserted with `insertFIRERows.sql`.

I'll remove 'observationtype_insert.sql' right away so confusion is avoided.

**Comment by nikolajkamstrup** [comment]
Super
