### ISSUE TITLE
Sagseventtyper

### ISSUE THREAD

**Issue by AsgerPetersen** [Kortforsyningen/FIRE-DDL#40]
Er der ikke et logisk problem i eventtyperne `observation_nedlagt` og `koordinat_nedlagt`?

Handlingen i denne forbindelse er vel at opdatere `registrering_til` til sysdate? Skal observationens eller koordinatens reference til det oprindelige sagsevent samtidig skiftes ud med en ny sagsevent af denne type? Det virker ikke helt rigtigt.

**Comment by kbevers** [comment]
Thomas og jeg har lige vendt problemstillingen og har mindet hinanden om at vi på et tidspunkt har diskuteret dette. Det er korrekt at det logisk ser forkert ud. Vi har indført nedlagt/fjernet eventtyperne for at kunne registrere den slags hændelser på sagen. Det får vi svært ved uden disse events. En mulig løsning er, at oprette en ny række når noget nedlægges eller fjernes og giver den et nyt sagsevent. Fx for en koordinat:

```
ID		|		eventtype	|	regfra		|	regtil		| ...
------------------------------------------------------------------
1		|	Koord_indsat	|	2015-01-01	|	2018-12-11	| ...
1		|	Koord_nedlagt	|	2018-12-11	| 	2018-12-11	| ...
```

Så en nedlæggelse medfører altså at

1) Den aktuelle koordinat får sat regtil=sysdate
2) En ny række indsætte med en nedlæggelses-eventtype og regtil=regfra=regtil på den foregående række.

Det sidste bryder muligvis en constraint men i så fald kan vi ændre et `<` til `<=`.

Er det en brugbar løsning? Der er meget muligt noget vi har overset...

**Comment by AsgerPetersen** [comment]
Ja, det er en mulig løsning. Vi bruger denne metode i GeoDanmark til at holde historik på sletninger. I GeoDanmark lader vi databasen om at håndtere det, så vi er stensikre på, at data ikke kan blive inkonsistente. I FIRE er det en lille smule mere kompliceret fordi der også er en eventtype inde over.

Hvor foretrækker I, at det implementeres her?

**Comment by kbevers** [comment]
Umiddelbart lyder det som det rigtige at lade databasen klare det, men jeg kan ikke lige forestille mig hvordan det skal gøres. Man vil jo typisk knytte en kommentar til sådan en sletning (som ender i SAGSEVENTINFO.BESKRIVELSE), den skal der i så fald være en mekanisme til at indsætte. Er det mon muligt at få databasen til at håndtere det? Hvis ikke så er det vel en API opgave.

**Comment by B027987** [comment]
Lad os lige tage en sludder om den endelige løsning. 
Skal vi på dataasesiden bare lave et QA-check (validate constraint) når API'et nedlægger en observation/punkt. ELLER skal basen lavenedlæggelses-rækken via en after-update-trigger ?

Det mest simple/sikre er nok at lade API'er indsætte og bare lade basen validere eller hvad syntes i?

**Comment by AsgerPetersen** [comment]
Tjah, jeg er blevet en lille smule skeptisk over for modellen, som den er lige nu.

Hvordan er det, at man med sikkerhed ved, hvilken record en slette-record vedrører? For koordinater må det være noget med at srid og punktid er identiske og at recordens registreringtil er identisk med sletterecordens registreringfra (og registreringtil).

Men hvad nu, hvis der findes en sletterecord (registreringtil == registreringfra), men vi ikke kan finde en matchende record? Hvordan skal sletterecorden så fortolkes (og ER det en sletterecord)?

Sletterecord-modellen fungerer efter min mening bedre, når der findes et gennemgående objektId, som identificerer samme objekt på tværs af dets versioner. På den måde hersker der ikke tvivl feks i GeoDanmark om hvilket objekt en sletterekord vedrører.

Rent praktisk bliver det lidt spændende at implementere feks tidslinier, hvor slettede records vel skal sorteres fra.

Vi kan nok godt sno os igennem, men det virker en anelse hacky.

**Comment by busstoptaktik** [comment]
> Tjah, jeg er blevet en lille smule skeptisk over for modellen, som den er lige nu.

@AsgerPetersen, ser du en oplagt løsning som man kunne implementere fx i forbindelse med at man (hypotetisk, naturligvis :-)) tog fat på fremmednøgleproblematikken i #17?

@kbevers  tænker grundigt i skrivende stund...

**Comment by kbevers** [comment]
Den oplagte løsning er vi vist langt forbi. Jeg har også været omkring Asgers løsning 1, men synes i virkeligheden ikke det er bedre end den løsning jeg beskrev midt i december. Jeg kan godt se fidusen i løsning 2 men jeg er ikke begejstret for at udvide modellen på den måde.

En tredje løsning kunne være at gå lidt på kompromis med kravet om at der aldrig slettes/ændres noget i eksisterende rækker. Hvis man ved sletning af en koordinat sætter regtil samt indsætter et nyt sagseventid, der peger på et sletningssagsevent som refererer til den sag koordinaten oprindeligt er skabt under. Så får vi registreret hvorfor en koordinat er slettet samtidigt med at historikken bibeholdes, da det oprindelige sagsevent jo stadig eksisterer (dog uden reference fra denne specifikke koordinat). Fordelen her er at der ikke kommer til at opstå flere udgaver af den samme koordinat (som ikke har et fælles id),historikken bevares og modellen ændres ikke. Ulempen er at der brydes med princippet om ikke at ændre/slette information fra databasen. 
Denne tilgang vil naturligvis kræve nogle ændringer på constraints. Jeg kan ikke lige overskue om der er nogle eksisterende constrains som vil gøre det umuligt i praksis.

En fjerde løsning er at gå med fremgangsmåden jeg beskrev midt i december og sno os igennem udfordringerne og acceptere at det er en anelse hacky.
