### ISSUE TITLE
Status på migration af udstillingsmodel

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#58]
Overblik over migreringen af udstillingsmodellens backend fra REFGEO til FIRE.

# PLANFIKSPUNKTDK

Generelt - bl.a. om hvordan punkterne identificeres (#96)
## Felter der ikke findes i HOEJDEFIKSPUNKTDK

- [x] DK10KMNET (#85)
- [ ] ELLIPSOIDEHOEJDE (#86)
- [x] GPSEGNET (#87)
- [ ] KLASSE (#88)
- [x] REFDK (#89)

## Sidetabeller

- [ ] PLANFIKSPUNKTDK_FOTO
- [ ] PLANFIKSPUNKTDK_PLANDESC
- [ ] PLANFIKSPUNKTDK_PUNKTDESC
- [ ] PLANFIKSPUNKTDK_SPECIALNR

### Faglige felter

- [x] REGISTRERINGFRA (#61)
- [x] REGISTRERINGTIL (#62)
- [x] STATUS
- [ ] FIKSPUNKTSNUMMER (#63)
- [x] KOTE (#101)
- [x] KOTEREFERENCEVERSION (#64)
- [x] MAALEMETODE (#65)
- [x] MAALEAAR (#98, se også #66)
- [x] FIKSPUNKTSBESKRIVELSE (#67)
- [ ] ARTSKODE (#122)
- [ ] MVSTATUS (#69)
- [x] MIDDELFEJL (#70)
- [x] AFMAERKNINGSBESKRIVELSE (#71)
- [ ] TEKSTBESKRIVELSE (#72)
- [ ] MAALSKITSE (#73)
- [x] HERREDSOGN_HERREDSNUMMER (#74)
- [x] HERREDSOGN_KOEBSTADNUMMER (#75)
- [x] HERREDSOGN_SOGNENUMMER (#76)
- [ ] LOEBENUMMER (#77)
- [x] NORTHING (#78)
- [x] EASTING (#79)
- [ ] KOTEKLASSE (#80)

### Administrative felter

- [x] DATO_OPRETTET (#83)
- [x] DATO_NEDLAGT
- [x] GMLID (#82)
- [x] ID_NAMESPACE
- [x] ID_LOKALID
- [x] FORRETNINGSPROCES
- [x] FORRETNINGSHAENDELSE
- [x] REGISTRERINGSAKTOER
- [x] FORRETNINGSOMRAADE
- [x] KOMMUNEKODE (#81)
- [x] OBJECTID
- [x] VIRKNINGFRA (#59)
- [x] VIRKNINGTIL (#60)
- [x] VIRKNINGSAKTOER

# HOEJDEFIKSPUNKTDK

- [x] OBJECTID
- [x] ID_NAMESPACE
- [x] ID_LOKALID
- [x] VIRKNINGFRA (#59)
- [x] VIRKNINGTIL (#60)
- [x] VIRKNINGSAKTOER
- [x] FORRETNINGSHAENDELSE
- [x] REGISTRERINGFRA (#61)
- [x] REGISTRERINGTIL (#62)
- [x] REGISTRERINGSAKTOER
- [x] FORRETNINGSOMRAADE
- [x] STATUS
- [x] FORRETNINGSPROCES
- [ ] FIKSPUNKTSNUMMER (#63)
- [x] KOTE
- [x] KOTEREFERENCEVERSION (#64)
- [x] MAALEMETODE (#65)
- [ ] MAALEAAR (#66)
- [x] FIKSPUNKTSBESKRIVELSE (#67)
- [ ] ARTSKODE (#68)
- [ ] MVSTATUS (#69)
- [x] MIDDELFEJL (#70)
- [ ] AFMAERKNINGSBESKRIVELSE (#71)
- [ ] TEKSTBESKRIVELSE (#72)
- [ ] MAALSKITSE (#73)
- [x] HERREDSOGN_HERREDSNUMMER (#74)
- [x] HERREDSOGN_KOEBSTADNUMMER (#75)
- [x] HERREDSOGN_SOGNENUMMER (#76)
- [ ] LOEBENUMMER (#77)
- [x] NORTHING (#78)
- [x] EASTING (#79)
- [ ] KOTEKLASSE (#80)
- [x] KOMMUNEKODE (#81)
- [x] GMLID (#82)
- [x] DATO_OPRETTET (#83)
- [x] DATO_NEDLAGT

**Comment by Helle-Git** [comment]
Punkter til denne tabel udvælges (pt) således:
punktet har koordinat-sridid = 8 (~ DVR90)  OG
punktet har punktinfo region:DK eller 'region:SJ'  (361 eller 365) OG
det er aktuelt gældende (registreringtil er NULL) data 

Der indsættes  faste værdier i disse felter:
ID_NAMESPACE  'http://data.gov.dk/fikspunkt'
VIRKNINGSAKTOER  'fikspunktmyndigheden'
FORRETNINGSHAENDELSE  ' ikke angivet'
REGISTRERINGSAKTOER  'fikspunktmyndigheden'
FORRETNINGSOMRAADE  ' 52.20.15.05'
STATUS  'gældende'
FORRETNINGSPROCES 'behandlet i fikspunktsregisteret'

**Comment by kbevers** [comment]
@Helle-Git vil du ikke lukke issues i takt med at du får dem på plads i din migreringskode? Så kan vi bedre holde styr på hvor meget der mangler.

**Comment by Helle-Git** [comment]
Jeg forventer at I står for at lave beskrivelse af hvordan de enkelte felter skal udfyldes; 
Der er pt. lavet et mapnings-test setup - ikke den egentlige migreringskode.
Mapningen skal være på plads.

**Comment by kbevers** [comment]
> Jeg forventer at I står for at lave beskrivelse af hvordan de enkelte felter skal udfyldes;

Når jeg kigger på listen af felter så er der er en del af dem der falder ind und kategorien "lige ud af landevejen", men det gør de angiveligt ikke alle sammen for dig. Det er en stor hjælp hvis du siger hvilke du sidder fast ved, så prøver jeg at svare så godt jeg kan.

> Der er pt. lavet et mapnings-test setup - ikke den egentlige migreringskode.

Så erstat 'migreringskode' ovenfor med 'mapning'. Jeg forsøger på at få et overblik over hvilke felter vi ved hvordan skal overføres fra FIRE til udstillingsmodellen. Da vi ikke ser noget SQL her er det den eneste måde vi kan følge med. Hvis der er en bedre måde at skabe et overblik er jeg åben for forslag.

**Comment by Helle-Git** [comment]
Udtræk af danske højdefikspunkter.
På møde 31.10 blev det ønsket at der set bort fra transformerede koordinater for ALLE tabeller.

Der er nu kørt udtræk af alle danske højdefikspunkter, og der er 71644 (hvoraf de 339 skal ignoreres, p.gr.a itilstrækkelige data) - i UM er der pt. 103749 punkter.

Det lyder af ALT for få; mon ikke de transformerede alligevel skal med?
Den bruges jo bl.a. til at bestemme om punktet har ARTSKODE 'punkter transformeret til gældende system',

**Comment by busstoptaktik** [comment]
> Det lyder af ALT for få; mon ikke de transformerede alligevel skal med? Den bruges jo bl.a. til at bestemme om punktet har ARTSKODE 'punkter transformeret til gældende system'

Her er vi igen ude i problemet mellem punkt og koordinat: i UM betyder ordet "punkt" koordinat. I FIRE betyder punkt punkt - altså et fysisk veldefineret sted, der kan genfindes, i princippet uden kendskab til dets eksakte koordinat, og genindmåles.

Så i UM handler ARTSKODE om en koordinat (selv om vi kalder det et punkt), og hvis koordinaten ikke udstilles længere, så er det kun begrænset hvad vi behøver at vide om den :-)

Det sagt, så vil eliminering af en tredjedel af de udstillede koter nok vise sig at være et alvorligt problem de steder hvor man ikke har sørget for vedligeholdelse af de kommunale detailnet - den skal nok lige vendes endnu engang på højeste sted.

Men de transformerede koter er jo altså ikke meget bedre end hvis vi bare henviste til DNN-tabellen. Så spørgsmålet er også delvist en sag om hvor tydeligt vi skal gøre en bruger opmærksom på at vedkommende bygger videre på aldrende grundlag...

Jeg vender den med Søren

**Comment by busstoptaktik** [comment]
Ja - problemet er at der er kommuner som ikke får renoveret deres detailnet, så de forfalder bare. Derfor vil det være hele kommuner der forsvinder fra DVR90-tabellen hvis vi lader de transformerede koter ryge ud, Jeg har snakket med Søren om det og ind til videre er vi nok nødt til at lade DNN-koter transformeret til DVR90 blive, og nøjes med at stritte dem ud som er transformeret den modsatte vej

**Comment by Helle-Git** [comment]
Hvad er konklusionen?, at der alligevel ikke skal ses bort fra de transformerede  - og gælder det for ALLE typer af punkter (Højde-/plan-, danske/DNN/FO/GL?, sys34 )?

**Comment by busstoptaktik** [comment]
DVR90-koter (dvs. dem i HOEJDEFIKSPUNKTDK) skal tages med uagtet om de er transformerede.

Hvis der er DNN-koter som er transformerede skal de *ikke* tages med, men det vil være rart at få et tal på hvor mange transformerede DNN-koter der pt er i UM.

Situationen er parallel mht. System34 vs. PlanfikspunktDK: Vi udstiller transformerede punkter i PlanfikspunktDK, og igen vil det være rart at få et tal på hvor mange transformerede koordinater der findes ovre i System34-tabellen.

I FO og GL er vi nok nødt til  at tage transformerede koordinater med, og igen ville det være rart med en oversigt over hvor mange der er i UM.

Så det mest generelle jeg kan sige er at det ville være lækkert med en **optælling over "antal punkter og antal transformerede punkter"** i hver af de otte tabeller i UM.

og opsummerende:

FO/GL: alt med.

DK:  alt med i PlanfikspunktDK og HoejdefikspunktDK.
DK: Transformerede punkter udelades fra DNN og System34 tabellerne.

**Comment by Helle-Git** [comment]
Fordelingen blandt de aktuelt gældende i UM er:
(om de er transformerede afgøres alene udfra artskoden)


ANTAL | ART
-- | --
497601 | FPS34
16180 | FPS34 heraf transformeret
103783 | HFPDK
32448 | HFPDK heraf transformeret
714 | HFPFO
0 | HFPFO heraf transformeret
98891 | HFPdnn
8 | HFPdnn heraf transformeret
8165 | HFPgl
6 | HFPgl heraf transformeret
504537 | PFPDK
495532 | PFPDK heraf transformeret
762 | PFPFO
0 | PFPFO heraf transformeret
9680 | PFPGL
158 | PFPGL heraf transformeret

De er udtrukket over denne 'læst':
select count(*)antal, 'PFPFO' art    -- 
from fikspunkt_l1.planfikspunktFO
where registreringtil is NULL
union
select count(*)antal, 'PFPFO heraf transformeret' art    -- 
from fikspunkt_l1.planfikspunktFO
where registreringtil is NULL
and   artskode  like '%trans%'

**Comment by busstoptaktik** [comment]
Lukker denne: Den erstattes af 8 tabelvise issues samlet under project 2
