### ISSUE TITLE
DDL SQL to populate ObservationType is incorrect 

### ISSUE THREAD

**Issue by nikolajkamstrup** [Kortforsyningen/FIRE-DDL#6]
The columns sigtepunkt1 and 2 are of datatype varchar but INSERT INTO SQL (last part of new DDL) tries to insert booleans.

INSERT INTO observationtype (beskrivelse, observationstype, **sigtepunkt1, sigtepunkt2**, value1, value2, value3, value4, value5, value6, value7, value8, value9, value10, value11, value12, value13, value14, value15)
VALUES ('Koteforskel fra fikspunkt1 til fikspunkt2 (h2-h1) opmålt geometrisk ', 'geometrisk_koteforskel', **TRUE, FALSE**, 'Koteforskel [m]', 'Nivellementslængde [m]', 'Antal opstillinger', 'Variabel vedr. eta_1 (refraktion) [m^3]', 'Afstandsafhængig varians koteforskel pr. målt koteforskel [m^2/m]', 'Afstandsuafhængig varians koteforskel pr. målt koteforskel [m^2]', 'Total varians koteforskel [m^2]', 'Præcisionsnivellement [0,1,2,3]', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

**Comment by kbevers** [comment]
Okay, det dur jo ikke. Jeg har tilføjet en opdateret version af insert-scriptet: https://github.com/Kortforsyningen/FIRE-DDL/blob/master/observationtype_insert.sql

Desuden har jeg opdateret `DDL.sql` med de opdaterede inserts.

Peter: Du må hellere få taget en kopi af `observationtype_insert.sql` så det bliver rigtigt i næste version af DDL'en.
