### ISSUE TITLE
HOEJDEFIKSPUNKTDK.VIRKNINGTIL

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#60]
Hvilken data skal vælges?

**Comment by busstoptaktik** [comment]
Jvf. #61 og #62 er det nok snarere dags dato ved migration end noget fra FIRE? (gælder tilsvarende #59)

**Comment by Helle-Git** [comment]
Denne er NULL, da der pt kun arbejdes på aktuelle data.
 (Historik afklares senere)
