### ISSUE TITLE
HOEJDEFIKSPUNKTDK.REGISTRERINGTIL

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#62]
Hvilken værdi skal tildeles her?

I øjeblikket benyttes dags dato ved overskrivning/opdatering

**Comment by busstoptaktik** [comment]
> I øjeblikket benyttes dags dato ved overskrivning/opdatering

Jeg antager at registreringtil/fra i udstillingsmodellen har en anden betydning end i FIRE-datamodellen: I udstillingsmodellen skal vi sikre at dem der vil sagsøge os mhp. at fejlagtig information er pushet ud, de skal kunne rekonstruere hvad der stod på Valdemar den dag de tilgik den (as-of).

Derfor må det være korrekt at gøre som gjort: Dags dato (gælder tilsvarende for #61) - men jeg tror lige vi skal vende den med Lars og/eller @nikolajkamstrup inden vi definitivt lukker #61 og #62

**Comment by busstoptaktik** [comment]
@Helle-Git Jeg har checket med Lars - REGISTRERINGTIL og REGISTRERINGFRA tages fra FIREfelterne med samme navne. VIRKNINGTIL og VIRKNINGFRA dublerer disse (registreringer har øjeblikkelig virkning).

DATO_OPRETTET er dato for initialload FIRE->UM, eller, ved senere opdateringer med nyoprettede punkter, datoen for denne opdateringskørsel.

Denne kommentar har også relevans for issues #59, #60, #61, #83, som derfor lukkes sammen med denne
