### ISSUE TITLE
HOEJDEFIKSPUNKTDK.FIKSPUNKTSNUMMER

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#63]
Hvilken værdi skal tildeles her?

**Comment by Helle-Git** [comment]
Der skal være en værdi, og den skal være entydig (kun eet punkt med denne værdi).

**Comment by Helle-Git** [comment]
Undersøg punktinfo for punktet
Findes der info med IDENT:landsnr (#342)?
 Ja netop 1: Brug info fra TEKST-feltet
 Ja flere: Brug info fra TEKST-feltet for den med lavest OBJECTID.
 Nej: Findes der info med IDENT:diverse (#347)?
   Ja netop 1: Brug info fra TEKST-feltet
   Ja flere: Brug info fra TEKST-feltet for den med lavest OBJECTID.
   Nej:  ????  Der meldes fejl;

**Comment by Helle-Git** [comment]
Må der være blanktegn i FIKSPUNKTSNUMMER?
Skal de fjernes (hvis der er nogle)?

**Comment by kbevers** [comment]
> Må der være blanktegn i FIKSPUNKTSNUMMER?

Ja, det må der godt. Det er ikke særligt tilfredsstillende at der er det, men grundet dum logik i REFGEO og tilhørende programmel er det nødvendigt. Fx er fikspunktsnumre som `9904/14 496` og `GL 1049` gyldige. Vi har jo konstateret at der er nogle fejl i FIRE som det ser ud lige nu. Jeg er i gang med at løse problemet og satser på at det er i orden inden vi kører næste migrering fra REFGEO til FIRE.

> Skal de fjernes (hvis der er nogle)?

Nej. Jeg sørger for at fikspunktsnumrene (identerne) er som de skal være når de kommer ind i FIRE. Jeg laver en del datavask i forbindelse med udtræk fra REFGEO og der skulle alle overflødige mellemrum osv gerne blive fjernet.

**Comment by Helle-Git** [comment]
Jeg har ændret udvælgelses-kriterierne i de tilfælde hvor der er flere kandidater; 
Der benyttes den med HØJEST objectid  (hermed fås samme fikspunktsnumre som der pt udstilles).

**Comment by kbevers** [comment]
En opdatering til min forrige kommentar: Efter seneste migration skulle der nu kun forekomme blanktegn mellem regionskode og identen, fx `GL  TERN` eller `GL  1049`. Der kommer altid to efter hinanden. Identer som `9904/14 496` forekommer nu uden blanktegn, altså `9904/14496`.

**Comment by kbevers** [comment]
> Jeg har ændret udvælgelses-kriterierne i de tilfælde hvor der er flere kandidater;
Der benyttes den med HØJEST objectid (hermed fås samme fikspunktsnumre som der pt udstilles).

Skal det forstås sådan, at hvis der findes flere identer til et givent fikspunkt så vælger du den med højest objectid? Det virker nok med det data der findes i FIRE nu, men jeg ved ikke om det er langtidsholdbart når først egentligt produktion går i gang. Jeg vil mene at det er bedre at vælge identen i IDENT:landsnr punktinfotypen (stavemåden er fra hukommelsen, den er måske anderledes med burde være til at genkende). Det skulle gerne eksistere for alle punkter.

**Comment by Helle-Git** [comment]
Der er nu tilfælde med flere flere forekomster af IDENT:landsnr for et punkt - og det er i den situation, der vælges den forekomst med højest objectid (der skal jo vælges en af dem).
Hvis der IKKE findes en forekomst af IDENT:landsnr for punktet, benyttes den forekomst af IDENT:diverse, der har højest objectid.
Nu er der 0-4 (aktuelt gældende) forekomster af IDENT:landsnr pr punkt, og
0-6 (aktuelt forekomster) af IDENT:diverse pr punkt.

**Comment by kbevers** [comment]
> Der er nu tilfælde med flere flere forekomster af IDENT:landsnr for et punkt - og det er i den situation, der vælges den forekomst med højest objectid (der skal jo vælges en af dem).

Super. Det lyder som den rette tilgang.

> Hvis der IKKE findes en forekomst af IDENT:landsnr for punktet, benyttes den forekomst af IDENT:diverse, der har højest objectid.

Prioriteten af de forskellige typer ident bør være: IDENT:landsnr, IDENT:GI, IDENT:GNSS, IDENT:jessen, IDENT:diverse. Altså, hvis der ikke findes et landsnr så se om der er et GI-nummer. Hvis ikke, så se om der er et GNSS nummer. Og så videre. Fint at sortere på objectid hvis der er flere muligheder inden for samme identtype.

**Comment by Helle-Git** [comment]
Hvis der IKKE findes et fikspunktsnummer ud fra ovenstående algoritme, tildeles et fiktivt fikspunktsnummer.  '???-!!-'yymmdd' 'nummer   f.eks.: '???-!!-190920 0002'  
Fikspunktsnummer SKAL være udfyldt og unikt.
OBS De punkter, der mangler informationer til at danne fikspunktsnumre, vil IKKE 'beholde' deres fikspunktsnummer ved næste indlæsning.

**Comment by kbevers** [comment]
> Hvis der IKKE findes et fikspunktsnummer ud fra ovenstående algoritme, tildeles et fiktivt fikspunktsnummer. '???-!!-'yymmdd' 'nummer f.eks.: '???-!!-190920 0002'

Har du et eksempel på hvor det ikke lader sig gøre at finde et nummer ud fra den fremgangsmåde?

**Comment by kbevers** [comment]
Der er tale om fire punkter som ikke får tildelt et rigtigt ident. De fire punkter kan findes ved deres REFGEO ID: 533768, 534080, 72205 og 72206. Jeg arbejder på at finde ud af hvorfor netop de fire ikke bliver indlæst i databasen med et rigtigt ident.

**Comment by kbevers** [comment]
Jeg har ikke set nærmere på det endnu. Det er kompliceret, men der findes nok en løsning.

**Comment by kbevers** [comment]
Jeg har nu kigget nærmere på det. De fire punkter har alle MV_STATUS=-1 i REFGEO. De er altså taget ud af drift og bør slet ikke migreres til FIRE. Det er også derfor de ikke har et landsnr - mit script der genererer identer tager slet ikke de fire punkter i betragtning. 

Det er muligt at der er en fejl i migrerings-SQL'en. Det kan også tænkes at problemet går væk af sig selv ved en ny migrering. Jeg synes vi skal vente med at gøre med til vi ved om problemet forsvinder efter en ny migrering.

**Comment by Helle-Git** [comment]
Der er stadig problemer med at finde fikspunktsnummer for disse 4 REFGEO ID: 533768, 534080, 72205 og 72206.

**Comment by kbevers** [comment]
Okay, det er uheldigt. Jeg forstår ikke hvorfor de bliver overført i første omgang. Er det muligt at se bort fra dem? Jeg er klar over at det ikke er en særlig skøn løsning, men da årsagen til deres eksistens ikke er kendt kan vi ikke gøre ret meget andet.

**Comment by Helle-Git** [comment]
Der tjekkes nu i denne rækkefølge:
ident:landsnr
ident:GI   
ident:GNSS
ident:jessen
ident:ekstern 
ident:diverse

Hvis det fundne er IDENT:ekstern, tjekkes for om punktet skal ignoreres:
HVIS det er af formen  '\d+/\d+\-\d+', eller '\d+/\d+\H\d+' - ignoreres punktet
HVIS det er af formen '\d+/\d+' eller '\d+/\d+\.\d+' OG tallet foran '/' er en af disse fiktive producentnr (4078, 4110, 4500, 8025), ignoreres punktet,

**Comment by busstoptaktik** [comment]
Resten af dette issue er flyttet til #140
