### ISSUE TITLE
HOEJDEFIKSPUNKTDK.MAALEMETODE

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#65]
Hvilken værdi skal tildeles?

**Comment by Helle-Git** [comment]
Indtil videre er det altid 'terrestrisk måling'

**Comment by kbevers** [comment]
Det virker fornuftigt. Er det den eneste målemetode der findes i den nuværende udstillingsmodel?

**Comment by Helle-Git** [comment]
Der er disse mulige/anvendte værdier:
***barometrisk opmålt**          
Barometer brugt som trykhøjdemåler,
Bruges som trykhøjdemåler, fordi lufttrykket aftager regelmæssigt opad i atmosfæren. Benyttes især 
inden for luftfart, men også af bjergbestigere.

**blanding af terrestrisk måling med GPS eller fotogrammetrisk måling**
 Anvendelse af forskellige opmålingsmetoder.

**doppler opmålt**             
 Opmålt med doppler udstyr.
 Doppler effekten er navnet på den ændring i frekvens af f.eks. lyd og lys, der skyldes at observatøren bevæger sig relativt til kilden, f.eks. når en ambulance kommer kørende forbi og man hører sirenen ændre lyd. Som bekendt kan målinger af dopplerforskydningen af en frekvens udsendt fra en satellit, der enten nærmer sig til eller fjerner sig fra en jordstation, give en stedsbestemmelse af modtagestationens antenne. Med observation af ca. 40 satellitpassager kan en geodætisk nøjagtighed, dvs. 1-2 m i alle tre koordinater, opnås, når satellittens sted og bane er bedst muligt bestemt gennem de præcise ephemerider, der bliver tilgængelige få måneder efter passagen.

**fotogrammetrisk opmålt**      
Opmåling med fotogrammetri.
En metode, som i nogle tilfælde er velegnet til at udføre opmåling med er fotogrammetri. 
 Denne metode bruger ofte vha. luftfotos, som gennemgår en behandling, som gør det muligt at måle i billederne. Metoden udmærker sig ved at være særdeles hurtig, hvis de nødvendige fotos allerede eksister. Derudover er metoden anvendelig, hvor større evt. svært tilgængelige områder skal opmåles.

**GPS opmålt**                 
 Opmålt ved hjælp af GPS modtager.

**terrestrisk måling**          
Opmålt ved hjælp af traditionel landmåler udstyr f.eks teodolit, laserafstandsmåler.

**ukendt målemetode**           
Målemetoden kendes ikke.

**Comment by kbevers** [comment]
Tak. Så er "Terrestrisk måling" det korrekte valg. Det er det eneste der er overført til FIRE. Andre opmålingstyper er bevist udelagt i migrationenen.

**Comment by kbevers** [comment]
Lukket da feltets værdi er afklaret, jv ovenstående.
