### ISSUE TITLE
HOEJDEFIKSPUNKTDK.MAALEAAR

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#66]
Hvilken værdi skal tildeles? Afledes fra nyeste observation tilknyttet punktet?

**Comment by Helle-Git** [comment]
Der benyttes årstallet fra 'registreringfra'-feltet i den aktuelle række fra KOORDINAT-tabellen.

**Comment by kbevers** [comment]
Der er ikke tvivl om hvilken værdi der skal bruges. Lukket.

**Comment by kbevers** [comment]
Vi skal istedet for året for nyeste koordinat til punktet kigge på seneste observation til punktet. Det drejer sig om observationstyperne `trigonometrisk_koteforskel` og `geometrisk_koteforskel` (observationstypeid 1 og 2).

Noget i stil med:

```
SELECT MAX(EXTRACT(YEAR FROM o.registreringfra))
FROM observation o
WHERE o.observationstypeid in (1, 2) 
  AND (o.opstillingspunktid = '92BBD366-AA0F-4074-E053-1A041EACA7BF' OR o.sigtepunktid = '92BBD366-AA0F-4074-E053-1A041EACA7BF');
```

**Comment by busstoptaktik** [comment]
@Helle-Git er fremgangsmåden fra @kbevers ovenfor anvendelig?

**Comment by Helle-Git** [comment]
Den beskrevne algoritme benyttes nu; 
men det er endnu ikke set hvordan den passer.

**Comment by Helle-Git** [comment]
Den nye metode har et problem - der er ikke observationer af disse typer for ikke alle punkter.
Der er  34475, hvor måleår bliver NULL - og det må det ikke (det SKAL have en værdi).
Eksempler:
id_lokalid, punktid:
9030	92BBD366-1570-4074-E053-1A041EACA7BF
9032	92BBD366-1572-4074-E053-1A041EACA7BF
10125	92BBD366-19B7-4074-E053-1A041EACA7BF

**Comment by kbevers** [comment]
De nævnte eksempler har slet ikke nogle observationer registreret. I så fald må der faldes tilbage på nyeste ikke-transformerede koordinat. Noget i stil med:

```
SELECT MAX(EXTRACT(YEAR FROM t)) FROM koordinat WHERE transformeret = 'false' AND punktid = '92BBD366-1570-4074-E053-1A041EACA7BF';
```

**Comment by Helle-Git** [comment]
Skal det 'bare' være den nyeste, eller skal der tages højde for f.eks. SRIDID?

**Comment by kbevers** [comment]
Så vidt jeg lige kan se fra de tre eksempler er det ikke nødvendigt med SRIDID, men det er ikke utænkeligt at der er er tilfælde hvor det er nødvendigt. Hvordan ser det ud hvis prøver ud at tage højde for SRIDID? Kommer det i nærheden af det nuværende indhold?

**Comment by Helle-Git** [comment]
Jeg fandt disse eksempler, på punkter med flere  (SRIDID, år)
92BBD365-F246-4074-E053-1A041EACA7BF	(13,1979) (15,1984) (22,1979)
92BBD365-F247-4074-E053-1A041EACA7BF	(3,1998) (11,1999) (13,1979) (15,1984) (22,1979)
92BBD365-F248-4074-E053-1A041EACA7BF	(13,1979) (15,1984) (22,1979) 
92BBD365-F249-4074-E053-1A041EACA7BF	(13,1979) (15,1984) (22,1979)

Skal jeg nøjes med at se på SRIDID:22?

**Comment by Helle-Git** [comment]
Der kan tidligst komme svar på 'effekten af en ændret algortime' i næste uge - en kørsel (udtræk af alle danske højdefikspunkter) tager ca 6 timer; og vi er på kontorseminar i torsdag+fredag.

**Comment by kbevers** [comment]
> Skal jeg nøjes med at se på SRIDID:22?

For højdefikspunkter må det være 11, 12 og 13 (varianter af Dansk Normal Nul) som er de relevante. Det ser også ud til at give det korrekte resultat for dine eksempler ovenfor.

Mit SQL ovenfor kan da altså justeres til:

```
SELECT MAX(EXTRACT(YEAR FROM t))
FROM koordinat
WHERE transformeret = 'false' 
  AND sridid IN (11, 12, 13)
  AND punktid = '92BBD365-F249-4074-E053-1A041EACA7BF';
```

Forhåbentligt kan vi ud fra det finde et måleår til alle punkterne. 

> Der kan tidligst komme svar på 'effekten af en ændret algortime' i næste uge - en kørsel (udtræk af alle danske højdefikspunkter) tager ca 6 timer; og vi er på kontorseminar i torsdag+fredag.

Ingen problem. Det ser jo også ud til at du kan spore dig ind på problemer uden at lave en fuld kørsel så det er helt fint.

**Comment by Helle-Git** [comment]
Af de fikspunkter, der mangler observation-info; har de 27996 ikke nogen ikke-transformeret koorrdinat (SRIDID: 11, 12, 13) (der er gældende); og 6 af dem har ikke gældende ikke-transformerede koordinater (uanset SRIDID).
Det er altså ikke godt nok endnu.

**Comment by kbevers** [comment]
Pokkers. Har du en håndfuld eksempler på de punkter?

**Comment by Helle-Git** [comment]
Her er et tilfældigt udklup af  måleår-løse punkter, der mangler brugbare koordinat-oplysninger:
lokal_id punktid
884609	92BBD372-710C-4074-E053-1A041EACA7BF
861240	92BBD372-2E32-4074-E053-1A041EACA7BF
881861	92BBD372-6882-4074-E053-1A041EACA7BF
860346	92BBD372-2B1E-4074-E053-1A041EACA7BF
880787	92BBD372-6452-4074-E053-1A041EACA7BF
886070	92BBD372-76C1-4074-E053-1A041EACA7BF

**Comment by Helle-Git** [comment]
Jeg har set på fordelingen af aktuelle koordinat-oplysninger på sridid, for de måleår-løse punkter:
SRIDID antal
 03	49
 06	6
 07	645
 08	5933
 11	13115
 12	12832
 13	2049
 14	1
 15	2123
 16	1
 19	7
 20	2
 21	1849
 22	947
 23	2
 24	9
 29	5
 34	1
 49	2
 67	2

**Comment by kbevers** [comment]
SRIDID 7, 8 og 10 må også skulle med så. Så er alle danske kotesystemer med i puljen.

**Comment by busstoptaktik** [comment]
Jeg tillader mig at konkludere at HOEJDEFIKSPUNKT.MAALEAAR sættes til

- år for seneste observation af typen 1 el. 2
- hvis disse ikke findes: År for seneste koordinat af typen 7--13
- hvis disse ikke indgår: Punktet fejlmeldes og overføres ikke.

(i sidste tilfælde er der tale om et højdefikspunkt uden nogen højdekoordinat)
