### ISSUE TITLE
HOEJDEFIKSPUNKTDK.FIKSPUNKTSBESKRIVELSE

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#67]
Hvilken værdi skal tildeles?

**Comment by Helle-Git** [comment]
Der dannes en reference til Valdemar:

'http://valdemar.kms.dk/cgi-valdemar/valdebsktxt?rgn=DK&stn=<fikspunktsnummer uden blanke>crd=utm32Letrs89&hgt=h_dvr90&wt=2&ut=6291456&st=0'

**Comment by kbevers** [comment]
Der er noget galt med linket. Jeg bliver mødt med denne fejlbesked: "CGI-data kunne ikke læses, eller der var fejl i cgi-data"

**Comment by Helle-Git** [comment]
Nu er referencen til fikspunktsnummeret indsat.
Og  det virker nok kun for fikspunktsnumre som er kendt af Valdemar.

**Comment by kbevers** [comment]
Okay, jeg forstår nu. Her er et eksempel man bare kan klikke på uden at slå hjernen til (det er ofte den slags jeg har brug for :-)): http://valdemar.kms.dk/cgi-valdemar/valdebsktxt?rgn=DK&stn=K.K.1103&crd=utm32Letrs89&hgt=h_dvr90&wt=2&ut=6291456&st=0

**Comment by kbevers** [comment]
Lukket, da det er på plads hvordan feltet skal udfyldes.
