### ISSUE TITLE
HOEJDEFIKSPUNKTDK.ARTSKODE

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#68]
Skal formenligt afledes af information om observation og punkt

**Comment by Helle-Git** [comment]
Afledes udfra ATTR-værdi (i punktinfo for punktet), hvis den findes - søges i nævnte rækkefølge:
ATTR:GI_punkt (337) => 'plane netværk,GI fikspunkt'
ATTR:Hjælpepunkt (338) => 'plane eller højde netværk, hjælpepunkter'
ATTR:MV_punkt (336) => 'plane netværk,MV fikspunkt'
ATTR:højdefikspunkt (335) => 'højde netværk'

Uvist hvad der skal ske, hvis der ikke er en af ovenstående
?? => 'sømærker'
?? => 'teknik punkter'

**Comment by Helle-Git** [comment]
I den nuværende  UM har værdierne for Artskode denne fordeling:
76347    overordnet højdefikspunktsnet
40333    punkter transformeret til gældende system
19140    punkt i net af høj kvalitet
11719    fundamental punkt
      19    punkter i net af lavere eller ukendt kvalitet
        2    punkt i net af lav kvalitet bestemt ved få eller ingen overbestemmelse

**Comment by Helle-Git** [comment]
I følge DDL har værdierne følgende betydning:
    **fundamental punkt**     Punkt der har været med til at definere det pågældende koordinatsystem eller kotesystem.

    **overordnet højdefikspunktsnet**   
                        Højdefikspunkt der har deltaget i KMS kortbladsvise totalomregning, bestemt fra punkter i gruppe 1.

    **punkt i net af høj kvalitet**
                        Bestemt direkte fra punkter i grupperne 1 - 2 (3). 
                        Totale kommunevise beregninger, af alle kendte punkter bestemt fra punkter i grupperne 1 -2 (3).

    **punkter i net af lavere eller ukendt kvalitet**
                        Lokale net med utilstrækkelig tilslutning til overordnet net.

    **punkt i net af lav kvalitet bestemt ved få eller ingen overbestemmelse**
                        Punkter bestemt på gældende system f.eks et lokalt koordinatsystem.

    **punkter transformeret til gældende system**
                         Koordinater tranformeret til gældende system. 
                        f.eks fra lokalt system eller et ældre ikke længere brugt system.

    **punkter bestemt på ikke gældende system eller af ukendt oprindelse**
                        Koordinater hvor historien ikke kendes.

    **lokationskoordinater eller koter, også kaldet grovkoordinater**
                        Koordinater fra upræcist grundlag. f.eks digitaliseret fra topografisk kort.

**Comment by Helle-Git** [comment]
Der er forsøgt forskellige specifikationer; men de er opgivet.
SÅ det er pt. uklart hvordan der skal findes data til dette felt .

**Comment by Helle-Git** [comment]
Der undersøges for hvert punkt, indtil det er afklaret:
- Er det et fundamental punkt?
- Er det et transformeret punkt?
- Er det et overordnet højdefikspunkt?
  (Der undersøges for om infotype NET:DVR90 findes - hvis ikke gives en fejl - og der fortsættes,
  der undersøges kun for denne infotype-tilknytning til punktet, hvis infotypen en kendt)
- Er punktet i net af høj kvalitet?
Ellers er det 'net af lavere eller ukendt kvalitet'.

**Comment by busstoptaktik** [comment]
@kbevers håndgenererer NET:DVR90

**Comment by Helle-Git** [comment]
Er algortimen fælles for alle typer af fikspunkter? - eller skal der være særlige issues for artskode for andre typer af fikspunkter?

**Comment by busstoptaktik** [comment]
@Helle-Git, algoritmen er DVR90-specifik

**Comment by Helle-Git** [comment]
OK, så skal der laves særlig beskrivelse for øvrige tabellers ARTSKODE-felter.

**Comment by Helle-Git** [comment]
Der er STORE forskelle mellem punkternes ARTSKODE-værdier i FIRE og i Geobanken:

antal | UM-værdi | FIRE-værdi
-- | -- | --
1 | punkter i net af lavere eller ukendt kvalitet | punkt i net af lav kvalitet bestemt ved få eller ingen overbestemmelse
39584 | punkter i net af lavere eller ukendt kvalitet | overordnet højdefikspunktsnet
9906 | punkt i net af høj kvalitet | overordnet højdefikspunktsnet
14945 | punkter i net af lavere eller ukendt kvalitet | punkt i net af høj kvalitet
5527 | punkter i net af lavere eller ukendt kvalitet | fundamental punkt
1142 | overordnet højdefikspunktsnet | fundamental punkt

**Comment by busstoptaktik** [comment]
> OK, så skal der laves særlig beskrivelse for øvrige tabellers ARTSKODE-felter.

korrekt
