### ISSUE TITLE
HOEJDEFIKSPUNKTDK.MVSTATUS

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#69]
Skal formenligt afledes af information om observation og punkt

**Comment by Helle-Git** [comment]
Afledes udfra ATTR-værdi (i punktinfo for punktet), hvis den findes - søges i nævnte rækkefølge:
ATTR:GI_punkt (337) => 'plane netværk,GI fikspunkt'
ATTR:Hjælpepunkt (338) => 'plane eller højde netværk, hjælpepunkter'
ATTR:MV_punkt (336) => 'plane netværk,MV fikspunkt'
ATTR:højdefikspunkt (335) => 'højde netværk'

Uvist hvad der skal ske, hvis der ikke er en af ovenstående
?? => 'sømærker'
?? => 'teknik punkter'

**Comment by kbevers** [comment]
Har vi et par eksempler på punkter der i udstillingsmodellen har MVSTATUS "Sømærker" eller "teknik punkter"? 2-3 identer på hver type kunne være fint så undersøger jeg nærmere.

**Comment by busstoptaktik** [comment]
@kbevers kom vi i mål her?

**Comment by kbevers** [comment]
Nej. Vi skal muligvis løse problemet upstream og generere nye punktinfotype i migreringen: ATTR:sømærke og ATTR:teknikpunkt. Er ikke sikkert på at vi kan vride informationen ud fra hvad der ligger i FIRE nu.

**Comment by busstoptaktik** [comment]
Er rækkefølgen korrekt? I #80 benyttes argumentet "MVSTATUS < 3". Det lyder som om rækkefølgen skal være:

1. ATTR:GI_punkt (337) => 'plane netværk,GI fikspunkt'
2. ATTR:MV_punkt (336) => 'plane netværk,MV fikspunkt'
3. ATTR:højdefikspunkt (335) => 'højde netværk'
4. ATTR:Hjælpepunkt (338) => 'plane eller højde netværk, hjælpepunkter'
5. Alt andet

Kan det passe, @kbevers?

**Comment by kbevers** [comment]
Ja, det lyder plausibelt

**Comment by Helle-Git** [comment]
Er det de numeriske værdier for MVSTATUS, der står ovenfor - de værdier der henvises til ifm KOTEKLASSE?
Skal der ændres på den rækkefølge, hvori der undersøges ?
(Har kun betydning hvis samme punkt har tilknyttet flere af disse attributter på samme tid).

**Comment by kbevers** [comment]
REFGEO siger følgende om MV_STATUS:

```
Status for control point group, use for surveying, landmark ev.
 mv_status = 0 height network.
 mv_status = 1 plane network, MV control point.
 mv_status = 2 plane network, GI control point.
 mv_status = 3 plane/height network, temporary control point.
 mv_status = 4 navigation mark of any kind in plane network.
 mv_status = 5 technical landmark in plane network.
```

Det oversættes vel så til

```
VÆRDI   TEKST
---------------
0       højde netværk
1       plane netværk,MV fikspunkt
2       plane netværk,GI fikspunkt
3       plane eller højde netværk, hjælpepunkter
4       sømærker
5       teknik punkter
```

**Comment by kbevers** [comment]
> @kbevers, for mig ser det ud som om MV-status 0 betyder at punktet ud fra matrikelsynspunkt er uinteressant, så hvis hverken MV eller GI er sat kan vi vel sætte status til 0 og ignorere at det kan betyde 3-5?

Lyder fint for mig

**Comment by busstoptaktik** [comment]
@mrlarshole, denne er markeret som lukket og løst, men bare for at være helt sikker: Ovenfor skriver jeg at...

> for mig ser det ud som om MV-status 0 betyder at punktet ud fra matrikelsynspunkt er uinteressant, så hvis hverken MV eller GI er sat kan vi vel sætte status til 0 og ignorere at det kan betyde 3-5?

Jeg kan forestille mig at vi her igen støder ind i problemet med at begreberne "punkt" og "koordinat" overlapper i udstillingsmodellen. Min pointe var at koter, og dermed højdefikspunkter er ligegyldige i matrikelsammenhæng, så som koordinat betragtet kan alle koter få MVSTATUS=0.

Men hvad nu hvis det relaterede punkt er en universalkalot med både kote og plankoordinat - går Valdemar Webapp så agurk over at kotedelen får MVSTATUS=0, mens plankoordinaten og/eller S34koordinaten får MVSTATUS 1 eller 2?

**Comment by mrlarshole** [comment]
Ja højdefikspunkter er ligegyldige i matrikel sammenhænge. Og ja nogle højdefikspunkter(mv=0) er også planfikspunkter(mv=2), dit eksempel med universalkalot er relevant men også alle 3d-punkter så som skruepløkke mfl. Nogle desiderede planfikspunkter som fx tjenesternes punkter har mv=1 af hensyn til det bogstav som kom med koordinaten ud og kunne betyde fx v="vedligeholdes af styrelsen", tjenesternes punkter måtte ikke få et "v", men snarer et "g". 

Jeg mener ikke at webapplikationen benytter mv-status til noget. Jeg mener at der ved valg af plan- eller højdefikspunkt udelukkende kigges på om punktet findes i hhv. planfikspunktdk eller hoejdefikspunktdk.

der hvor mv-status betyder noget er blandt andet ved klasseinddelingen som foregår på REFGEO.

**Comment by mrlarshole** [comment]
Adskillelsen af plan og højde er jo et gammelt levn som stammer tilbage fra adskillelsen i Geodætisk institut og matrikeldirektoratet. Ved sammenlægningen var det stadig de traditionelle målemetoder der blev benyttet og derfor gav det stadig mening at adskille det. Der var ikke mange 3d afmærkningstyper.

**Comment by Helle-Git** [comment]
Der mangler at blive løst, hvordan der findes information om  hvordan værdierne 'Sømærke' og 'teknik punkter' findes.
Der er kun få af disse for danske højdefikspunkter; men dette issue refereres også fra andres tabeller, hvorfra der er flere ; f.eks. danske planfikspunkter, hvor der i UM er 6026	'teknik punkter' og 457						'sømærker'.

Tidligere skrev @kbevers at der muligvis skal nye punktinfo-typer til (ATTR:sømærke og ATTR:teknikpunkt. )

**Comment by kbevers** [comment]
> Tidligere skrev @kbevers at der muligvis skal nye punktinfo-typer til (ATTR:sømærke og ATTR:teknikpunkt. )

Ja, det er den mest elegante løsning. Sømærker findes i REFGEO med HVD_REF.MVSTATUS=4 og teknikpunkter findes med HVD_REF.MVSTATUS=5. Jeg tilpasser migreringsscript så snart jeg får tid til det.

**Comment by kbevers** [comment]
Tilføjet i https://github.com/Kortforsyningen/FIRE-DDL/commit/7aa761eb31f5fcfcc42395e61ba4bc05189c236b. Tilgængelig efter næste migration.
