### ISSUE TITLE
Population of data as part of DDL

### ISSUE THREAD

**Issue by nikolajkamstrup** [Kortforsyningen/FIRE-DDL#7]
I'll suggest that you consider whether the DDL should include SQL to populate the type tables. I think it would be more clean that the DDL only creates the structures (tables, constraints, keys etc.). Furthermore, it is only a few of the type tables that can be populated without querying REFGEO db.

**Comment by kbevers** [comment]
This was discussed on the meeting with Septima last week and the conclusion was that it preferable to include everything in one file. Table creation and constraints are kept at the top of the file, so the rest of the file can be ignored in the cases where only the database setup is needed.

Outside this repository the DDL lives in a separate file from the table inserts etc.
