### ISSUE TITLE
HOEJDEFIKSPUNKTDK.MIDDELFEJL

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#70]
Findes enten på observation eller koordinat

**Comment by Helle-Git** [comment]
Der anvendes SZ-felt-værdien fra den tilknyttede koordinat. (OBS kun aktuelle data)

**Comment by Helle-Git** [comment]
Afledes udfra ATTR-værdi, hvis den findes - søges i nævnte rækkefølge:
 ATTR:GI_punkt (337)          => 'plane netværk,GI fikspunkt'
 ATTR:Hjælpepunkt (338)    => 'plane eller højde netværk, hjælpepunkter'
 ATTR:MV_punkt (336)        => 'plane netværk,MV fikspunkt'
 ATTR:højdefikspunkt (335) => 'højde netværk'

Uvist hvad der skal ske, hvis der ikke er en af ovenstående
      ?? =>    'sømærker'
     ?? =>    'teknik punkter'

**Comment by kbevers** [comment]
Jeg forstår ikke lige det med ATTR:*. Måske forsimpler jeg problemstillingen, men er det ikke nok at finde nyeste DVR90-koordinat tilknyttet punktet? Noget i stil med

```
SELECT k.sz FROM koordinat k
JOIN punkt p
ON p.id=k.punktid
WHERE k.sridid=8 and k.registreringtil IS NULL AND p.id='91133808-2F01-7CAB-E053-1A041EACB67A';
```
naturligvis uden den afsluttende `AND p.id=...`

**Comment by Helle-Git** [comment]
Jo min første kommentar er den rigtige - den anden vedrører 'ARTSKODE'.

**Comment by kbevers** [comment]
Jeg har slettet kommentarerne vedrørende artskode. De håndteres i det relevante issue.

**Comment by kbevers** [comment]
Lukkes da feltets værdi er afklaret.

**Comment by Helle-Git** [comment]
Der er punkter, hvor der IKKE er en værdi i sz-feltet, hvilken værdi skal så benyttes??

Eksempel lokalid: 25715 

REGISTRERINGFRA | REGISTRERINGTIL | SRIDID | SX | SY | SZ | T | TRANSFORMERET | X | Y | Z
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2008 SEP 04 |   | 8 |   |   |   | 2004 FEB 20 12:42 | FALSK |   |   | 3,357
2004 FEB 20 | 2008 SEP 04 | 8 |   |   | 1 | 2004 FEB 20 12:42 | FALSK |   |   | 3,357
2002 MAR 05 | 2004 FEB 20 | 8 |   |   | 999 | 2002 MAR 04 12:00 | SAND |   |   | 3,36
2004 FEB 20 |   | 11 |   |   | 1 | 2004 FEB 20 10:30 | FALSK |   |   | 3,435
1986 MAY 23 | 2004 FEB 20 | 11 |   |   | 10 | 1944 JUL 01 00:00 | FALSK |   |   | 3,437

if UM er der bl.a. disse oplysninger om punktet:

ID_LOKALID | FIKSPUNKTSNUMMER | KOTE | ARTSKODE | MVSTATUS | MIDDELFEJL | KOTEKLASSE
-- | -- | -- | -- | -- | -- | --
25715 | K-41-09012 | 3,357 | overordnet højdefikspunktsnet | højde netværk | 999 | 3

**Comment by Helle-Git** [comment]
Værdien af middelfejl benyttes ifm fastlæggelse af værdien for KOTEKLASSE

**Comment by kbevers** [comment]
Det undrer mig meget at der findes koter uden usikkerhedsangivelse. Det lugter langt væk af fejl i migrationsscripts - jeg undersøger nærmere. Indtil der er afklaring på det er det bedste du kan gøre at sætte usikkerheden til 999 hvor den ellers er nul.

Har du set andre eksempler på punkter hvor z findes, men ikke sz?

**Comment by kbevers** [comment]
Der findes tilsyneladende 79 DVR90-koter der ikke har en usikkerhed tilknyttet koten:

```
SELECT count(*) FROM koordinat WHERE sridid=8 AND z IS NOT NULL AND sz IS NULL;
----
79
```

**Comment by Helle-Git** [comment]
Der er 53 punkter (de øvrige er med registreringtil <> NULL)

Jeg sender dig et regneark med koordinater og punktinfo for disse 53 punkter.
(Jeg ved ikke hvordan jeg vedhæfter det hertil).

**Comment by busstoptaktik** [comment]
Det omtalte punkt har også en "ekstern" id med producentnummer 8025. Kan det have noget med sagen at gøre?

    IDENT:refgeo_id     :  25715        
    IDENT:ekstern       :  8025/221-6011
    IDENT:landsnr       :  K-41-09012   
    REGION:DK           :               

Derudover ser det ud som om den gældende kote har overskrevet en tidligere med sz=1mm inden for samme minut:

    * 2004-02-20 09:30   DK:GI44         None, None, 3.435   (1.0) 
      1944-06-30 23:00   DK:GI44         None, None, 3.437   (10.0)
    * 2004-02-20 11:42   EPSG:5799       None, None, 3.357   (None)
      2004-02-20 11:42   EPSG:5799       None, None, 3.357   (1.0) 
      2002-03-04 11:00   EPSG:5799       None, None, 3.36   (999.0)

Der er i hvert fald stensikkert noget der er gået galt ved enten den originale koteindsætning eller migrationen til FIRE

**Comment by kbevers** [comment]
Jeg kan ikke huske hvad producent 8025 betyder.

https://github.com/Kortforsyningen/FIRE-DDL/issues/125 er relateret til dette problem. Der skal nok laves en lille ændring i migrationsscriptet sådan at der tildeles en usikkerhed på 999.0 til koter der ikke har en.

**Comment by busstoptaktik** [comment]
@mrlarshole er ved at slå det op :-)

**Comment by Helle-Git** [comment]
Lars Hole har tidligere skrevet at 8025 er Vejdirektoratet

**Comment by mrlarshole** [comment]
Undskyld, 8025 er banestyrelsen. De øvrige "falske" herredesnumre er:
PROD_NR	NAVN	FIRMA	ADRESSE1		POSTNR	POSTDIST	TELEFON	TELEFAX	DEBIREKV	DEBIBET	BETAL	KONTAKT	PASSW	VALDE	NYPROD_NR	IN_DATE
**8025**	DSB	Banestyrelsen Baneteknik	Vanløsealle 89	2720	Vanløse	19-06-1997 09:21:00
**4500**	Københavns Kommune	Stadskonduktørembedet	Ottiliavej 1	2500	Valby	33663366	33667091	10-11-1995 08:43:00
**4110**	Kystinspektoratet	Postbox 100	ATT. Hr. Kjeldgaard	Højbovej 1	7620	Lemvig
**4078**	Vejdirektoratet Motorvejskontoret	Postboks 529	Th. Helstedsvej 22	8660	Skanderborg	0	0	 10-11-1995 08:43:00

**Comment by busstoptaktik** [comment]
Antager at svaret er at vi ikke udstiller eksterne producenters materiale - og lukker
