### ISSUE TITLE
HOEJDEFIKSPUNKTDK.AFMAERKNINGSBESKRIVELSE

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#71]
Findes i diverse AFM-punktfinfotyper

**Comment by Helle-Git** [comment]
Find de aktuelle punktinfo med type 'AFM:<nummer>' som har anvendelse='TEKST' ;
og sammensæt teksterne for disse til een tekst.
(Hent en let transformeret og sammensat tekst fra alle punktets 'AFM:'-info-rækker.)

**Comment by kbevers** [comment]
Det er formentligt den rigtige strategi, men for en sikkerheds skyld kunne jeg godt tænkte mig at se et par eksempler på teksten i den nuværende udstillingsmodel og den nye tilsvarende tekst. Bare for 2-3 punkter.

**Comment by Helle-Git** [comment]
Eksempler på punkter med forskellige afm-tekster:
første tekst er den fra FIRE (NY_AFM_BESKR)


ID_LOKALID | PUNKTID | NY_AFM_BESKR | AFMAERKNINGSBESKRIVELSE

16009 | 92BBD366-30AE-4074-E053-1A041EACA7BF | Bolt. 0.65 m over terræn. | Bolt. 0.70 m over terræn.
16108 | 92BBD366-3110-4074-E053-1A041EACA7BF | Bolt mærket krone og G.I. 0.50 m over beton. | Bolt. 0.50 m over terræn.
13446 | 92BBD366-26AE-4074-E053-1A041EACA7BF | Plade mærket G.I. | Plade mærket G.I. 0.35 m over terræn.
21351 | 92BBD366-4589-4074-E053-1A041EACA7BF | Plade mærket G.I. 0.50 m over terræn. | Plade mærket G.I. 0.55 m over terræn.

**Comment by busstoptaktik** [comment]
@kbevers  er vi i mål her?

**Comment by kbevers** [comment]
Ja, det ser fint ud.
