### ISSUE TITLE
HOEJDEFIKSPUNKTDK.TEKSTBESKRIVELSE

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#72]
punktinfo( id=334 ~ ATTR:beskrivelse)
.tekst + afledt[årstal fra punktinfo.registreringfra]

**Comment by kbevers** [comment]
Er ovenstående muligt? Altså at bruge teksten fra ATTR:beskrivelse samt årstallet fra punktinfo.registreringfra?

**Comment by busstoptaktik** [comment]
@Helle-Git: Giver kommentaren fra @kbevers ovenfor mening - kan det bringes til at virke?

**Comment by Helle-Git** [comment]
Der kigges på ATTR-punkt-info.
Hvis den har 'ATTR:Tabtgået' returneres 'Tabtgået'.
Ellers returneres en sammenstilning af teksterne fra de 'AFM-%-TEKST'-beskrivelserne, samt en evt højde-angivelse hvor højden og dets 'basis' findes fra (AFM-%-TAL)-punktinfo.
(Der er ingen årstal i denne)
Eksempler:
Hul i midte af skifferplade på muret postament, ca. 0.96 m højt.
Universalkalot i cylindrisk støbning 30x80 cm. Til terræn.

**Comment by Helle-Git** [comment]
Det er sådan, det er lavet;  med den tilføjelse at der kommer sluttes med  '  GPS egnet', hvis punktet har ATTR:GNSS.
Dog sker der en del 'formatering' af teksten (blanke og CR LF etc)
