### ISSUE TITLE
HOEJDEFIKSPUNKTDK.HERREDSOGN_HERREDSNUMMER

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#74]
Skal afledes via polygoner over gamle herreder

**Comment by Helle-Git** [comment]
Hvordan / hvorfra hentes denne oplysning?

**Comment by busstoptaktik** [comment]
Sættes til 9999 hvis punktet ikke har noget landsnummer

**Comment by kbevers** [comment]
Og hvis den har et landsnummer, så er det 'xxx' i xxx-yyy-zzzzz, medmindre landsnummeret er på format 'K-yyy-zzzzz'.

**Comment by Helle-Git** [comment]
I UM er der brugt værdien 1, hvis der ikke er et nummer.
Foreslår at der også fremover benyttes 1 (i stedet for 9999).

**Comment by kbevers** [comment]
> Kan det være det herred som købstaden tilhører/tilhørte?

Det er det sikkert. Det gør det lidt sværere for os at tildele værdierne ud fra landsnummeret. Måske vi skal have en hjælpetabel?

**Comment by Helle-Git** [comment]
Der er lavet en tabel med købstadnr - herredsnummer; en købstads herredsnummer findes ved opslag i denne tabel.
Prefix fra fikspunktsnummer, herredsnummer og Købstadsnummer er:

Prefix | Herredsnummer | Købstadsnumer
K-01- | 1 | 1
K-02- | 5 | 2
K-03- | 3 | 3
K-04- | 8 | 4
K-05- | 10 | 5
K-06- | 12 | 6
K-07- | 8 | 7
K-08- | 15 | 8
K-09- | 18 | 9
K-10- | 16 | 10
K-11- | 25 | 11
K-12- | 21 | 12
K-13- | 23 | 13
K-14- | 25 | 14
K-15- | 22 | 15
K-16- | 28 | 16
K-17- | 26 | 17
K-18- | 32 | 18
K-19- | 29 | 19
K-20- | 26 | 20
K-21- | 138 | 21
K-22- | 140 | 22
K-23- | 140 | 23
K-24- | 138 | 24
K-25- | 137 | 25
K-26- | 139 | 26
K-27- | 47 | 27
K-28- | 49 | 28
K-29- | 52 | 29
K-30- | 47 | 30
K-31- | 48 | 31
K-32- | 47 | 32
K-33- | 51 | 33
K-34- | 39 | 34
K-35- | 38 | 35
K-36- | 34 | 36
K-37- | 40 | 37
K-38- | 33 | 38
K-39- | 44 | 39
K-40- | 132 | 40
K-41- | 41 | 41
K-42- | 45 | 42
K-43- | 43 | 43
K-44- | 132 | 44
K-45- | 56 | 45
K-46- | 53 | 46
K-47- | 54 | 47
K-48- | 53 | 48
K-49- | 55 | 49
K-50- | 61 | 50
K-51- | 66 | 51
K-52- | 61 | 52
K-53- | 60 | 53
K-54- | 74 | 54
K-55- | 70 | 55
K-56- | 83 | 56
K-57- | 75 | 57
K-58- | 94 | 58
K-59- | 87 | 59
K-60- | 87 | 60
K-61- | 92 | 61
K-62- | 96 | 62
K-63- | 102 | 63
K-64- | 107 | 64
K-65- | 106 | 65
K-66- | 104 | 66
K-67- | 116 | 67
K-68- | 131 | 68
K-69- | 113 | 69
K-70- | 119 | 70
K-71- | 122 | 71
K-72- | 126 | 72
K-73- | 118 | 73
K-74- | 122 | 74
K-75- | 135 | 75
K-76- | 130 | 76
K-77- | 134 | 77
K-78- | 142 | 78
K-79- | 141 | 79
K-80- | 149 | 80
K-81- | 148 | 81
K-82- | 147 | 82
K-83- | 152 | 83
K-84- | 155 | 84
K-85- | 155 | 85
K-86- | 156 | 86

**Comment by busstoptaktik** [comment]
@Helle-Git er denne tilstrækkeligt afklaret efter din hjælpetabel er oprettet?

**Comment by Helle-Git** [comment]
Jeg mener at denne er afklaret nu; hjælpetabellen bruges.
