### ISSUE TITLE
HOEJDEFIKSPUNKTDK.HERREDSOGN_KOEBSTADSNUMMER

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#75]
Skal formenligt afledes fra polygoner over herreder og sogne

**Comment by Helle-Git** [comment]
Hvordan / hvorfra hentes denne oplysning?

**Comment by busstoptaktik** [comment]
Sættes til 9999 hvis punktet ikke har noget landsnummer som er af købstadstype "K-nnn-nnnnn"

**Comment by kbevers** [comment]
Og hvis den har et landsnummer, så er det 'yyy' i K-yyy-zzzzz.

**Comment by Helle-Git** [comment]
I UM er der brugt værdien 0, hvis der ikke er et landsnummer.
Foreslår at der også fremover benyttes 0 (i stedet for 9999).
