### ISSUE TITLE
HOEJDEFIKSPUNKTDK.HERREDSOGN_SOGNENUMMER

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#76]
Skal afledes fra polygoner over gamle sogne

**Comment by Helle-Git** [comment]
Hvordan / hvorfra hentes denne oplysning?

**Comment by busstoptaktik** [comment]
Sættes til 9999 hvis punktet ikke har noget landsnummer

**Comment by kbevers** [comment]
Og hvis den har et landsnummer, så er det 'yyy' i xxx-yyy-zzzzz, medmindre landsnummeret er på format 'K-yyy-zzzzz' (sættes da til 9999)

**Comment by Helle-Git** [comment]
I UM er der brugt værdien 0, hvis der ikke er et nummer.
Foreslår at der også fremover benyttes 0 (i stedet for 9999).

**Comment by busstoptaktik** [comment]
@Helle-Git er denne afklaret?

**Comment by Helle-Git** [comment]
Der indsættes 0, hvis der ikke er et nummer (ikke 9999); så hvis det er som I vil have det; er det afklaret.

**Comment by busstoptaktik** [comment]
De oprindelige numre afgjordes af "historiske opmålingsdistriktgrænser", digitaliseret af en vis Karin en gang før 1980. De ligger på stien F:\REF\programmer\data\DIVERSE\Herred_sogn_mapinfo

Denne kommentar er også relevant for #74 og #75.

**Comment by Helle-Git** [comment]
Jeg har ikke adgang til 'F:\REF\programmer\data\DIVERSE\Herred_sogn_mapinfo'; 
så kan den evt. sendes til mig?  
Måske står der mere i den tabel, end jeg allerede har fundet frem til.
