### ISSUE TITLE
HOEJDEFIKSPUNKTDK.LOEBENUMMER

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#77]
Skal muligvis læses fra punktets landsnummer.

**Comment by Helle-Git** [comment]
I følge DDL for udstillingsmodellen, er det sidste del af fikspunktsnummer uden opmålingsdistrikt.
Der kan være foranstillede 0 og -, eks '-09001'

**Comment by busstoptaktik** [comment]
Sættes til 9999 hvis punktet ikke har noget landsnummer

**Comment by Helle-Git** [comment]
Der er fikspunkter af typen K-xx-zzzzz.åååå  de er af typen 'IDENT:Diverse'
Men i UM har de løbenr: -zzzzz.åååå 
Så her er løbenummeret ikke kun for landsnr (eller også burde disse være af kategori landsnummer)

**Comment by busstoptaktik** [comment]
@Helle-Git er denne afklaret?

**Comment by Helle-Git** [comment]
NEJ, ikke endelig afklaret.
som det er nu, bliver løbenummer ikke sat som i UM, for fikspunkter af typen 'K-xx-zzzzz.åååå'.
Der er (mindst) 3 muligheder:
A) Som det er nu, løbenummer bliver 'forkert' for disse fikspunkter. (Den nuværende algoritme og kode er OK)
B) Der ændres i udtræk til FIRE, så disse får infotype 'landsnr', så får de 'automatisk' det 'rigtige' løbenummer. (Den nuværende algoritme og kode er OK)
C) Der laves om i algoritmen, så disse genkendes, som nogle der skal have læbenummeret trukket so for 'landsnr'. (Den nuværende algoritme og kode skal ændres).

Jeg synes at B) er den mest rigtige løsning. 
(Og så kan dette issue lukkes, og der kommer et nyt med data i FIRE)

**Comment by kbevers** [comment]
B er den rigtige løsning. Der er rod i koden der registrerer hvilken type et ident er. Det er på min liste over ting der skal fikses. Det er ikke en hurtig løsning.

**Comment by Helle-Git** [comment]
Der er 258 punkter, som har formen  'K-xx-zzzzz.åååå' og identtypen diverse.
De er ikke blevet til 'Landsnr' endnu - og derfor kommer der forkert løbenummer på.

**Comment by kbevers** [comment]
Ja, det gjorde de
