### ISSUE TITLE
HOEJDEFIKSPUNKTDK.NORTHING

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#78]
Nordlig komponent af placeringskoordinat

**Comment by Helle-Git** [comment]
Afledes af GEOMETRI for det pågældende punkt

SELECT SDO_CS.TRANSFORM(g.geometri, 25832).sdo_point.y 
FROM geometriobjekt g
where g.punktid = punkt-id for det aktuelle punkt

[Ved sammenligning med data for punkter i GeodataBanken, er der mindre afvigelser på værdien - typisk er de ens inden for +/- 1 (når der ses bort fra decimaler).]

**Comment by kbevers** [comment]
Koordinatafvigelserne skyldes med stor sandsynlighed implementeringsforskelle i understøttelsen af koordinattransformationer. Det er forventeligt at Oracle leverer andre resultater end KMSTrans og PROJ. Vi lever med det - en meter fra eller til er ikke afgørende her.
