### ISSUE TITLE
HOEJDEFIKSPUNKTDK.EASTING

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#79]
Østlig komponent af placeringskoordinat

**Comment by Helle-Git** [comment]
Hvordan findes denne værdi?  
F.eks. for id_lokalid  4974 er den nuværende værdi i UdstillingsDB : 693855,44



--





--

**Comment by kbevers** [comment]
Vi taler om det punkt (eller egentligt koordinat) der frem ved følgende SQL, ikke?
```
SELECT k.* FROM koordinat k
JOIN punktinfo pi
ON k.punktid=pi.punktid
WHERE pi.infotypeid=344 AND pi.tekst='4974';
```

Det er et højdefikspunkt som kun har en kote i sin koordinat. Altså må både easting or northing udledes fra geometrien. Det er vist noget i den her dur:

```
SELECT SDO_CS.TRANSFORM(g.geometri, 25832).sdo_point.x FROM geometriobjekt g
JOIN punktinfo pi
ON pi.punktid=g.punktid
WHERE pi.infotypeid=344 AND pi.tekst='4974';
```

Tilsvarende kan northing fremskaffes ved at erstatte `x` med `y` i ovenstående.
