### ISSUE TITLE
HOEJDEFIKSPUNKTDK.KOTEKLASSE

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#80]
Hvilken værdi skal tildeles her?

**Comment by Helle-Git** [comment]
Den sættes altid til 3.
Hvilken værdi skal eller benyttes?

Beskrivelse af feltet:
Værdinavn    Dokumentation
    0    Punkter med artskode 1 og mvstatus mindre end 3
    1    Punkter med artskode mellem 1 og 6 og mvstatus mindre end 3 samt middelfejl mindre end 50 mm
    2    Enten punkter med artskode 6 og middelfejl mindre end 150 mm eller punkter med artskode mellem 1 og 6 og middelfejl større end 49 mm, og for begge med mvstatus mindre end 3
    3    Punkter med artskode 6 og mvstatus større end 2 eller middelfejl større end 149 mm

**Comment by busstoptaktik** [comment]
@kbevers arbejder på implementering af Aslaks algoritme

**Comment by mrlarshole** [comment]
Det ser ud til at i leger med at klasseindele kotepunkter med script til planfiks. Den går ikke. [https://github.com/Kortforsyningen/FIRE-DDL/issues/88#issuecomment-537997921](url)
Herunder fra rodekassen, nogle overvejelser vi gjorde os engang ifm klasseinddeling for koter, hvor afmærkningstypen er en vigtig parameter:
Koteklasser.
Kl. 0
		§ Punktsamling (INC-filer fra 5d-analyser, refnumre herunder, oprettes muligvis i tabellen NET af hensyn til SQL) 
		§ Nummertype G.M. og G.I.
		§ Afmtype(skal defineres)
		§ Middelfejl < 2 mm
				 
Kl. 1
		§ Alle andre,  minus klasse 0
		§ Minus metode 3
		§ Minus Afmtyper(skal defineres)
		§ Minus løbenummer >/= 90000
		§ Middelfejl < 5 mm
Kl. 2
		§ Alle andre minus kl 0. og kl 1.
		§ Plus metode 3
		§ Middelfejl < 50 mm
Kl. 3
§ Resten    
 
(11103, 21011, 24074, 51196, 61490, 74435, 782313, 128776, 133073, 141473, 149502, 161627, 182736,
182737, 182935, 191834, 221054, 231790, 231799, 292921, 852260, 327871, 327880, 330041, 330042, 384877, 386646, 861727, 452567, 478841, 482748, 849771, 850947, 485409, 729101, 596939, 529288, 879223, 536523,765083, 545933, 545934, 6456, 6457, 6458, 19536, 19531, 19532, 19534, 161630, 245087, 245088, 545899,545901, 543370, 543371, 543372, 538655, 538656, 538657, 11816, 11817, 11818, 127190, 127191, 127192,128923, 128924, 126195, 126196, 126197, 91047, 91048, 91049, 3030, 3031, 3032, 170108, 170110, 159704,159705, 159706, 242989, 242990, 242991, 245089, 245090, 245091, 237645, 237646, 237647, 32101, 32102,32103, 251132, 251133, 251134, 293035, 293036, 372994, 372995, 47100, 411365, 411366, 48746, 55058,55059, 55060, 62395, 62396, 62397, 543373, 536562, 536563, 536564, 60829, 60830, 60831, 61591, 61592,61593, 451297, 451298, 475962, 475963, 475964, 485471, 485472, 330140, 330141, 325771, 325772, 325773,321565, 321566, 321567, 321483, 321484, 321485, 319163, 319164, 283154, 283155, 283156, 269460, 269461,269462, 30844, 30845, 256555, 256556, 256557, 520778, 532538, 532539, 532540, 22003, 22004, 22005,191919, 191920, 191921, 24689, 24690, 24691, 203659, 203660, 203661, 170111, 478866, 478867, 320671,320672, 320673, 294126, 294127, 182420, 182423, 182894, 182932, 478868, 133077, 133078, 133079, 141966,141967, 141968, 450873, 450874, 538485, 538486, 543640, 543642, 253157, 186766, 415204, 330127, 330128,48747, 410253, 410254, 410255, 39333, 39334, 15602, 15603, 15604, 19006, 19007, 19008, 186767, 11122,11123, 11124, 546048, 546049, 546050, 63356, 63357, 63358, 29173, 25833, 25834, 51497, 51498, 415206,116342, 116343, 362379, 386651, 5152, 452874, 452875, 11125, 11126, 11127, 102046, 102047, 102048,5153, 5155, 5156, 11130, 11131, 450876, 354423, 60096, 60097, 729301, 734909, 729276, 734622, 757345,765212, 767168, 767169, 766823, 766824, 767084, 767085, 766670, 766671, 766734, 786160, 789309, 788759,
789204, 790777, 784472, 784439, 787637, 784466, 784495, 789612, 788601, 788599, 789617, 789616, 790422,794706, 794705, 794715, 794716, 794721, 794727, 794728, 794733, 794736, 795346, 790118, 794525, 789208,794524, 796130, 796129, 796136, 796134, 796139, 796151, 796137, 796132, 796131, 796135, 849541, 849542,848613, 849076, 849390, 849414, 849410, 851830, 851831, 851844, 596977, 790791, 851073, 851089, 851071,851096, 851803, 852235, 856764, 856765, 856766, 854487, 856968, 851080, 848596, 849062, 857691, 855133,855095, 10736, 853690, 855107, 855110, 855093, 788605, 783178, 855874, 855090, 855088, 855096, 855099,596672, 855089, 855098, 855875, 855111, 853632, 10738, 861818, 858169, 862412, 849722, 862463, 862661,862662, 862457, 862663, 862664, 854348, 862651, 862969, 862970, 862971, 862972, 862973, 566250, 862988,862994, 862992, 862993, 879220, 879221, 879222, 853633, 879216, 882228, 887342, 887343, 887399, 887400,887402, 887403, 887486, 887487, 887485, 51189, 520759, 444710, 467358, 415191, 46464, 46465, 60054,
60089, 28965, 29114, 47091, 47093, 47095, 161628, 245084, 11060, 11117)

Hej Frands, hermed et bud. Har ikke kørt den helt stor analyse, men jeg tænker at jeg vil komme med dette bud, og så må vi se…
 
Disse afm_typer er med:
Kl.0                      >1100, (1700 til 1708 -1706), 1900,1901, 1952,1953,1963.
Kl.1                      1955 til 1901, 1976,2700 til 2796, 2722,2777,2789,2793,2843 til 2852.
 
Prøv at se om du kan få det i kombination med resten, så tester vi.

Hej Lars 
 
Jeg har kun set på det samlede antal koter, ikke på lukkede versioner
 
Så der er fundet
Klasse                0                           293
Klasse                1                           69327
Klasse                2                           20525
Klasse                3                           45634
 
Frands

**Comment by Helle-Git** [comment]
Det kunne se ud til at der er en fejl i DDL vedr. værdier for dette felt ;( 
For der står:

Værdinavn | Dokumentation
-- | --
0 | Punkter med artskode 1 og mvstatus mindre end 3
1 | Punkter med artskode mellem 1 og 6 og mvstatus mindre end 3 samt middelfejl mindre end 50 mm
2 | Enten punkter med artskode 6 og middelfejl mindre end 150 mm eller punkter med artskode mellem 1 og 6 og middelfejl større end 49 mm, og for begge med mvstatus mindre end 3
3 | Punkter med artskode 6 og mvstatus større end 2 eller middelfejl større end 149 mm

**Comment by busstoptaktik** [comment]
> Det kunne se ud til at der er en fejl i DDL vedr. værdier for dette felt

Så er vi jo lidt mere frit stillet mht at opfinde noget nyt :-)

Fx: middelfejl over 5 mm ryger direkte i klasse 3

KL0: Middelfejl under 2mm og afm.type iflg Lars' tabel: 1700-1705, 1707, 1708,1900, 1901, 1952, 1953,1963
KL1: Middelfejl under 5mm og afm.type som i KL0, suppleret med  1955-1901 (her mentes formodentlig 1961), 1976, 2700-2796, 2722, 2777, 2789, 2793, 2843-2852.

KL2: udgår
KL3: Resten

@kbevers?

**Comment by Helle-Git** [comment]
Problemet er at mvstatus og artskode er tekster - ikke et tal; derfor er det ikke beskrevet hvad artskode 6 er.  Det stiller dig vel ikke mere frit ; for DDL kan vist 'ikke bare' ændres til ny beskrivelse.

**Comment by busstoptaktik** [comment]
@kbevers jeg kan ikke huske hvor langt denne er nået?

**Comment by kbevers** [comment]
Så vidt jeg lige kan regne ud har vi bestemt os for hvordan både mv_status og artskode skal håndteres. Så er det vel bare et spørsmål om at følge regler som beskrevet ovenfor:

```
0 Punkter med artskode 1 og mvstatus mindre end 3
1 Punkter med artskode mellem 1 og 6 og mvstatus mindre end 3 samt middelfejl mindre end 50 mm
2 Enten punkter med artskode 6 og middelfejl mindre end 150 mm eller punkter med artskode mellem 1 og 6 og middelfejl større end 49 mm, og for begge med mvstatus mindre end 3
3 Punkter med artskode 6 og mvstatus større end 2 eller middelfejl større end 149 mm
```

**Comment by Helle-Git** [comment]
Er nu lavet , men så 
Punkter med artskode 6 og mvstatus større end 2 eller middelfejl større end 149 mm
er tolket som 
Punkter med artskode 6 og mvstatus større end 2 
ELLER 
Punkter med middelfejl større end 149 mm

**Comment by busstoptaktik** [comment]
@Helle-Git jeg lukker denne som løst - du åbner igen hvis du er uenig :-)
