### ISSUE TITLE
HOEJDEFIKSPUNKTDK.KOMMUNEKODE

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#81]
Afledes af kommunepolygoner?

**Comment by Helle-Git** [comment]
Hvordan / hvorfra hentes denne oplysning?

**Comment by kbevers** [comment]
Vil du kommer med nogle eksempler på kommunekoder der bruges i den nuværende udstillingsmodel? Selvfølgelig med deres dertilhørende ident. 

Hvad siger modellens dokumentation om dette felt?

**Comment by Helle-Git** [comment]
Modellens dokumentation siger at det er den 4-cifrede CPR-kode, der entydigt angiver en kommune.

Der er pt anvendt 99 kommunekoder + blank.
Alle de anvendte kommunekoder er kendte som 'nuværende' kommuner.
Eksempler (de 2 første har ingen kommunekode, de 2 sidste har kommunekode 0376):

ID_LOKALID | ARTSKODE | FIKSPUNKTSNUMMER | KOMMUNEKODE
548071	fundamental punkt	                      199-01-99001	
548072	fundamental punkt	                       199-01-99002	
853464	overordnet højdefikspunktsnet	52-03-00849	0376
888031	overordnet højdefikspunktsnet	52-03-09106	0376

**Comment by busstoptaktik** [comment]
@Helle-Git jeg har checket med Lars: Der benyttes DAGI på placeringskoordinaten for at afgøre kommunekoden, så det er korrekt at der i dag kun skal være 99 forskellige.

Se i øvrigt også kommentarer under købstads-, herred- og sognenummer: issues #74, #75, #76
