### ISSUE TITLE
HOEJDEFIKSPUNKTDK.GMLID

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#82]
afledt af ’fiks.’<lokal_id>.YYYYDDMMhhmmss for sridid-rækken

**Comment by Helle-Git** [comment]
Sættes til ’fiks.’<lokal_id>.YYYYDDMMhhmmss 
Med dags dato for kørsel af overførselsprogram (så denne del er fælles for alle  GMLID)

**Comment by busstoptaktik** [comment]
@kbevers jeg er ikke sikker på status af denne pind. Kan den lukkes med Helles bud?

**Comment by kbevers** [comment]
Ja, det ser korrekt ud. Så vidt jeg kan se bør det være "registreringfra" datoen der benyttes til at lave GMDID.
