### ISSUE TITLE
Opret NET:DVR90

### ISSUE THREAD

**Issue by kbevers** [Kortforsyningen/FIRE-DDL#84]
Alle punkter der har definerende DVR90 koter tilknyttet sig skal have påført punktinfo attributten `NET:DVR90`. En liste over punkterne findes bagerst i DVR90-publikationen.

**Comment by Helle-Git** [comment]
Nogle punkter har dette attribut tilknyttet mange gange.
Jeg ser på om det er der - så det generer ikke min kode - kun mit øje ;) 
Men det skyldes måske at det er 'sat på i hånden, gennem flere omgange'

**Comment by kbevers** [comment]
> Men det skyldes måske at det er 'sat på i hånden, gennem flere omgange'

Ja. Jeg har brugt Python-API'et til at indsætte attributterne med og der var nogle fejl og mangler i koden. Det krævede et par forsøg at få rettet op på det. Næste gang vi migrerer skulle de gerne kun forekomme en gang pr. punkt.
