### ISSUE TITLE
PLANFIKSPUNKTDK.DKK10KMNET

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#85]
Hvis punktet hører til 10km-nettet bør der være en punktinfoattribut med navn i retning af NET:10km

**Comment by Helle-Git** [comment]
Der er nu denne fordeling:
 503819    false
       712    true


Og i FIRE , er der også 712 punkter (der ser ud til at være danske planfikspunkter), der har punktinfo 348 (NET:10KM) tilknyttet.

**Comment by busstoptaktik** [comment]
Antallet er troværdigt: Jeg har altid hørt det omtalt som at der er "cirka 710 10km-punkter". Lukker.
