### ISSUE TITLE
PLANFIKSPUNKTDK.ELLIPSOIDEHOEJDE

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#86]
Tredjekoordinaten ("Z") for disse SRIDid'er

- EPSG:4937 (DK og FO: Geografiske koordinater, ETRS89, 3D)
- EPSG4909  (GL: Geografiske koordinater, GR96, 3D)

**Comment by Helle-Git** [comment]
Fra DDL:

Definition: | Højde over den anvendte ellipsoiden.
-- | --
Beskrivelse: | Anvendt ellipsoide er ETRS89.
Multiplicitet: | 0..1


Hvis SRID **IKKE** er en af ovenstående, er der så ingen værdi? (feltet bliver NULL)

**Comment by kbevers** [comment]
> Hvis SRID IKKE er en af ovenstående, er der så ingen værdi? (feltet bliver NULL)

Korrekt. Dog med den præcisering at det KUN drejer sig om SRID EPSG:4937 da der her kun er tale om danske planfikspunkter. Den tilsvarende tabel for Grønland skal kun kigge tage ellipsoidehøjder fra EPSG:4909.

**Comment by Helle-Git** [comment]
Dvs ca 2100 punkter får dette attribut , ud af ca. 500.000 planfikspunkter.
I nuværende er der 2203 aktuelle planfikspunkter med værdi for ellipsoidehøjde

**Comment by kbevers** [comment]
Okay, det er jo ikke helt dumt. Har du et eksempel eller to på punkter der får en højde for nuværende men ikke har det med ovenstående tilgang?

**Comment by Helle-Git** [comment]
Nej, ikke endnu.

**Comment by Helle-Git** [comment]
Jeg har 4 punkter som eksempler hvor jeg ikke kan finde ellipsoidehøjde i FIRE; men der er en i Geobanken.
Her er de udtrukket med de gældende koordinater


SRIDID | SX | SY | SZ | TRANSFORMERET | X | Y | Z | PUNKTID
-- | -- | -- | -- | -- | -- | -- | -- | --
2 | 30 | 30 | 90 | SAND | 11,86420216 | 55,69211696 |   | 95582745-C16B-3280-E053-1A041EAC5624
22 | 30 | 30 |   | FALSK | 116368,702 | 141119,914 |   | 95582745-C16B-3280-E053-1A041EAC5624
2 | 999 | 999 | 2997 | FALSK | 12,36332461 | 55,81860998 |   | 95582750-5463-3280-E053-1A041EAC5624
8 |   |   | 5 | FALSK |   |   | 100,999 | 95582750-5463-3280-E053-1A041EAC5624
21 | 14 | 14 |   | FALSK | 324167,175 | 140655,297 |   | 95582750-5463-3280-E053-1A041EAC5624
22 | 999 | 999 |   | FALSK | 85394,5275 | 155986,9719 |   | 95582750-5463-3280-E053-1A041EAC5624
2 | 5 | 5 | 15 | SAND | 10,2391464 | 56,15319284 |   | 95582750-617D-3280-E053-1A041EAC5624
8 |   |   | 1 | FALSK |   |   | 2,05973 | 95582750-617D-3280-E053-1A041EAC5624
21 | 5 | 5 |   | FALSK | 218459,445 | 191457,475 |   | 95582750-617D-3280-E053-1A041EAC5624
73 |   |   | 1 | FALSK |   |   | 2,0921 | 95582750-617D-3280-E053-1A041EAC5624
2 | 1 | 1 | 3 | FALSK | 8,118343167 | 56,52312752 |   | 95582750-6C9F-3280-E053-1A041EAC5624
8 |   |   | 1 | FALSK |   |   | 22,556 | 95582750-6C9F-3280-E053-1A041EAC5624
14 | 1 | 1 |   | FALSK | 445758,8803 | 6264652,853 |   | 95582750-6C9F-3280-E053-1A041EAC5624
76 |   |   | 0 | FALSK |   |   | 22,56254 | 95582750-6C9F-3280-E053-1A041EAC5624

**Comment by busstoptaktik** [comment]
Nu kan jeg ikke lige gennemskue sammenhængen mellem SRIDID og SRID, men kan det tænkes at SRIDID=21 og 22 svarer til EPSG:23032 og EPSG:23033, altså ED50-koordinater, som er målt/beregnet i 3D?

**Comment by kbevers** [comment]
SRIDID 21 og 22 er System34. De væsentligste SRIDID'er kan du finde i tabellen herunder:

```
1	EPSG:4326	Geografiske koordinater 2D: WGS84
2	EPSG:4258	Geografiske koordinater 2D: ETRS89
3	EPSG:4937	Geografiske koordinater 3D: ETRS89
4	EPSG:4936	Geocentrisk kartesiske koordinater 3D: ETRS89
5	EPSG:4230	Geografiske koordinater 2D: ED50
6	EPSG:4231	Geografiske koordinater 2D: ED87
7	EPSG:5714	Kotesystem: Lokal middelvandstand
8	EPSG:5799	Kotesystem: Dansk Vertikal Reference 1990
9	DK:HPOT_DVR90	Kotesystem: Geopotentialhøjder DVR90
10	EPSG:5733	Kotesystem: Dansk Normal Nul
11	DK:GI44	Kotesystem: Dansk Normal Nul, Sjælland
12	DK:GM91	Kotesystem: Dansk Normal Nul, Jylland
13	DK:KN44	Kotesystem: Københavns nul 1944
14	EPSG:25832	Projicerede koordinater 2D: UTM zone 32, ETRS89
15	EPSG:23032	Projicerede koordinater 2D: UTM zone 32, ED50
16	EPSG:23033	Projicerede koordinater 2D: UTM zone 33, ED50
17	DK:GS	Projicerede koordinater 2D: Generalstabens Konformt Koniske System
18	DK:GSB	Projicerede koordinater 2D: Generalstabens Konformt Koniske System Bornholm
19	DK:KK	Projicerede koordinater 2D: Københavns Kommunes System
20	DK:OS	Projicerede koordinater 2D: System Ostenfeld
21	DK:S34J	Projicerede koordinater 2D: System 34 Jylland
22	DK:S34S	Projicerede koordinater 2D: System 34 Sjælland
23	DK:S45B	Projicerede koordinater 2D: System 45 Bornholm
24	DK:SB	Projicerede koordinater 2D: System Storebælt
25	EPSG:5317	Kotesystem: Færøsk Vertikal Reference 2009
26	EPSG:4747	Geografiske koordinater 2D: GR96
27	EPSG:4909	Geografiske koordinater 3D: GR96
28	GL:NAD83G	Geografiske koordinater 2D: NAD83G (DEPRECATED)
29	TS:LRL	Vandstandsbrætsnettilknytning
```

**Comment by busstoptaktik** [comment]
Første punkt har en ægte S34-koordinat, som så er blevet transformeret til ETRS89 - derfor er det den todimensionelle ETRS89-variant, med sridid=2 der er i spil. Men den har af en eller anden grund fået tildelt en spredning på tredjekoordinaten også...

Enten er det en fejl at den har en kote i UM, eller også er der nogle koordinater der ikke er kommet med over i FIRE (jeg kan ikke i skrivende stund lokalisere et punkt vha. dets UUID)

Andet punkt har BÅDE s34s og s34j-koordinater, men spredningen er sat til 999 på s34s-delen. Det er den også på den tilsvarende etrs89koordinat - så det kunne tyde på  at det i virkeligheden var en transformeret koordinat.

s34s og etrs89-koordinaterne passer sammen, men s34j-koordinaten passer som æøå i britisk retskrivning. Det er nu også lidt mærkeligt med en s34j-koordinat for et punkt der ligger i københavn!

Så har punktet også en dvr90-kote, så det burde være en universalkalot. Kan det tænkes at Frands har "opfundet" ellipsoidehøjder ved at transformere koter on the fly hvis der ikke var ellipsoidehøjder tilgængelige?

Det er i hvert fald sært med diskrepansen mellem s34s og s34j-koordinaten, så vi skal lige have kigget på  95582750-5463-3280-E053-1A041EAC5624 i refgeo og FIRE.

**Comment by busstoptaktik** [comment]
Lang vej rundt - men på workshop med Nikolaj Kamstrup 2019-10-31 nåede vi frem til en forklaring på hvordan dette kan opstå (hænger sammen med den uheldige opsplitning af 3D-koordinater i plan- og "højde" i REFGEO).

Konklusionen er at "det gør vi ikke noget ved"
@kbevers og @Helle-Git: jeg lukker denne nu
