### ISSUE TITLE
PLANFIKSPUNKTDK.GPSEGNET

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#87]
ATTR:gpsegnet?

**Comment by kbevers** [comment]
Ja, den hedder dog `ATTR:gnss_egnet`

**Comment by Helle-Git** [comment]
I de  nuværende gældende data, fordeles de på:
479564	ikke vurderet
7915	ikke egnet
14612	egnet
2440	måske egnet

De fleste er altså 'Ikke vurderet' - hvordan afgøres hvilke værdier, der skal benyttes.

Hvis ATTR:gnss_egnet er sat er det vel 'egnet'?
Men hvad hvis dette attribut IKKE findes???

**Comment by busstoptaktik** [comment]
> Men hvad hvis dette attribut IKKE findes???

Hvis attributten ikke findes er det ikke nødvendigvis egnet. Men vi skal vel også bare populere et felt der siger at det (i givet fald *er* egnet)

**Comment by Helle-Git** [comment]
Det er værdier fra PLANFIKSPUNKTDK.
I følge DDL, kan feltet indeholde de 4 værdier, og de har denne betydning:
Værdinavn	Dokumentation
**egnet  **      Egnet til opstilling af GPS måling.
**måske egnet**   Svært tilgængelig eller mindre egnet horisont.
**ikke egnet**  Ikke anvendelig til måling med GPS udstyr.
**ikke vurderet**  Ikke undersøgt mulighed for måling med GPS.

**Comment by busstoptaktik** [comment]
Med FIREs datamodel kan vi ikke gøre andet end at kalde alle med `ATTR:gnss_egnet` for "egnet", og alle andre for "ikke vurderet"
