### ISSUE TITLE
PLANFIKSPUNKTDK.KLASSE

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#88]

**Comment by Helle-Git** [comment]
Fordeling i nuværende udstillingsmodel:
 klasse antal
0	773
1	1177
2	371151
3	125633
	5797

**Comment by kbevers** [comment]
Jeg ved ikke hvad "klasse" betyder i denne sammenhæng

**Comment by Helle-Git** [comment]
I DDL står:
Klasse er et kvalitetsudtryk for koordinaten.
Den er beregnet ud fra værdierne af artskode, mvstatus og middelfejl.

**Comment by mrlarshole** [comment]
Det er en klasseinddeling primært til det matrikulære system, men bredt ud til de øvrige planfikspunkter. Det er ikke muligt at inddele koter efter samme.

sådan ser det ud for levering til LDS, planfikspunkter.
 
 
/* Indtil videre sættes i_klasse til 4
*  hvis den ikke sættes af nedenstående.
*  Klasse 0
*/
if (u2_artskode == 1 && m_mv_status < 3)
  i_klasse = 0;
/*  Klasse 1 */
if ((1 < u2_artskode && u2_artskode < 6) &&
    (m_mv_status < 3 && u2_cmf < 50))
  i_klasse = 1;
/*  Klasse 2 */
if (((u2_artskode == 6 && u2_cmf < 150) ||
    (1 < u2_artskode && u2_artskode < 6 && u2_cmf > 49)) &&
    m_mv_status < 3)
  i_klasse = 2;
/*  Klasse 3 */
if (u2_artskode == 6 && (m_mv_status > 2 || u2_cmf > 149))
  i_klasse = 3;

**Comment by Helle-Git** [comment]
Lars's beskrivelse svarer helt til beskrivelsen i DDL; 
MEN nu er artskode og mvstatus ikke længere numeriske værdier; og jeg ved ikke hvilken numeriske værdi, der svarer til de enkelte tekster.


Værdinavn | Dokumentation
-- | --
0 | punkter med artskode 1 og mvstatus mindre end 3
1 | Punkter med artskode mellem 1 og 6 og mvstatus mindre end 3 samt middelfejl mindre end 50 mm.
2 | Enten punkter med artskode 6 og middelfejl mindre end 150 mm eller punkter med artskode mellem 1 og 6 og middelfejl større end 49 mm, og for begge med mvstatus mindre end 3.
3 | Punkter med artskode 6 og mvstatus større end 2 eller middelfejl større end 149 mm.

**Comment by busstoptaktik** [comment]
OK - hvis vi, som foreslået ovre i #69, lader mvstatus=1 være GI, 2 være MV og 0 være "alt det andet lort som matrikelvæsenet ikke er interesseret i, så **tror** jeg (men check  mig lige, please) at det  bliver til:

**For mvstatus=0 eller hypot(sx,sy) > 149mm**
[Klasse=3]

**For mvstatus != 0:**
[Klasse=0]: artskode=1
[Klasse=1]: artskode 1-6 og hypot(sx,sy) < 50 mm
[Klasse=2]: resten

**Comment by kbevers** [comment]
Det virker umiddelbart korrekt

**Comment by Helle-Git** [comment]
Jeg kan ikke se at denne beskrivelse af MVSTATUS svarer til #69, og slet ikke at den svarer til beskrivelsen i DDL. 
Jeg er kommet frem til at sammenhængen mellem MVSTATUS nr og tekst er:
0 ~højde netværk
1 ~plane netværk, MV fikspunkt
2~plane netværk, GI fikspunkt
3 ~plane eller højde netværk, hjælpepunkter
4 ~sømærker
5 ~teknik punkter
6 ~aerotriangulations punkter

**Comment by mrlarshole** [comment]
[diverse_forklaringer_3_lrh_v3.xlsx](https://github.com/Kortforsyningen/FIRE-DDL/files/3803356/diverse_forklaringer_3_lrh_v3.xlsx)
Jeg har tidligere fremsendt regneark med de tekstforklaringer der blev benyttet udstillingsmodellen blev lavet tilbage i 2015. Altså relationen mellem numerisk værdi i REFGEO og tekst i UM.
(vedhæftet)

**Comment by busstoptaktik** [comment]
#69 siger:

> hvis hverken MV eller GI er sat kan vi vel sætte status til 0 og ignorere at det kan betyde 3-5?

Altså: punkter (koordinater) der er matrikulært uinteressante får MVSTATUS=0 ligegyldigt hvad der så har stået oprindeligt - vi skelner ikke mellem 0,3,4,5.

Derfor får alle punkter med MVSTATUS=0 KLASSE=3 (de frarådes til matrikulært brug).
Det samme gør alle punkter med spredning over 150 mm.

Jeg kan vist bedre beskrive det i C:

    int klasse (artskode, mvstatus, sx, sy) {
        double sd = hypot (sx, sy);

        /* Matrikulært ubrugelige punkter */
        if (mvstatus==0) return 3;
        if (sd > 150) return 3;

        /* Matrikulært antagelige punkter */
        if (sd < 50) {
            if (artskode==1) return 0;
            else return 1;
        }

        /* matrikulært bop-bop-elige punkter*/
        return 2;
    }

**Comment by busstoptaktik** [comment]
### Efterrationalisering efter at have set effekten af ovenstående

Ovenstående algoritme ser fornuftig ud, men fører i praksis til alt for mange opklassificeringer ifht. algoritmen fra den Frands'ke kode.

Men da artskoder nu medmigreres til FIRE, så kan vi genindføre den Frands'ke algoritme (se nederst for beskrivelse fra @kbevers). Herved reproduceres de eksisterende klasseinddelinger eksakt, men nye koordinater tildeles klassen NULL, da de ikke har nogen artskode tilknyttet. Dette afspejler simpelthen at artskode og planklasser er begreber fra en svunden tid og en ikke-længere-aktuel beregnings- og databaserepræsentationsprocedure.

Hvis der konstateres problemer i den anledning må artskoden håndholdes for GNSS-beregningsilæggelse: For moderne GNSSmålte koordinater vil den typisk kunne sættes til 1, 2 eller 3. Hermed vil koordinaten tildeles klassen 1 (modulo MV_STATUS).

```c
/* Beregning af klasse for utm32_etrs89 koordinater */
    i_io_klasse     = -1;
    /*  Klasse 0 */
    if (c_artskode == 1 && m_mv_status < 3) {
      i_io_klasse   = 0;
      strcpy(io_klasse, "0");
    }
    /*  Klasse 1 */
    if ((1 < c_artskode && c_artskode < 6) && (m_mv_status < 3 && c_cmf < 50)) {
      i_io_klasse = 0;
      strcpy(io_klasse, "1");
    }
    /*  Klasse 2 */
    if (((c_artskode == 6 && c_cmf < 150) || (1 < c_artskode && c_artskode < 6 && c_cmf > 49)) && m_mv_status < 3) {
      i_io_klasse     = 0;
      strcpy(io_klasse, "2");
    }
    /*  Klasse 3 */
    if (c_artskode == 6 && (m_mv_status > 2 || c_cmf > 149)) {
      i_io_klasse   = 0;
      strcpy(io_klasse, "3");
```
>
> hvor c_cmf er middelfejlen. Resten giver vist sig selv. Artskoden findes som en del af koordinater i FIRE og mv_status kan udledes fra ATTR-punktinfo. Værdierne er som følger
> 
> 0.	ATTR:højdefikspunkt
> 1.	ATTR:MV_punkt
> 2.	ATTR:GI_punkt
> 3.	ATTR:hjælpepunkt
> 4.	ATTR:sømærke
> 5.	ATTR:teknikpunkt
> 6.	ATTR:aerotriangulationspunkt
> 
> Med det in mente burde ovenstående kunne oversættes til SQL i mapningen fra FIRE til UM, det bliver dog nok lidt mere kluntet end Frands’ C-kode…
