### ISSUE TITLE
PLANFIKSPUNKTDK.REFDK

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#89]
NET:REFDK vil jeg regne med

**Comment by Helle-Git** [comment]
Fordeling i Udstillingsmodellen:
 false  504442   
 true           89

**Comment by kbevers** [comment]
Der skal være 692 REFDK punkter i alt. Der er sandsynligvis en del af REFDK-punkterne der er restricted (ATTR:restricted, punktinfotypeid=329). Det stemmer formentligt med ovenstående, men det må hellere tjekkes efter.

**Comment by Helle-Git** [comment]
Jeg ser ikke på om de er restrictede - jeg ser kun på felt-værdien INDEN de restrictede 'sorteres fra'.
I DDL står at der vil være 95 punkter.

**Comment by kbevers** [comment]
> Jeg ser ikke på om de er restrictede

Det tror jeg du bliver nødt til - offentligheden må ikke se de restrictede punkter.

**Comment by Helle-Git** [comment]
De, der offentliggøres er UDEN de restrictede - men jeg sammenligner med de data der OGSÅ indeholder de restrictede.
Det kan så være at der er 95 'offentlige' og bør være 692 offentlige+restrictede.
(Men jeg fandt altså  89 ialt)

**Comment by busstoptaktik** [comment]
iflg. KMS technical report vol 15 (https://sdfe.dk/media/2919811/kms_technical_report_15.docx) består refdk-nettet af nedenstående 98 punkter (som jo altså er lidt mere end 89 - kan det have været en tastefejl?)

    AGGE
    AGRI
    ANST
    AVAN
    BAVN
    BLAA
    BORR
    BRUN
    BUDP
    DEGN
    DZMA
    EIER
    ESBC
    EVAD
    FAKK
    FLYY
    GALG
    GESR
    HANS
    HESB
    HIRS
    HLBJ
    HNBO
    HVIG
    JHOJ
    KIGU
    LASO
    LERU
    LINH
    LSIG
    LUMS
    LYSH
    MALH
    MULD
    MYGD
    NOLM
    NYHO
    PRES
    RLDO
    ROMO
    SANB
    SIRL
    SKAM
    SLKJ
    SMHJ
    SMID
    SORR
    STAG
    SULD
    TAMD
    TEBB
    THOJ
    TISE
    TYVH
    VAEG
    VORK
    VRAA
    ANBO
    VIBY
    VEJR
    ONSB
    RRSO
    BOGE
    UTTE
    TOST
    ASSE
    HOLE
    MAGL
    SYNN
    SNOD
    KOGS
    EJBY
    PUGE
    MOEL
    GAAB
    MRVE
    KONG
    HSHJ
    BUDD
    KVAN
    NYRU
    SBJE
    DYRE
    PBAN
    BKAL
    KLIP
    EMME
    POTH
    RIBE
    LIST
    PEDE
    ROEN
    TEJN
    FERR
    AGE1
    OSBY
    HABY
    TEJH
