### ISSUE TITLE
sidetabel:SPECIALNUMMER

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#90]
```
- OBJECTID             INTEGER                                      
- NUMMER               VARCHAR2 (4000 Byte)            
- NUMMERTYPE           VARCHAR2 (4000 Byte)            
- ID_LOKALID           VARCHAR2 (48 Byte)                
- DATO_OPRETTET        TIMESTAMP(0)
- DATO_NEDLAGT         TIMESTAMP(0)                            
```

**Comment by Helle-Git** [comment]
Hvilke data skal ind i denne tabel?
- For hver tabeltype; f.eks. HOEJDEFIKSPUNKTDK

**Comment by kbevers** [comment]
Den her er ikke helt nem i øjeblikket. Jeg tror jeg er nødt til at tilføje flere IDENT:-typer for at vi kan reproducere den eksisterende tabel. I øjeblikket bliver stationsnumre, eksterne numre og fotonumre alle klassificeret som IDENT:diverse. Jeg vil forsøge at gøre det mere granulært, sådan at der for hver nummertype i specialnummer tabellen findes en tilsvarende IDENT:xxx. Måske lige med undtagelse fotonummer og hjælpepunkter der kun optræder henholdsvis 4 og 2 gange i tabellen.

**Comment by kbevers** [comment]
Ja, det kan det. De seks punkter med enten fotonummer og hjælpepunktnummer må udgå fra udstillingsmodellen. De har alligevel ikke nogen nævneværdig værdi.

**Comment by Helle-Git** [comment]
Hvilke data skal over i SPECIALNUMMER-tabellen?  Er det ALLE informationer med IDENT:xxx  (som IKKE er fikspunktsnummer) for punktet?

**Comment by kbevers** [comment]
Ja, med undtagelse af IDENT:refgeo_id. De skal kategoriseres på følgende måde:

```
Stationsnummer (type 2) == IDENT:station
Landsnummer (type 1)	== IDENT:landsnr
GPS nummer (type 8)		== IDENT:gnss
Ekstern nummer (type 7)	== IDENT:ekstern
Hjælpepunkter (type 5)	== IDENT:diverse
Nivellementspunkter (type 3) == IDENT:GI
Fotonummer (type 4)     == udgår
```

Der vil ikke blive et komplet 1 til 1 match men det bør være tæt på. Det er i hvert fald godt nok.

**Comment by Helle-Git** [comment]
Specialnummer-tabellen benyttes fra alle 8 tabeller.
Er det samme kategorier, der skal benyttes for alle?
Det ser pt. ud til at der ikke er nogle specialnumre for de grønlandske punkter på UM; 
vil det altid være sådan - eller er det en 'tilfældighed'?

**Comment by kbevers** [comment]
> Er det samme kategorier, der skal benyttes for alle?

Det vil jeg mene, ja.

**Comment by Helle-Git** [comment]
Jeg har nu kigget på data for de nordtalantiske højdefikspunkter, 

’fra’ | antal UM | nummertype | Antal Fire
-- | -- | -- | --
Færøske | 56 | GPS nummer (type 8) | 56
  | 958 | Stationsnummer (type 2) | 41
  |   |   |  
Grønland | 0 | GPS nummer (type 8) | 98
  | 0 | Hjælpepunkter (type 5) | 2

**Comment by kbevers** [comment]
Det ser fint ud for Grønland. Det undrer mig at GNSS-identerne ikke har været tilgængelige før.

Det ser dog lidt mærkeligt ud med de færøske. Kan du komme med et par eksempler på stationsnumre der optræder i REFGEO-UM men ikke i FIRE-UM?

**Comment by Helle-Git** [comment]
Eksempler på Færøske specialenumre, der KUN findes i UM:


NUMMER | NUMMERTYPE | ID_LOKALID | FIKSPUNKTSNUMMER
-- | -- | -- | --
12809 | Stationsnummer (type 2) | 727445 | 162-07-00809
19796 | Stationsnummer (type 2) | 727445 | 162-07-00809
27018 | Stationsnummer (type 2) | 860694 | 19912
NORD | GPS nummer (type 8) | 862807 | 88022
