### ISSUE TITLE
sidetabel:HOEJDEFIKSPUNKTDK_PUNKTDESC

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#93]
HOEJDEFIKSPUNKTDKOBJECTID                        INTEGER                                      
PUNKTDESC                                                           VARCHAR2 (4000 Byte)

**Comment by Helle-Git** [comment]
Hvilke data skal ind her?

Pt vælges på baggrund af punktinfo tilknyttet punktet, der indsættes for hver punktinfo; MEN er det disse infotyper, der skal mappes på denne måde???

'ATTR:restricted'  begrænset adgang'
'ATTR:ekstern' eksternt etableret'   
'AFM:naturlig' 'naturligt fikspunkt'
'ATTR:Tabtgået' 'afmærkning tabtgået'

**??? 6,7,8,9,10,11,12,13, 27 ??** 'postament'   
 
6	AFM:1000	Postament ca. 50x50 cm.           
7	AFM:1001	Postament ca. 34x34 cm.
8	AFM:1002	Postament ca. 45x45 cm.
9	AFM:1003	Postament 60x60 cm.
10	AFM:1005	Cylindrisk postament ca. 38 cm i diameter.
11	AFM:1006	Cylindrisk postament ca. 50 cm i diameter.
12	AFM:1007	Granitpostament 34x34 cm. omsluttet af betonstøbning 70x70 cm.
13	AFM:1099	Postament.
27	AFM:1704	Messingbolt i granitpostament.

**Comment by kbevers** [comment]
Ja, det ser ud til at være de punkttyper der er i spil.

```
SELECT count(punktdesc), punktdesc
FROM fikspunkt_l1.hoejdefikspunktdk_punktdesc
GROUP BY punktdesc
ORDER BY count(punktdesc) DESC;
```
giver
```
COUNT   PUNKTDESC
27367	afmærkning tabtgået
8382	begrænset adgang
395	    postament
22	    naturligt fikspunkt
21	    eksternt etableret
```

Der kan sikkert godt være punkter der har flere af ovenstående attributter tilknyttet. Er det tilfældet må de tildeles i prioriteret rækkefølge: ATTR:Tabtgået, ATTR:restricted, <POSTAMENT>, AFM:naturlig, ATTR:ekstern. 

Hvad angår <POSTAMENT> så er det som du har bemærket ikke helt lige til. Mit bedste bud er at finde punkterne via `punktinfo` tabellen, fx ved

```
SELECT * FROM punktinfo WHERE lower(tekst) LIKE '%postament%';
```

Det resulterer dog i ~1500 punkter. Formentligt vil en del af dem blive sorteret fra på ATTR:tabtbået og ATTR:restricted. Hvis det ikke er tilfældet må vi prøve at fintune udtrykket yderligere.
