### ISSUE TITLE
PLANFIKSPUNKTDK - generelt

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/FIRE-DDL#96]
Første ønske/krav er at kunne identificere de punkter, der skal med.
Jeg (dvs. @Helle-Git) har her fået en lang række sridid-numre, som er kendetegnende for dem.
(SRIDID 1-6, 14-24, 26-18).

Den algoritme giver ca. 630.000 punkter fra FIRE. I udstillingsmodellen er der ca. 504.000.

Derudover har stor del af disse har flere sæt koordinater – med forskellige sridid-numre;
hvor skal koordinat-oplysningerne hentes fra? (Der er nogle af punkterne, der har 5 gældende koordinater).

Det drejer sig om oplysninger som bruges til at finde værdier til felterne KOTE, ARTSKODE, MIDDELFEJL og VIRKNINGFRA

(Hvis algoritmerne fra højdefikspunkterne skal genbruges)

**Comment by kbevers** [comment]
SRID 26-28 er grønlandske koordinater, så de bør i hvert fald ikke regnes med i tabellen for Danmark. Derudover, ifølge Lars, udstilles der kun geografiske koordinater for planfikspunkter. Så, prøv at justere algoritmen til kun at inkludere SRID'er med ID 2 og 3. Hvor mange punkter resulterer det i?

**Comment by Helle-Git** [comment]
Der er 508051 punkter, hvis der KUN medtages SRIDID 2 og 3.

**Comment by kbevers** [comment]
Det er da i hvert fald den rigtige størrelsesorden. Hvordan er fordelen af antallet af punkter for henholdsvis SRIDID 2 og 3? Kan det tænkes at fx SRIDID=3 indeholder de ~4000 overskydende punkter?

**Comment by Helle-Git** [comment]
Fordelingen mellem 2 og 3 er:
2 505885
3 2166
Så det kan ikke - alene - forklare forskellen.

**Comment by kbevers** [comment]
Tak. Nej, vi kom dog tættere på. Mit bedste gæt er at der bliver sorteret nogle flere punkter fra så snart resten af tabellen skal udfyldes. Jeg synes bare vi skal arbejde videre med det her indtil videre i hvert fald.

**Comment by Helle-Git** [comment]
Eksempler på lokalid, mm for punkter som findes som planfikspunkter i FIRE; en ikke er kendt som sådan i nuværende PLANFIKSPUNKTDK-tabel.

ID_LOKALID | PUNKTID | FIKSPUNKTSNUMMER
-- | -- | --
853224 | 92BBD372-115A-4074-E053-1A041EACA7BF | 8025/102-6047
853227 | 92BBD372-115D-4074-E053-1A041EACA7BF | 8025/102-6052
853243 | 92BBD372-116D-4074-E053-1A041EACA7BF | 8025/102-6121
853270 | 92BBD372-1188-4074-E053-1A041EACA7BF | 8025/15-6022
852714 | 92BBD372-0F95-4074-E053-1A041EACA7BF | 8025/53-6026
852715 | 92BBD372-0F96-4074-E053-1A041EACA7BF | 8025/53-6029
853092 | 92BBD372-10EC-4074-E053-1A041EACA7BF | 8025/12-6060

**Comment by kbevers** [comment]
Alle de nævnte punkter har en ATTR:højdefikspunkt attribut, hvilket i hvert fald strider imod at det skal være et planfikspunkt. Underligt nok har de tilhørende koordinat IKKE nogen højde tilknyttet. Det er en fejl. Jeg ved ikke hvor den stammer fra, men hvis den kommer fra REFGEO så kan det tænkes at man i den nuværende overførsel til geobanken sorterer punkter fra som er markeret som et højdefikspunkt.

**Comment by Helle-Git** [comment]
Der er ca. 504000 (aktuelt gældede) punkter i UMs tabel.
Der er ca. 508000 punkter i FIRE, der opfylder udtrækskrit; heraf har de ca. 8000 en ATTR:højdefikspunkt attribut. 
Så kommer der til at mangle ca. 4000 punkter .
Skal jeg frasorterede de punkter der har ATTR:højdefikspunkt attribut?

**Comment by kbevers** [comment]
@busstoptaktik burde den så ikke også have en attribut der redegør for at det også er et planfikspunkt? Til gengæld har de alle en ident der antyder at punktet kommer fra en ekstern leverandør eller enhed. Så måske er de bare fejlregistrerede? Det kunne være interesant at se om tallene passer bedre hvis man sorterer punkter fra der har IDENT:ekstern (punkterne i tabellen ovenfor har i øvrigt ikke landsnumre efter seneste migration, så de bør måske heller ikke kunne findes i UM?)

**Comment by busstoptaktik** [comment]
> punkterne i tabellen ovenfor har i øvrigt ikke landsnumre efter seneste migration, så de bør måske heller ikke kunne findes i UM?

Det lyder plausibelt - hvad siger @mrlarshole?

**Comment by mrlarshole** [comment]
Punkterne i tabellen ovenfor har et specielt landsnummer hvor der er opfundet er et herredsnummer som ikke findes i virkeligheden. Det svarer i stedet til producentnummer i samme tabel. f.eks er prodnummer 8025 vejdirektoratet. De er ikke udstillet/overført. Andre "kunstige" herredsnumre: 4078, 4110, 4500. Det er således jo ikke alt fra refgeo der overføres. 

Desuden kan et punkt sagtens være både i planfikspunkt og højdefikspunkt. Der findes en pæn fællesmængde.

Håber jeg fik svaret på det der blev spurgt om. Sidder netop inde i UM og skriver om UM.

**Comment by Helle-Git** [comment]
Ovenstående punkter er pt. ikke at finde i FIRE; måske de ikke overføres efter Kristians ændringer til overførsel fra REFGEO.

**Comment by kbevers** [comment]
> Ovenstående punkter er pt. ikke at finde i FIRE; måske de ikke overføres efter Kristians ændringer til overførsel fra REFGEO.

Jeg er ikke med på hvilke punkter du mener? Dem fra tabellen du skrev for et par uger siden?

**Comment by Helle-Git** [comment]
Ja, de punkter som var omtalt længere oppe (for 2½ uge siden), og som Lars har kommenteret på.

**Comment by Helle-Git** [comment]
Undskyld Det er mig, der har set forkert - de ER med; men har (selvfølgelig) fået nye punktid, da de er trukket ud fra REFGEO igen.  Der er tilsyneladende ikke landsnr på disse; men de er markeret med 'IDENT:ekstern'.
Lars antyder at der kan udledes  herredsnumre fra disse - skal der det? - 
Udover at der skal ses på om det er fiktive numre, og punktet derfor ikke skal videre til UM.

**Comment by mrlarshole** [comment]
Med fare for at vi taler forbi hinanden :0)
De findes ikke i UM! eksempel: select * from FIKSPUNKT_L1.planfikspunktdk where id_lokalid= 853224
-og tilsvarende fra hoejdefikspunkt og sys34 returner 0.

**Comment by Helle-Git** [comment]
Netop - de findes IKKE i UM; men var kandidater til at komme dertil med det nye overførsel fra FIRE til UM.  Der skal så findes et kriterium, der frasorterer dem.

**Comment by busstoptaktik** [comment]
> Der skal så findes et kriterium, der frasorterer dem.

Det løst formulerede kriterium er så at punkter med producentnummer, altså punktnumre der matcher dette regexp:

    [0-9]*/[0-9]*-[0-9]*

ikke skal overføres.

Om det betyder at der skal sættes yderligere flag i @kbevers' præprocessering, eller om betingelsen kan sættes op direkte i mappingkoden - det har jeg så ingen idé om.

@kbevers,  @Helle-Git: Har I det?

**Comment by kbevers** [comment]
Umiddelbart lyder det som de punkter jeg klassificerer som IDENT:ekstern:

https://github.com/Kortforsyningen/FIRE-DDL/blob/d571d3a262afe8e927b54cbda88c668b9adc12de/pre-migration/identer/parse_idents.py#L45-L46

**Comment by busstoptaktik** [comment]
> Umiddelbart lyder det som de punkter jeg klassificerer som IDENT:ekstern

Yderst original betegnelse :-)

**Comment by busstoptaktik** [comment]
> Sidder netop inde i UM og skriver om UM

Det minder mig om et konstruktivistisk 1960erdigt af Vagn Steen:

UM
Sagde sproget.
Jeg vendte hende om.
MU
sagde hun

Den er fra samlingen "Digte?", fra ca. 1964.

**Comment by busstoptaktik** [comment]
@Helle-Git og @kbevers - konklusionen må m.a.o. være at punkter der har en IDENT:ekstern ikke skal overføres til UM

**Comment by Helle-Git** [comment]
Der blev i dag sagt at der ALDRIG skal punkter med, hvor koordinaterne er tranformerede.
Hvis de frasorteres er det ialt ca. 9000 punkter - jeg forventer ca. 505000.
Hvis de ikke frasorteres er der ca. 508000.  (Nogle af de 'overskydende' kan måske sorteres fra, når der kigges på IDENT'er etc).
SÅ mon ikke de transformerede koordinater skal tages med i betragtning?

**Comment by kbevers** [comment]
> SÅ mon ikke de transformerede koordinater skal tages med i betragtning?

Jo, det må de hellere. Det er lige voldsomt nok at sortere SÅ mange punkter fra :-) Jeg håber du er enig @busstoptaktik

**Comment by busstoptaktik** [comment]
> Hvis de frasorteres er det ialt ca. 9000 punkter - jeg forventer ca. 505000.
> Hvis de ikke frasorteres er der ca. 508000. (Nogle af de 'overskydende' kan måske sorteres fra, når der kigges på IDENT'er etc).

Undskyld, men jeg er ikke sikker på at jeg forstår meningen. Står der at 505000 punkter bliver til 9000 hvis man frasorterer de transformerede?

Det er selvfølgelig ikke aldeles utænkeligt, for i en lang periode blev punkterne målt og regnet i System GS eller System 34. Men jeg havde ventet at der var en del punkter der var målt ind i det gamle datum ED50.

Er pointen mon så at det er alle disse som over en kam er transformeret til ETRS89, og så har vi over de sidste 30 år GNSS-målt 9000 punkter i alt?

Det lyder også lidt omfattende i betragtning af at REFDK er på under 800 punkter. Og selv med hele 10km-nettet lyder det usandsynligt at vi skulle være kommet op på 9000 GNSS-målte punkter i alt.

Måske er der blevet indberettet en del GNSS-målinger fra landinspektører der har genmålt punkter i MV-nettet?

@Helle-Git kan du komme til at se hvor mange planfikspunkter, markeret som ikke-transformeret, der også indgår i hhv GI og MV nettene?

**Comment by busstoptaktik** [comment]
Det var godt nok noget færre end jeg regnede med. Så konklusionen er vel at vi medtager punkter transformeret til gældende system (ETRS89), men ikke punkter transformeret til System34.

**Comment by Helle-Git** [comment]
Det overordnede udvalgskriterium er nu udvidet, så der KUN medtages punkter, som har tilknyttet mindst eet gældende IDENT:-attribut (som ikke er landsnr ). Dvs mindst en af disse:
IDENT:landsnr, IDENT:GNSS, IDENT:GI , IDENT:diverse eller IDENT:jessen

**Comment by Helle-Git** [comment]
Det viser sig at der er ER landsnr knyttet til ALLE de relevante punkter, der har REGION:DK;
MEN de 8, der er fra REGION:SJ har 'kun' IDENT:diverse - og de ser lidt underlige ud.


ID_LOKALID | FIKSPUNKTSNUMMER | PUNKTID
-- | -- | --
703855 | SJ  86140141 | 98CC3943-14CD-2190-E053-1A041EAC2FFF
674146 | SJ  70970436 | 98CC3942-A100-2190-E053-1A041EAC2FFF
659779 | SJ  70280003 | 98CC3942-68E1-2190-E053-1A041EAC2FFF
659798 | SJ  70280022 | 98CC3942-68F4-2190-E053-1A041EAC2FFF
659192 | SJ  70240326 | 98CC3942-6696-2190-E053-1A041EAC2FFF
659144 | SJ  70240252 | 98CC3942-6666-2190-E053-1A041EAC2FFF
669501 | SJ  70691361 | 98CC3942-8EDB-2190-E053-1A041EAC2FFF
673787 | SJ  70970055 | 98CC3942-9F99-2190-E053-1A041EAC2FFF
